<?php
declare(strict_types=1);

/*
 * Writes the database's current structure and reference data into the repo, so a new
 * database (a fresh local one, or Dreamhost's) can be built from source:
 *
 *   db/schema.sql   CREATE TABLE for every table (as the migrations have left it)
 *   db/seed.sql     the reference tables' rows (sizes, attributes, scales, skills, ...)
 *
 * Saved items are never written; the item catalog has its own importer (dev/import-catalog.mjs).
 * Run from the project root after applying a migration, and commit the result:
 *
 *   php dev/dump-db.php
 */

const REFERENCE_TABLES = ['attribute', 'attributescale', 'attributespecialization', 'itemsize', 'itemtype', 'limitationtype', 'skills'];

$root = dirname(__DIR__);
$config = require $root . '/config/config.php';
$db = $config['db'];
$pdo = new PDO(
    sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $db['host'], $db['port'] ?? 3306, $db['name']),
    $db['user'],
    $db['pass'],
    // Native prepares return INT columns as PHP ints, so the seed writes 1, not '1'.
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
     PDO::ATTR_EMULATE_PREPARES => false, PDO::ATTR_STRINGIFY_FETCHES => false]
);

$tables = $pdo->query('SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() ORDER BY TABLE_NAME')
    ->fetchAll(PDO::FETCH_COLUMN);

// ---- schema -------------------------------------------------------------------------------
$schema = [
    '-- The database structure, generated by `php dev/dump-db.php`. Don\'t edit by hand:',
    '-- change the database with a migration (db/migrations), then regenerate this file.',
    '--',
    '-- New database: run this, then db/seed.sql. An existing database only needs the',
    '-- migrations it hasn\'t had yet. CREATE TABLE (no DROP) so it can\'t wipe a live database.',
    '',
    '-- Tables are in name order, not dependency order.',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
];
foreach ($tables as $table) {
    $create = $pdo->query("SHOW CREATE TABLE `$table`")->fetch()['Create Table'];
    $schema[] = preg_replace('/\s+AUTO_INCREMENT=\d+/', '', $create) . ';';
    $schema[] = '';
}
$schema[] = 'SET FOREIGN_KEY_CHECKS = 1;';
$schema[] = '';
file_put_contents("$root/db/schema.sql", implode("\n", $schema));

// ---- reference data -----------------------------------------------------------------------
$seed = [
    '-- Reference data, generated by `php dev/dump-db.php`. Run after db/schema.sql on a new database.',
    '-- Regenerate (don\'t edit by hand) after a migration that changes these tables.',
    '',
    'START TRANSACTION;',
    '',
];
foreach (REFERENCE_TABLES as $table) {
    if (!in_array($table, $tables, true)) {
        throw new RuntimeException("Reference table '$table' doesn't exist.");
    }
    // Primary-key order, so a regenerated file only differs where the data did.
    $key = $pdo->query("SELECT COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE
                         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '$table' AND CONSTRAINT_NAME = 'PRIMARY'
                         ORDER BY ORDINAL_POSITION")->fetchAll(PDO::FETCH_COLUMN);
    $order = $key === [] ? '' : ' ORDER BY `' . implode('`, `', $key) . '`';
    $rows = $pdo->query("SELECT * FROM `$table`$order")->fetchAll();

    $seed[] = "-- $table (" . count($rows) . ' rows)';
    if ($rows === []) {
        $seed[] = '';
        continue;
    }
    $columns = '`' . implode('`, `', array_keys($rows[0])) . '`';
    $values = array_map(static function (array $row) use ($pdo): string {
        $cells = array_map(static fn ($v): string => $v === null ? 'NULL' : (is_int($v) ? (string) $v : $pdo->quote((string) $v)), $row);
        return '    (' . implode(', ', $cells) . ')';
    }, $rows);
    $seed[] = "INSERT INTO `$table` ($columns) VALUES\n" . implode(",\n", $values) . ';';
    $seed[] = '';
}
$seed[] = 'COMMIT;';
$seed[] = '';
file_put_contents("$root/db/seed.sql", implode("\n", $seed));

printf("Wrote db/schema.sql (%d tables) and db/seed.sql (%s).\n", count($tables), implode(', ', REFERENCE_TABLES));
