# One entry per errata line. changes: (item_name or None, field, old, new)
O=None  # original errata (no date)
D5='2026-09-25'; D6='2026-09-26'
E=[]
def e(section,p1,p2,subject,kind,added,text,changes=()):
    E.append(dict(section=section,p1=p1,p2=p2,subject=subject,kind=kind,added=added,text=text,changes=list(changes)))
C='Combat'; IC='Item Creation'; G='Gear'; P='Psionics'
e(C,183,None,'Plasma Attacks','rule',O,'Plasma Weapon Attacks should be +2 Multiplier versus shields, not "Double Damage" as described here. This brings it in line with the description for Counter: Shields on P212.',
  [(None,'Effect against Force Fields','Double Damage','+2 Weapon Multiplier')])
e(C,183,None,'Terran psionic Force Fields','rule',O,"Terran Sphere psionics using force fields circumvent the restriction on Psionic effects by having a gap in their force field's protection. This means that their force fields may be bypassed by aimed or area attacks that happen while they are using their powers. Normally this vulnerability only lasts for the Psionics turn, leaving them vulnerable to sustained attacks, but ongoing effects require the gap to remain open and exploitable.")
e(C,185,None,'Armor reduction duration','rule',O,"Armor Reduction from Coordinated Fire or from attacks with Counter: Armor persists until the end of the round, allowing subsequent players to take advantage of the target's weakened state.")
e(C,191,None,'Battle Strain: missile salvos','rule',O,'Battle strain can be spent on a 1 to 1 basis to increase the number of missiles in a salvo. This can not be used in conjunction with the Coordinated fire effect.')
e(C,191,None,'Battle Strain: Tags and extra actions','rule',O,'Using Battle Strain to Activate Tags or Perform Extra Actions with a unit does not fall under the single Battle Strain expenditure per round rule. Additional extra actions after the first cost increasing multiples of 3 Battle Strain (6, 9, etc...) as per the extra actions for AP rule.')
e(C,191,None,'Attached characters: skill switch','rule',O,"A character attached to a unit may use Tags and their personal AP to skill switch from the unit's target number on to their corresponding skill.")
e(C,194,None,'Missile attacks vs margin of defense','rule',O,"Missile attacks reduce their targets' total margin of defense by the number of attacking missiles in the salvo not -1 per salvo launched at the target. This reduction is not restricted to their bonus margin of defense from anti missile fire.",
  [(None,'Margin of defense reduction','-1 per salvo','-1 per missile in the salvo')])
e(IC,210,None,'Attack: turrets','rule',O,'Omission of Turret rules from Attack attribute - Spending the base cost for an attack multiple times allows additional gunners to make attacks with the weapon, or the same gunner assuming he spends the action points. The Ships of the Line design exercise starting on page 219 provides an example of these rules in action.')
e(IC,210,None,'Attack: Melee','rule',O,'Melee attacks can never gain the Area attribute.')
e(IC,212,None,'Counter: Armor','rule',O,'Counter Armor no longer can bypass non-partial armor on an aimed attack. Instead on an unaimed attack it will reduce armor by 1. Aimed attacks will grant an additional 1 armor reduction for the attack, bringing the aimed attack to -2 armor. However, the armor reduction contributed to other attacks remains at -1 armor.',
  [(None,'Armor reduction','-2, or ignore armor on an aimed attack','-1 unaimed; -2 aimed; -1 carries to other attacks')])
e(IC,213,None,'Drive: Reactionless','rule',O,'Reactionless drives should not expel Reaction Mass.',
  [(None,'Reaction mass','Expels reaction mass','Does not expel reaction mass')])
e(IC,216,None,'Power Supply: minimum item size','rule',D5,'A Moderate Power Supply may be installed on a Small item (the table lists Medium). Major Power Supplies still require a Large item, except that the compact Hyperspace Tap and Coil implementations can squeeze a Major Power Supply into a Medium item.',
  [(None,'Minimum size: Moderate','Medium','Small'),(None,'Minimum size: Major (Hyperspace Tap or Coil)','Large','Medium')])
e(IC,217,None,'Resource: Fuel grade','rule',D5,'A Fuel Resource can feed Drives and Power Supplies of its own grade or lower. A larger fuel tank can feed a smaller drive (for example, Major Fuel can feed a Moderate Reaction Drive), but never the reverse.',
  [(None,'Fuel grade','Same grade as the Drive/Power Supply','Same grade or higher')])
e(G,226,271,'Firearms skill name','clarification',D6,'Equipment Modifiers listed for "Sidearms" should read "Firearms". Sidearms is an earlier name for the personal weapon skill.',
  [(None,'Modifier skill','Sidearms','Firearms')])
e(G,226,271,'Multiplier printing error','clarification',D6,'Several stat blocks printed an Armor or Attack Multiplier rank as the final value, leaving out the base rank, so the printed Armor Rating or Weapon Multiplier is one step too low. The affected items are corrected individually below.')
e(G,226,None,'Psionic Light Armor','stat',O,"Psionic Light Armor's fuel should read 10 Days/Combat turns instead of \"1 Day\".",
  [('Psionic Light Armor','Charge duration','1 day','10 days / combat turns')])
e(G,226,None,'Camouflage Suit','stat',D6,"The Camouflage Suit's Armor Rating is 4 (Firefight), not 3.",
  [('Camouflage Suit','Armor Rating','3 (Firefight)','4 (Firefight)')])
e(G,227,None,'Riot/LEO Armor, Psi Variant','stat',O,'Riot/LEO Armor, Psi Variant, fuel should also be 10 Days/Combat turns.',
  [('Riot/LEO Armor, Psi Variant','Charge duration','1 day','10 days / combat turns')])
e(G,227,None,'Standard Powered Armor','stat',O,'Standard Powered Armor possesses Battlefield, not Firefight level armor.',
  [('Standard Powered Armor','Armor scale','Firefight','Battlefield')])
e(G,228,None,'Kavacha Powered Armor','stat',O,'Kavacha Powered Armor possesses Battlefield, not Firefight level armor. This applies to both the A-350 Marine Engagement Suit and the A-350SR Marine Reconnaissance Suit.',
  [('Kavacha-class A-350 Marine Engagement Suit','Armor scale','Firefight','Battlefield'),('Kavacha-class A-350SR Marine Reconnaissance Suit','Armor scale','Firefight','Battlefield')])
e(G,230,None,'Quality Gauss Pistol','stat',D6,"The Quality Gauss Pistol's attack increases to 3x from 2x.",
  [('Quality Gauss Pistol','Weapon Multiplier','2x','3x')])
e(G,230,None,'Heavy Gauss Pistol','stat',D6,"The Heavy Gauss Pistol's single-target attack increases to 3x from 2x. The burst fire mode remains 2x.",
  [('Heavy Gauss Pistol','Weapon Multiplier (single target)','2x','3x')])
e(G,230,None,'Concealable Pistol','stat',D6,"The Concealable Pistol's attack increases to 3x from 2x, it gains Modifier: Firearms +2, and its ammunition increases to 4 Minor Ammunition (40 shots) from 3 (30 shots).",
  [('Concealable Pistol','Weapon Multiplier','2x','3x'),('Concealable Pistol','Modifier','none','Firearms +2'),('Concealable Pistol','Ammunition','3 Minor (30 shots)','4 Minor (40 shots)')])
e(G,231,None,'Wellpoint Armory Stormguard 9MP','stat',O,'Wellpoint Armory Stormguard 9MP ammo now costs CR 1 instead of "3x".',
  [('Wellpoint Armory Stormguard 9MP','Ammunition cost','3x','CR 1')])
e(G,231,None,'Security Gauss Rifle','stat',D6,"The Security Gauss Rifle's single-target attack increases to 4x from 3x. The burst fire mode remains 3x.",
  [('Security Gauss Rifle','Weapon Multiplier (single target)','3x','4x')])
e(G,232,None,'Plasma Carbine','stat',O,'The Plasma Carbine has the following changes: Weapon multiplier increases to 4x from 3x, Ammo cost is CR 1, not 5x, and it loses the Area attack attribute, to be replaced with Counter: Armor.',
  [('Plasma Carbine','Weapon Multiplier','3x','4x'),('Plasma Carbine','Ammunition cost','5x','CR 1'),('Plasma Carbine','Area','Small Sudden','none'),('Plasma Carbine','Counter','none','Armor')])
e(G,232,None,'Sniper Rifle','stat',D6,"The Sniper Rifle's attack increases to 5x from 4x.",[('Sniper Rifle','Weapon Multiplier','4x','5x')])
e(G,233,None,'Explosive Grenade','stat',D6,"The Explosive Grenade's attack increases to 6x from 5x.",[('Explosive Grenade','Weapon Multiplier','5x','6x')])
e(G,233,None,'Tactical Railgun','stat',D6,'The Tactical Railgun is a Small item, not Medium. Its Hungry limitation is a Moderate limitation. Its attack remains 4x.',
  [('Tactical Railgun','Size','Medium','Small'),('Tactical Railgun','Limitation grade: Hungry','Minor','Moderate')])
e(G,234,None,'Light Plasma Cannon','stat',O,'Light Plasma cannon ammo now costs CR 1.',[('Light Plasma Cannon','Ammunition cost','5x','CR 1')])
e(G,235,None,'Personal Psi Link','stat',O,'Personal Psi Link should read Moderate instead of Major Power Supply. Strain should be 10 not 25 - This is the most important change on the list, as starting Psionics were more powerful than intended as a result.',
  [('Personal Psi Link','Power Supply','Major Coil','Moderate Coil'),('Personal Psi Link','Strain Threshold','25','10')])
e(G,237,None,'Advanced Neural Interface Control Link','stat',D5,"The Advanced Neural Interface Control Link's [Dance Along the Bleeding Edge, But You Might Get Cut] is a Major Limitation, not a Tag: hacking that breaches the user's defenses can inflict physical damage.",
  [('Advanced Neural Interface Control Link','[Dance Along the Bleeding Edge, But You Might Get Cut]','Tag','Major Limitation')])
e(G,238,None,'Psi Amp','stat',O,'The Psionic Strain on Psi Amps reduced from +25 to +10.',[('Psi Amp','Psionic Strain','+25','+10')])
e(G,238,None,'Telekinetic Shuttle','stat',O,'The Telekinetic Shuttle now has a Major Psi Link.',[('Telekinetic Shuttle','Link','none','Major Psi')])
e(G,239,None,'"Fluffy"','stat',D6,'"Fluffy" has Armor Rating 3 (Firefight), not 2.',[('“Fluffy”','Armor Rating','2 (Firefight)','3 (Firefight)')])
e(G,242,None,'Light Performance Aircraft','stat',D6,'The Light Performance Aircraft has Armor Rating 2 (Firefight), not 1.',[('Light Performance Aircraft','Armor Rating','1 (Firefight)','2 (Firefight)')])
e(G,245,None,'Attack Hovercraft','stat',D6,"The Attack Hovercraft's heavy railgun single-target attack increases to 5x from 4x. The burst fire mode remains 4x.",
  [('Attack Hovercraft','Weapon Multiplier (single target)','4x','5x')])
e(G,245,None,'Armored Personnel Carrier','stat',D6,"The Armored Personnel Carrier has Armor Rating 4 (Battlefield), not 3. Its heavy gauss gun's single-target attack increases to 5x from 4x; the burst fire mode remains 4x. Its troop bay is a Major Hangar, not Minor.",
  [('Armored Personnel Carrier','Armor Rating','3 (Battlefield)','4 (Battlefield)'),('Armored Personnel Carrier','Weapon Multiplier (single target)','4x','5x'),('Armored Personnel Carrier','Hangar','Minor','Major')])
e(G,246,None,'Autonomous Kill Vehicle','stat',D6,"The Autonomous Kill Vehicle's light particle beam increases to 5x from 4x. It gains a Major Coil Power Supply (rank 1) with 1 Major Charge (10 combat rounds) to power the beam. Its Maneuver drops to 3 from 5. Its \"ineffective at Far Range\" restriction becomes a Moderate Limitation: No Far Range. Total Power Slots: 3 Moderate (0 used), 3 Major (1 used).",
  [('Autonomous Kill Vehicle (“Auntie”)','Weapon Multiplier','4x','5x'),('Autonomous Kill Vehicle (“Auntie”)','Power Supply','none','Major Coil, rank 1'),('Autonomous Kill Vehicle (“Auntie”)','Charge','none','1 Major (10 combat rounds)'),('Autonomous Kill Vehicle (“Auntie”)','Maneuver','5','3'),('Autonomous Kill Vehicle (“Auntie”)','Limitation','Usage Restriction (ineffective at Far Range), Minor','No Far Range, Moderate'),('Autonomous Kill Vehicle (“Auntie”)','Total Power Slots','3 Moderate (1 used)','3 Moderate (0 used), 3 Major (1 used)')])
e(G,247,None,'Stealth FTL Recon Drone','replacement',D5,"The Stealth FTL Recon Drone's stat block is replaced. The original build left out the cost of its Shrouded Hull. Corrected stats: Size Medium, CR 6, CC 21. Armor Rating 1 (Space, Shrouded); Body Track 10. Drives: Moderate Reaction, Major Gravitic, Maneuver 2; Resource: 2 Major Fuel (shared by both Drives). Communications: Major (Ansible; Resource: 1 Major Tangle). Computer: Minor 4 (20 target, 5 tasks); Tasks: Piloting 17, Detection 19, Intrusion Detection 15. Tags: [Security 2], [I Spy with my Little Eye...]. Limitations: One Track Mind (Moderate; follows its programmed route), One-Time Use (Major; each drone is burned out by its run and requires an extended Engineering roll to be brought back into service). Total Power Slots: 3 Moderate (0 used), 3 Major (0 used).",
  [('Stealth FTL Recon Drone','CR','5','6'),('Stealth FTL Recon Drone','CC','15','21'),('Stealth FTL Recon Drone','Body Track','15','10'),('Stealth FTL Recon Drone','Fuel','5 Moderate + 1 Major','2 Major (shared)'),('Stealth FTL Recon Drone','Maneuver','4','2 (Major grade)'),('Stealth FTL Recon Drone','Tangle','2 Major','1 Major'),('Stealth FTL Recon Drone','Tags','[High Security 3], [I Spy with my Little Eye...]','[Security 2], [I Spy with my Little Eye...]'),('Stealth FTL Recon Drone','Limitations','none','One Track Mind (Moderate), One-Time Use (Major)')])
e(G,253,None,'Tanker/Command Ship','stat',D5,"The Tanker/Command Ship's 100 ranks of Major Fuel are bulk fuel stores carried as Cargo, not the ship's own Fuel Resource. Pumping fuel from the storage tanks into a ship's systems requires an Engineering check.",
  [('Tanker/Command Ship','Fuel','100 Major Fuel (Resource)','Bulk fuel stores carried as Cargo')])
e(G,253,None,'Tanker/Command Ship','stat',D6,'The Tanker/Command Ship has Armor Rating 4 (Space), not 3.',[('Tanker/Command Ship','Armor Rating','3 (Space)','4 (Space)')])
e(G,254,None,'Dragon-class Fleet Interceptor/Escort','stat',D5,'The Dragon-class Fleet Interceptor/Escort is missing the auxiliary Major Fusion Power Supply described in its design notes. Its Power Slots become 6 Moderate and 3 Major.',
  [('Dragon-class Fleet Interceptor/Escort','Power Supply','none','Major Fusion, rank 1 (auxiliary)'),('Dragon-class Fleet Interceptor/Escort','Total Power Slots','6 Moderate (6 used)','6 Moderate, 3 Major')])
e(G,255,None,'Bridgehead Assault Shuttle','stat',D6,'The Bridgehead Assault Shuttle has Armor Rating 4 (Space), not 3, and its rapid plasma cannon increases to 5x from 4x.',
  [('Bridgehead Assault Shuttle','Armor Rating','3 (Space)','4 (Space)'),('Bridgehead Assault Shuttle','Weapon Multiplier','4x','5x')])
e(G,255,None,'Phantom DRIV','stat',O,'The Phantom DRIV possesses a Moderate Laser Link.',[('Phantom Deep Recon and Insertion Vehicle (DRIV)','Communication','none','Moderate Laser Link')])
e(G,258,None,'Standard (Conventional) Frigate','stat',O,'Skeleton Crew of Standard Frigate up to 100, from 10, Full Complement to 200, from 20.',
  [('Conventional Frigate','Crew Requirement','10 skeleton, 20 full','100 skeleton, 200 full')])
e(G,259,None,'Resolute-class Frigate','stat',D6,'The Resolute-class Frigate has Armor Rating 5 (Space), not 4, and its laser turret increases to 7x from 6x.',
  [('Resolute-class Frigate','Armor Rating','4 (Space)','5 (Space)'),('Resolute-class Frigate','Weapon Multiplier','6x','7x')])
e(G,261,None,'Fleet Auxiliary','stat',D5,"The Fleet Auxiliary's 300 ranks of Major Fuel are bulk fuel stores carried as Cargo, not the ship's own Fuel Resource. Pumping fuel from the storage tanks into a ship's systems requires an Engineering check.",
  [('Fleet Auxiliary','Fuel','300 Major Fuel (Resource)','Bulk fuel stores carried as Cargo')])
e(G,262,None,'Arniston','stat',O,'The Arniston is missing its Power Slots listing: 6 Major, 3 Used.',[('Arniston (Unique Armed Merchantman)','Total Power Slots','missing','6 Major (3 used)')])
e(G,264,None,'Heavy Railgun','stat',O,'Heavy Railgun - Attack increases from 6 to 7, body to 50.',[('Heavy Railgun','Weapon Multiplier','6x','7x'),('Heavy Railgun','Body Track','10','50')])
e(G,264,None,'Heavy Laser Cannon','stat',O,'Heavy Laser Cannon - Attack increases from 7 to 8, body to 50.',[('Heavy Laser Cannon','Weapon Multiplier','7x','8x'),('Heavy Laser Cannon','Body Track','10','50')])
e(G,267,None,'Cover Identity programs','clarification',D5,"Cover Identity and Good Cover Identity are Tiny items. The identity is stored on a chip (such as an ident card or passport) and runs on whatever computer reads the chip, spoofing that reader. The reader needs a Minor computer or better; its Tasks run at the lower of their own TN and the reader's max TN.",
  [('Cover Identity','Size','not printed','Tiny'),('Good Cover Identity','Size','not printed','Tiny')])
e(G,268,None,'Tse Blade','stat',O,'Tse Blade attack multipliers increase to 5x.',[('Tse Blade','Weapon Multiplier (both attacks)','4x','5x')])
e(G,268,None,'Shohan Personal Armor','stat',O,'Shohan Personal Armor possesses Battlefield, not Firefight level armor.',[('Shohan Personal Armor','Armor scale','Firefight','Battlefield')])
e(G,269,None,'War Drone (Cerberus)','stat',O,"Shohan War Drone's Body increases to 80, armor increases to 5.",[('War Drone (Cerberus)','Body Track','40','80'),('War Drone (Cerberus)','Armor Rating','4','5')])
e(P,278,None,'Astral Projection','rule',O,'Astral Projection costs 1 strain per round or scene that the character maintains the projection.',[(None,'Strain cost','','1 per round or scene maintained')])
e(P,285,None,'Necromancy: sacrificing attunements','rule',O,'Necromantic attunements may be sacrificed to gain strain at 10 points for every rank of the attunement.')
e(P,285,None,'Necromancy: shunting damage','rule',O,'Necromancers may shunt damage to their strain track at a 1 to 1 ratio, previously this was 3 strain for every point of damage.',[(None,'Damage-to-strain ratio','3 strain per 1 damage','1 strain per 1 damage')])
D7='2026-09-27'
e(G,229,None,'Knife','stat',D7,'The Knife gains Limitation: Usage Restriction (Firefight targets only; useless against Battlefield or hull armor), Minor.',
  [('Knife','Limitation','none','Usage Restriction (Firefight targets only), Minor')])
e(G,233,None,'Tactical Missile Rack','stat',D7,'The Tactical Missile Rack gains Limitation: Slave (Moderate). It is a module mounted on and powered by a host unit.',
  [('Tactical Missile Rack','Limitation','none','Slave (host unit), Moderate')])
e(G,235,None,'Carry Comp','stat',D7,"The Carry Comp's computer is rank 4 (20 target, 5 tasks), not rank 3.",
  [('Carry Comp','Computer','Minor 3 (18 target)','Minor 4 (20 target)')])
e(G,236,None,'Personal G3P','stat',D7,"The Personal G3P's [Hobbyist Builder's Best Friend] Tag is rank 3.",
  [('Personal G3P',"Tag rank: [Hobbyist Builder's Best Friend]",'1','3')])
e(G,237,None,'Basic Neural Interface Control Link','stat',D7,"The Basic Neural Interface Control Link's Initiative Modifier is +1, not +2.",
  [('Basic Neural Interface Control Link (NICL)','Modifier: Initiative','+2','+1')])
e(G,237,None,'Reflex Enhancements','stat',D7,'Reflex Enhancements gain the Tag [Need For Speed].',
  [('Reflex Enhancements','Tag','none','[Need For Speed]')])
e(G,242,None,'Light Air Transport','stat',D7,'The Light Air Transport gains Task: Intrusion Detection 17.',
  [('Light Air Transport','Tasks','Autopilot 20','Autopilot 20, Intrusion Detection 17')])
e(G,243,None,'Cargo Transport','stat',D7,"The Cargo Transport's Tag is [Security 2], not [Security].",
  [('Cargo Transport','Tag rank: [Security]','1','2')])
e(G,266,None,'Security programs: sizes','clarification',D7,'Basic Security Software and Security Software are Small items. Traceback and Honey Pot are Tiny add-on modules for a larger security suite.',
  [('Basic Security Software','Size','not printed','Small'),('Security Software','Size','not printed','Small'),('Traceback','Size','not printed','Tiny'),('Honey Pot','Size','not printed','Tiny')])
e(G,267,None,'Military-Grade Security','stat',D7,'Military-Grade Security loses its Compromise Task. [I See You 3] and [Like Fort Knox 3] are Free Tags ([Like Fort Knox] was rank 1), and it gains the Free Tag [This Is A Private Conversation 2].',
  [('Military-Grade Security','Tasks','Intrusion Detection 20, Trace 20, Compromise 20','Intrusion Detection 20, Trace 20'),('Military-Grade Security','Tag','[I See You 3]','[I See You 3] (Free)'),('Military-Grade Security','Tag','[Like Fort Knox]','[Like Fort Knox 3] (Free)'),('Military-Grade Security','Tag','none','[This Is A Private Conversation 2] (Free)')])
e(G,266,None,'Security Software','stat',D7,'Security Software gains the Free Tags [This Is A Private Conversation 2] and [I See You 2].',
  [('Security Software','Tag','none','[This Is A Private Conversation 2] (Free)'),('Security Software','Tag','none','[I See You 2] (Free)')])
e(G,266,None,'Honey Pot','stat',D7,'Honey Pot\'s [The Wages of Sin] Tag is rank 2.',
  [('Honey Pot','Tag rank: [The Wages of Sin]','1','2')])
e(IC,209,212,'Software: required computer','rule',D7,'Software no longer requires a computer rank by size. Instead, program size sets the computer grade it needs. Tiny, Small, and Medium programs need a Minor computer, carry 1 or 2 Tasks, and serve a single user. Large and Huge programs need a Moderate computer, carry multiple Tasks, and serve dozens of users at once. Colossal programs need a Major computer and serve hundreds of users at once. Computer rank no longer limits program size; it only caps Task target numbers. A Task runs at its own TN or the computer rank\'s maximum TN, whichever is lower. Replace every "Required Computer Rank" in program stat blocks with the matching Required Computer Grade.',
  [(None,'Software requirement','Required Computer Rank (by size)','Required Computer Grade (by size)'),(None,'Task TN on a lower-rank computer','not allowed','runs at the computer rank\'s max TN')])
e(G,271,None,'Resistance Lumber Mech','stat',D7,"The Resistance Lumber Mech's Body Track is 70, not 80. Its Coil Power Supply uses 2 Moderate Charge, not Fuel. [Kinetic Feedback Control Rig] is a Free Tag (free Skill switch from Drive to Athletics).",
  [('Resistance Lumber Mech','Body Track','80','70'),('Resistance Lumber Mech','Resource','2 Moderate Fuel','2 Moderate Charge'),('Resistance Lumber Mech','Tag type: [Kinetic Feedback Control Rig]','Standard','Free')])
# keep book order: section, then page (stable)
_order={'Combat':0,'Item Creation':1,'Gear':2,'Psionics':3}
e(G,226,None,'Standard Light Armor','stat',D7,"Standard Light Armor's Cost Rating is 0, not 2 (its CC is already 0).",
  [('Standard Light Armor','CR','2','0')])
e(G,226,None,'Psionic Light Armor','stat',D7,"Psionic Light Armor's Cost Rating is 0 and its Character Creation cost is 0 (was CR 1, CC 1). Its stats are unchanged.",
  [('Psionic Light Armor','CR','1','0'),('Psionic Light Armor','CC','1','0')])
e(G,226,None,'Stealth Suit','stat',D7,'The Stealth Suit is a Small item, not Medium; it can be worn under street clothing.',
  [('Stealth Suit','Size','Medium','Small')])
e(G,227,None,'Riot/LEO Armor','stat',D7,'Riot/LEO Armor is a Small item, not Medium, and its Armor Rating is 4 (Firefight), not 3.',
  [('Riot/LEO Armor','Size','Medium','Small'),('Riot/LEO Armor','Armor Rating','3 (Firefight)','4 (Firefight)')])
e(G,227,None,'Riot/LEO Armor, Psi Variant','stat',D7,'Riot/LEO Armor, Psi Variant is a Small item, not Medium. It has Life Support: Minor (the rebreather its limitation refers to), gains the Tag [Mental Block], and its Strain Threshold is 10, not 5.',
  [('Riot/LEO Armor, Psi Variant','Size','Medium','Small'),('Riot/LEO Armor, Psi Variant','Life Support','none','Minor (1 person)'),('Riot/LEO Armor, Psi Variant','Tag','none','[Mental Block]'),('Riot/LEO Armor, Psi Variant','Strain Threshold','5','10')])
e(G,229,None,'Flight Pack','stat',D7,'The Flight Pack gains Modifier: Pilot +2. [Turn Your Head to Steer] is a Free Tag and [A Leap of Faith] is rank 3. Its Usage Restriction is a Moderate limitation. Its Cost Rating is 0 and its Character Creation cost is 0 (was CR 1, CC 1).',
  [('Flight Pack','Modifier','none','Pilot +2'),('Flight Pack','Tag type: [Turn Your Head to Steer]','Standard','Free'),('Flight Pack','Tag rank: [A Leap of Faith]','1','3'),('Flight Pack','Limitation grade: Usage Restriction','Minor','Moderate'),('Flight Pack','CR','1','0'),('Flight Pack','CC','1','0')])
e(G,229,None,'Bolt-on Thruster Pack','stat',D7,'The Bolt-on Thruster Pack gains Modifier: Pilot +2 and Life Support: Minor (extending suit operations in space). Its fuel is 3 Moderate Fuel, not Minor.',
  [('Bolt-on Thruster Pack','Modifier','none','Pilot +2'),('Bolt-on Thruster Pack','Life Support','none','Minor (1 person)'),('Bolt-on Thruster Pack','Fuel','3 Minor','3 Moderate')])
e(IC,211,None,'Attack: Plasma Bleed','rule',D7,"A Plasma Attack's free Bleed (half its Weapon Multiplier, at the grade matching the Attack's scale) can be increased. Additional Bleed damage costs the difference between the full Bleed cost and the free Bleed.",
  [(None,'Plasma Bleed above the free amount','not addressed','Costs the difference between full Bleed cost and the free Bleed')])
e(IC,217,None,'Regeneration: Force Field','rule',D7,'Shohan Force Field Regeneration is always Major grade (regenerates every round).',
  [(None,'Force Field Regeneration grade','not specified','Major')])
e(G,232,None,'Plasma Carbine','stat',D7,"The Plasma Carbine's attack increases to 5x from 4x. Its Bleed is 4 (Minor): 2 free from the Plasma implementation plus 2 bought.",
  [('Plasma Carbine','Weapon Multiplier','4x','5x'),('Plasma Carbine','Bleed','Moderate 2','Minor 4 (2 free + 2 bought)')])
e(G,234,None,'Light Plasma Cannon','stat',D7,"The Light Plasma Cannon's attack increases to 5x from 4x. Its Bleed is 4 (Moderate): 2 free from the Plasma implementation plus 2 bought.",
  [('Light Plasma Cannon','Weapon Multiplier','4x','5x'),('Light Plasma Cannon','Bleed','Major 2','Moderate 4 (2 free + 2 bought)')])
e(G,268,None,'Tse Blade','stat',D7,"The Tse Blade's [Flexible Geometry Blade] is a Free Tag. [Where Did You Get Your Hands on One?] is a standard Tag (it applies when a character who is neither Shohan nor Altered carries one). Its Cost Rating is 4 and its Character Creation cost is 10 (was CR 5, CC 15).",
  [('Tse Blade','Tag type: [Flexible Geometry Blade]','Standard','Free'),('Tse Blade','Tag','[Where Did You Get Your Hands on One?] (conditional)','Standard Tag'),('Tse Blade','CR','5','4'),('Tse Blade','CC','15','10')])
e(G,268,None,'Shohan Personal Armor','stat',D7,"Shohan Personal Armor's Regeneration grades are Biological 4 at Moderate (4 Body per scene) and Force Field 4 at Major (every round). [Emergent Altered] is a Moderate limitation (Malfunction), and the armor has a second Moderate limitation, Target On Your Back.",
  [('Shohan Personal Armor','Regeneration: Biological','4 (grade not printed)','4, Moderate'),('Shohan Personal Armor','Regeneration: Force Field','4 (grade not printed)','4, Major'),('Shohan Personal Armor','Limitation','none','Malfunction [Emergent Altered], Moderate'),('Shohan Personal Armor','Limitation','none','Target On Your Back, Moderate')])
e(G,235,None,'Personal Psi Link','stat',D7,"The Personal Psi Link carries 2 Moderate Charge (20 days or 20 combat rounds), not 1. Its Cost Rating is 1 and its Character Creation cost is 1 (was CR 2, CC 3); the printed price matched its original Major Power Supply.",
  [('Personal Psi Link','Charge','1 Moderate','2 Moderate'),('Personal Psi Link','CR','2','1'),('Personal Psi Link','CC','3','1')])
e(G,240,None,'Family Transport','stat',D7,"The Family Transport's fuel is 2 Minor Fuel (20 days/combat rounds), not 5, and its Drive Task is 15, not 16.",
  [('Family Transport','Fuel','5 Minor','2 Minor'),('Family Transport','Task: Drive','16','15')])
e(G,241,None,'Speedster','stat',D7,'The Speedster gains Modifier: Drive +2 and the Free Tag [...And Turns A Few Heads 3].',
  [('Speedster','Modifier','none','Drive +2'),('Speedster','Tag','none','[...And Turns A Few Heads 3] (Free)')])
e(G,244,None,'Air Transport','stat',D7,"The Air Transport has Armor Rating 2 (Battlefield), not 1, and Maneuver 2, not 1. Its cargo is 3 Major, not 3 Moderate, and it gains Life Support: Moderate (12 passengers). Its computer is rank 3 (18 target, 5 tasks), not rank 2, and it gains Task: Intrusion Detection 17.",
  [('Air Transport','Armor Rating','1 (Battlefield)','2 (Battlefield)'),('Air Transport','Maneuver','1','2'),('Air Transport','Cargo','3 Moderate','3 Major'),('Air Transport','Life Support','none','Moderate (12 people)'),('Air Transport','Computer','Minor 2 (16 target)','Minor 3 (18 target)'),('Air Transport','Tasks','Pilot 16','Pilot 16, Intrusion Detection 17')])
e(G,262,None,'Arniston','stat',D7,"The Arniston's Manufacture is Major, not Moderate, and it gains a Major Weapon Link so the crew can fit a custom weapon besides the missiles. Its Detection is +2, not +1. It uses 4 of its 6 Major Power Slots, not 3; a weapon fitted to the Link draws another.",
  [('Arniston (Unique Armed Merchantman)','Manufacture','Moderate','Major'),('Arniston (Unique Armed Merchantman)','Link','none','Major Weapon'),('Arniston (Unique Armed Merchantman)','Modifier','Detection +1','Detection +2'),('Arniston (Unique Armed Merchantman)','Total Power Slots','6 Major (3 used)','6 Major (4 used)')])
e(G,263,None,'Lilith Carrier','stat',D7,"The Havenite Lilith Carrier's heavy particle cannons are 7x, not 6x. Its Armor Rating is 5 (Space, Shrouded Hull), not 3. Its cargo is 2 Major, not 1 Huge (Cargo has no Huge grade). It gains Manufacture: Major, and its Unique Fuel (Antimatter) limitation is Major. Total Power Slots: 6 Major, 5 used.",
  [('Havenite Lilith Carrier','Attack','Heavy particle cannon 6x (2 mounts)','Heavy particle cannon 7x (2 mounts)'),('Havenite Lilith Carrier','Armor Rating','3 (Space)','5 (Space)'),('Havenite Lilith Carrier','Cargo','1 Huge','2 Major'),('Havenite Lilith Carrier','Manufacture','none','Major'),('Havenite Lilith Carrier','Limitation','Unique Fuel (Antimatter)','Unique Fuel (Antimatter) (Major)'),('Havenite Lilith Carrier','Total Power Slots','none','6 Major (5 used)')])
e(G,261,None,'Marine LASCO Vessel','stat',D7,"The Marine LASCO Vessel carries 10 Major Fuel (100 days), not 13. It gains the Limitation Prerequisite: [Property of the Terran Sphere] (Moderate). Each of its 4 Major Hangars holds 3 Large craft (4 if crammed), so it launches 12 to 16 Bridgehead Assault Shuttles.",
  [('Marine LASCO (Launch, Support, and Command) Vessel','Fuel','13 Major','10 Major (100 days)'),('Marine LASCO (Launch, Support, and Command) Vessel','Limitation','none','Prerequisite [Property of the Terran Sphere] (Moderate)')])
e(IC,214,None,'Hangar: capacity','rule',D7,"Hangar: \"multiple items\" means 3 items, or 4 if crammed in. For example, a Major Hangar on a Huge ship holds 3 Large craft (4 crammed), and a Moderate Hangar holds 3 items two sizes smaller (4 crammed).",
  [(None,'Hangar capacity','multiple items','3 items (4 crammed)')])
e(G,263,None,'Havenite Marauder','stat',D7,"The Havenite Marauder has Armor Rating 4 (Space, Shrouded Hull), not 5. Its Reaction Drive is Moderate, not Major, and it has no Gravitic Drive; it relies on a carrier to travel between systems. It gains Power Supply: Major Antimatter, rank 1, which powers its Anti-Missile and launchers. Its Unique Fuel (Antimatter) limitation is Major. Remove its Intrusion Detection task. Total Power Slots: 3 Major and 3 Moderate, 3 Major used.",
  [('Havenite Marauder','Armor Rating','5 (Space)','4 (Space)'),('Havenite Marauder','Drive','Major Reaction, Major Gravitic','Moderate Reaction'),('Havenite Marauder','Power Supply','none','Major Antimatter, rank 1'),('Havenite Marauder','Limitation','Unique Fuel (Antimatter)','Unique Fuel (Antimatter) (Major)'),('Havenite Marauder','Tasks','Intrusion Detection 20','none'),('Havenite Marauder','Total Power Slots','none','3 Major, 3 Moderate (3 Major used)')])
e(G,251,None,'Factory Freighter','stat',D7,"The Factory Freighter's Reaction Drive is Moderate, not Major. It has 2 Major Hangars, not 3, and 5 Major Life Support (500 people), not 6. Its computer is Major rank 3 (18 target); delete \"5 tasks\", since a Major computer runs unlimited tasks. Its CR is 9 and CC 45, not CR 8 and CC 36. Total Power Slots: 3 Major and 3 Moderate, 3 Major used.",
  [('Factory Freighter','Drive','Major Reaction','Moderate Reaction'),('Factory Freighter','Hangar','3 Major','2 Major'),('Factory Freighter','Life Support','6 Major (600 people)','5 Major (500 people)'),('Factory Freighter','Computer','Major 3 (18 target, 5 tasks)','Major 3 (18 target)'),('Factory Freighter','CR','8','9'),('Factory Freighter','CC','36','45')])
e(G,249,None,'Shuttle/Yacht','stat',D7,"The Shuttle/Yacht gains Task: Pilot 17 and the Free Tag [The Grand Tour 3]. Its Tangle is 2 ranks (20 days), not 1.",
  [('Shuttle/Yacht','Tasks','none','Pilot 17'),('Shuttle/Yacht','Tag','none','[The Grand Tour 3] (Free)'),('Shuttle/Yacht','Tangle','1','2 (20 days)')])
e(G,250,None,'Locust Mobile Industrial Platform','stat',D7,"The Locust Mobile Industrial Platform has Armor Rating 2 (Space), not 1, and a Body Track of 250, not 200. It has Maneuver 1.",
  [('Locust Mobile Industrial Platform','Armor Rating','1 (Space)','2 (Space)'),('Locust Mobile Industrial Platform','Body Track','200','250'),('Locust Mobile Industrial Platform','Maneuver','none','1')])
e(G,264,None,'Havenite Lamprey','stat',D7,"The Havenite Lamprey's drive is a Major Gravitic Drive modified for in-system use (like the Phantom's), not a Reactionless drive. It gains the Limitations Usage Restriction: in-system only, not FTL-capable (Minor), and One-Time Use (Major); the boarding craft must be reserviced after each action.",
  [('Havenite Lamprey','Drive','Reactionless','Major Gravitic (modified, in-system)'),('Havenite Lamprey','Limitation','none','Usage Restriction: in-system only (Minor)'),('Havenite Lamprey','Limitation','none','One-Time Use (Major)')])
D8='2026-09-28'
A='Arniston (Unique Armed Merchantman)'
e(G,262,None,'Arniston: fuel endurance','typo',D8,'The Arniston\'s fuel reads "6 Major Fuel (60 days/combat rounds)", not 6 days.',[(A,'Fuel','6 Major Fuel (6 days/combat rounds)','6 Major Fuel (60 days/combat rounds)')])
e(G,264,None,'Havenite Lamprey: fuel endurance','typo',D8,'The Havenite Lamprey\'s fuel reads "4 Major Fuel (40 days/combat rounds)", not 4 days.',[('Havenite Lamprey','Fuel','4 Major Fuel (4 days/combat rounds)','4 Major Fuel (40 days/combat rounds)')])
e(G,263,None,'Havenite Marauder: magazine','typo',D8,'The Havenite Marauder\'s magazine reads "6 Major Magazine (60 shots)", not 640 shots.',[('Havenite Marauder','Magazine','Major Magazine (640 shots)','6 Major Magazine (60 shots)')])
e(G,265,None,'Quad Missile Pack: magazine','typo',D8,'The Quad Missile Pack\'s magazine reads "8 Major Magazines (80 shots)", not 2 Major Magazines.',[('Quad Missile Pack','Magazine','2 Major Magazines (80 shots)','8 Major Magazines (80 shots)')])
e(G,245,None,'Armored Personnel Carrier: power','stat',D8,'The Armored Personnel Carrier\'s Power Supply is Moderate Fusion rank 2, not rank 1, so its 2 Weapon Links have power for linked weapons. Its Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).',[('Armored Personnel Carrier','Power Supply','Moderate Fusion 1','Moderate Fusion 2'),('Armored Personnel Carrier','Total Power Slots','3 Minor (2 used), 3 Moderate (0 used)','3 Minor (0 used), 6 Moderate (2 used)')])
e(G,252,None,'Security Escort/Corsair: power slots','typo',D8,'The Security Escort/Corsair\'s Total Power Slots read 6 Major (2 used), 3 Moderate (0 used), not 9 Major (4 used). Weapons fitted to its Weapon Links draw further slots.',[('Security Escort/Corsair','Total Power Slots','9 Major (4 used)','6 Major (2 used), 3 Moderate (0 used)')])
e(G,259,None,'Redemption-class Frigate: launchers and power','stat',D8,'The Redemption-class Frigate carries 4 Launchers (Space), not 6; the ship is built around its plasma cannons. Its Total Power Slots read 9 Major (7 used), 3 Moderate (0 used), not 9 Major (7 used) with no Moderate listed.',[('Redemption-class Frigate','Launchers','6 (Space)','4 (Space)'),('Redemption-class Frigate','Total Power Slots','9 Major (7 used)','9 Major (7 used), 3 Moderate (0 used)')])
e(G,260,None,'Retribution-class Frigate: Anti-Missile','typo',D8,'The Retribution-class Frigate\'s "Anti-Missile (Space) 2x" reads "Anti-Missile (Space) 1x"; it has one Anti-Missile mount. Its Total Power Slots read 9 Major (6 used), not 7 used.',[('Retribution-class Frigate','Anti-Missile','Anti-Missile (Space) 2x','Anti-Missile (Space) 1x'),('Retribution-class Frigate','Total Power Slots','9 Major (7 used)','9 Major (6 used)')])
e(G,250,None,'Locust: power slots','typo',D8,'The Locust Mobile Industrial Platform\'s Total Power Slots read 6 Major (3 used); the grade was missing.',[('Locust Mobile Industrial Platform','Total Power Slots','6 (3 used)','6 Major (3 used)')])
e(G,271,None,'Resistance Lumber Mech: power slots','typo',D8,'The Resistance Lumber Mech\'s Total Power Slots read 3 Minor (0 used), 3 Moderate (1 used), not 2 Minor.',[('Resistance Lumber Mech','Total Power Slots','2 Minor (0 used), 3 Moderate (1 used)','3 Minor (0 used), 3 Moderate (1 used)')])
e(G,225,None,'Quick Reference table','typo',D8,'Update the Quick Reference table to match the errata: Standard Light Armor CR 0, CC 0; Psionic Light Armor CR 0, CC 0; Flight Pack CR 0, CC 0; Personal Psi Link CR 1, CC 1; Stealth FTL Recon Drone CR 6, CC 21; Factory Freighter CR 9, CC 45; Tse Blade CR 4, CC 10. Replace the Programs "Min" column (minimum computer rank) with the required computer grade: Minor for all eight programs.',
  [('Standard Light Armor','Quick Reference CR/CC','2 / 0','0 / 0'),('Psionic Light Armor','Quick Reference CR/CC','1 / 1','0 / 0'),('Flight Pack','Quick Reference CR/CC','1 / 1','0 / 0'),('Personal Psi Link','Quick Reference CR/CC','2 / 3','1 / 1'),('Stealth FTL Recon Drone','Quick Reference CR/CC','5 / 15','6 / 21'),('Factory Freighter','Quick Reference CR/CC','8 / 36','9 / 45'),('Tse Blade','Quick Reference CR/CC','5 / 15','4 / 10'),(None,'Quick Reference: Programs column','Min (computer rank)','Computer grade (Minor)')])
e(G,245,None,'Attack Hovercraft: power','stat',D8,'The Attack Hovercraft\'s Power Supply is Moderate Fusion rank 2, not rank 1, so its 3 Weapon Links have power for linked weapons. Its Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).',[('Attack Hovercraft','Power Supply','Moderate Fusion 1','Moderate Fusion 2'),('Attack Hovercraft','Total Power Slots','3 Minor (0 used), 3 Moderate (3 used)','3 Minor (0 used), 6 Moderate (2 used)')])
e(G,256,None,'Standard Cruiser: power','stat',D8,'The Standard Cruiser gains Power Supply: Major Fusion, rank 1, to power its integrated railgun turrets. Its Total Power Slots read 6 Major (4 used), 3 Moderate (0 used), not 3 Major (2 used).',[('Standard Cruiser','Power Supply','none','Major Fusion 1'),('Standard Cruiser','Total Power Slots','3 Major (2 used), 3 Moderate (0 used)','6 Major (4 used), 3 Moderate (0 used)')])
e(G,264,None,'Heavy Railgun: power','stat',D8,'The Heavy Railgun gains Power Requirement: 1 Major slot, drawn from its host through the Weapon Link (like the Heavy Laser Cannon).',[('Heavy Railgun','Power Requirement','none','1 Major slot')])
e(IC,210,None,'Attack: rail weapon power','rule',D8,'Rail (Kinetic Ranged) weapons integrated into an item (ship and vehicle weapons, and units slaved to a host such as suit-mounted or Weapon Link weapons) draw a Power Slot like any other Attack, in addition to their Ammunition. Standalone rail weapons (hand weapons such as gauss pistols and rifles) need no Power Supply: the power is built into the casing of each round, and this is already included in their Ammunition.',[(None,'Rail weapon power','unclear','integrated/slaved: Power Slot + Ammunition; standalone: self-powered rounds')])
def body90(item,page): return e(G,page,None,item+': Body Track','stat',D8,f"The {item}'s Body Track is 90, not 80 (80 isn't a whole Large increment; 90 costs the same).",[(item,'Body Track','80','90')])
body90('Armored Cargo Transport',243); body90('Air Transport',244); body90('Assault Platform',244); body90('Attack Hovercraft',245); body90('Armored Personnel Carrier',245)
e(G,243,None,'Armored Cargo Transport: computer','stat',D8,"The Armored Cargo Transport's computer is Minor rank 4 (20 target, 5 tasks), not rank 3, so it can run its Intrusion Detection 20 Task.",[('Armored Cargo Transport','Computer','Minor 3 (18 target)','Minor 4 (20 target)')])
e(G,246,None,'Recon Drone','stat',D8,"The Recon Drone's Maneuver is 4, not 5 (the maximum is 4). Its computer is Minor rank 3 (18 target, 5 tasks), not rank 2, so it can run its Piloting 18 Task.",[('Recon Drone','Maneuver','5','4'),('Recon Drone','Computer','Minor 2 (16 target)','Minor 3 (18 target)')])
e(G,269,None,'War Drone (Cerberus): computer','stat',D8,"The War Drone (Cerberus)'s Brain is Moderate rank 4 (20 target), not rank 3, so it can run its Combat 20 Task.",[('War Drone (Cerberus)','Computer','Moderate Brain 3 (18 target)','Moderate Brain 4 (20 target)')])
e(G,255,None,'Bridgehead Assault Shuttle: Bleed','stat',D8,"The Bridgehead Assault Shuttle's rapid plasma cannon has Bleed: Major 2 (its free Plasma Bleed, half of 5x rounded down), not Major 3. Its Total Power Slots read 3 Moderate (1 used), 3 Major (3 used).",[('Bridgehead Assault Shuttle','Bleed','Major 3','Major 2'),('Bridgehead Assault Shuttle','Total Power Slots','3 Moderate (3 used), 3 Major (3 used)','3 Moderate (1 used), 3 Major (3 used)')])
e(G,239,None,'Creatures: Drive','stat',D8,'"Fluffy" and the Monster in the Dark gain Drive: Minor Land (legs), which carries their Maneuver 1.',[('“Fluffy”','Drive','none','Minor Land (legs)'),('Monster in the Dark','Drive','none','Minor Land (legs)')])
e(G,238,None,'Psi Amp','stat',D8,'The Psi Amp is rebuilt. Its initial hit is +5 Psionic Strain (Counter: Strain, 1 rank), followed by Regeneration: Strain 5 (Major, every round) for its Duration of 10 combat rounds (1 Minor Resource rank). [Euphoria] is a Minor limitation. This supersedes the earlier +10 Strain erratum. CR 1, CC 1 (unchanged).',
  [('Psi Amp','Psionic Strain','+10','+5 initial (Counter: Strain, 1 rank)'),('Psi Amp','Regeneration','none','Strain 5, Major (every round)'),('Psi Amp','Duration','10 combat rounds or 1 hour','1 Minor Resource rank (10 combat rounds)'),('Psi Amp','Limitation','[Euphoria] (Drawback Tag)','[Euphoria] (Minor)')])
e(G,238,None,'Psi Damp','stat',D8,'The Psi Damp is costed as Counter: Strain, 5 ranks (−25 Psionic Strain), with a Duration of 1 day (1 Moderate Resource rank). [It Itches In My Brain] becomes [It Itches In My Brain 3], a Moderate limitation. CR 1, CC 1 (unchanged).',
  [('Psi Damp','Psionic Strain','−25','−25 (Counter: Strain, 5 ranks)'),('Psi Damp','Duration','1 day','1 Moderate Resource rank (1 day)'),('Psi Damp','Limitation','[It Itches in My Brain] (Drawback Tag)','[It Itches In My Brain 3] (Moderate)')])
e(IC,212,215,'Drugs: Strain and Duration','rule',D8,'Counter: Strain raises or lowers Psionic Strain by 5 per Counter (20 BP each). Regeneration: Strain restores Psionic Strain like other Regeneration implementations. A drug\'s Duration is bought as a Resource (1 Minor rank ≈ 10 combat rounds or 1 hour; 1 Moderate rank ≈ 1 day).',
  [(None,'Counter implementations','Armor, Shields, Disabling, Strike','adds Strain (±5 Psionic Strain per Counter)'),(None,'Regeneration implementations','Biological, Force Field, Mechanical','adds Strain'),(None,'Drug Duration','undefined','Resource')])
e(G,232,None,'Plasma Carbine: Upkeep','typo',D8,'Delete "Upkeep: 1" from the Plasma Carbine. Upkeep, a recurring maintenance cost, was phased out of the rules; this listing is a leftover.',[('Plasma Carbine','Upkeep','1','none')])
e(G,240,None,'Colonial Personal Transport (Hoverbike)','stat',D8,'The Colonial Personal Transport (Hoverbike) has Armor Rating 2 (Firefight), not 1. Replace "Cover: Moderate (Partial)" with Limitation: Partial Armor (Moderate); an aimed shot bypasses its armor.',
  [('Colonial Personal Transport (Hoverbike)','Armor Rating','1 (Firefight)','2 (Firefight)'),('Colonial Personal Transport (Hoverbike)','Cover','Moderate (Partial)','none'),('Colonial Personal Transport (Hoverbike)','Limitation','none','Partial Armor (Moderate)')])
e(G,254,None,'Dragon-class Fleet Interceptor/Escort','stat',D8,"The Dragon-class Fleet Interceptor/Escort's Air Drive is Minor, not Moderate; its drives are a Moderate in-system Reaction Drive and a Minor Air Drive. It carries 8 Launchers (Space), not 6.",
  [('Dragon-class Fleet Interceptor/Escort','Drive','Moderate Air','Minor Air'),('Dragon-class Fleet Interceptor/Escort','Launchers','6 (Space)','8 (Space)')])
e(IC,215,None,'Link: Refueling','rule',D8,'Add a Link type, Refueling: a docking connection that transfers fuel to a linked craft of up to the Link\'s maximum size. Each Refueling Link draws 1 Power Slot of its grade while in use. (The Fleet Auxiliary\'s three Major Refueling Links account for 3 of its 4 used Power Slots.)',
  [(None,'Link types','Data, Psi, Weapon','adds Refueling (draws 1 Power Slot)')])
e(IC,217,218,'Limitations: examples','clarification',D8,'Key Personnel (the item needs a specific crew member, such as a Navigator) is a Moderate limitation. A Modifier covering several skills is costed per skill (10 BP × rank × number of skills). A Minor Reaction Drive is a jet pack that works on a planet or in microgravity.',
  [(None,'Key Personnel','unlisted','Moderate limitation'),(None,'Multi-skill Modifier cost','unclear','per skill'),(None,'Minor Reaction Drive','unlisted','jet pack (planet or microgravity)')])
e(G,268,None,'Shohan Personal Armor','stat',D8,"The Shohan Personal Armor's 2 Weapon Links are Moderate. Its Weapons +2 Modifier works only with weapons fitted to those Links (Limitation: Usage Restriction, Minor). Its Computer is Minor rank 3 (18 target), not Moderate, its Athletics Modifier is +1, not +2, and its Body Track is 45, not 40. Total Power Slots: 3 Moderate, 3 used (Force Field and one weapon on each Link).",
  [('Shohan Personal Armor','Links','2 Weapon','2 Moderate Weapon'),('Shohan Personal Armor','Limitation','none','Usage Restriction: Weapons +2 only with Link weapons (Minor)'),('Shohan Personal Armor','Computer','Moderate 3','Minor 3'),('Shohan Personal Armor','Modifier','Athletics +2','Athletics +1'),('Shohan Personal Armor','Body Track','40','45')])
e(G,252,None,'Standard Assault Shuttle: launchers','stat',D8,'The Standard Assault Shuttle carries 4 Launchers (Space), not 2.',[('Standard Assault Shuttle','Launchers','2 (Space)','4 (Space)')])
e(G,258,None,'Conventional Frigate: launchers','stat',D8,'The Conventional Frigate carries 8 Launchers (Space), not 6.',[('Conventional Frigate','Launchers','6 (Space)','8 (Space)')])
e(G,263,None,'Havenite Marauder: launchers','stat',D8,'The Havenite Marauder carries 8 Launchers (Space), not 6, to fit its heavy missile loadout.',[('Havenite Marauder','Launchers','6 (Space)','8 (Space)')])
e(IC,214,None,'Launcher: sets of 4','rule',D8,'Launchers are bought in sets of 4 (one set draws 1 Power Slot and costs 4 × the per-launcher price: 20 / 40 / 60 BP). Ships printing launcher counts that are not multiples of 4 are corrected by errata (Standard Assault Shuttle, Dragon, Conventional Frigate, Redemption, Havenite Marauder). A Magazine does not have to match the launcher count.',[(None,'Launcher purchase','per launcher','sets of 4')])
e(G,256,None,'Standard Cruiser: computer','stat',D8,'The Standard Cruiser gains Computer: Major 3 (18 target, unlimited tasks), matching the Redemption and Retribution.',[('Standard Cruiser','Computer','none','Major 3 (18 target)')])
e(G,252,None,'Standard Assault Shuttle: radio','stat',D8,'The Standard Assault Shuttle gains Communications: Moderate (Radio).',[('Standard Assault Shuttle','Communications','none','Moderate (Radio)')])
e(G,254,None,'Dragon-class Fleet Interceptor/Escort: fuel','stat',D8,'The Dragon-class Fleet Interceptor/Escort carries 2 Major Fuel (20 days/combat rounds), not 2 Moderate, so it can run its Major Fusion reactor as well as its drives.',[('Dragon-class Fleet Interceptor/Escort','Fuel','2 Moderate','2 Major')])
e(G,248,None,'Telekinetic Shuttle: Charge','typo',D8,'The Telekinetic Shuttle\'s Coil Power Supply runs on 2 Major Charge, not 2 Major Fuel.',[('Telekinetic Shuttle','Resource','2 Major Fuel','2 Major Charge')])
e(G,242,None,'Light Performance Aircraft: life support','stat',D8,'The Light Performance Aircraft has Life Support: 3 Minor (3 people), not 1 Moderate (12 people); it is a 2–3 seat craft.',[('Light Performance Aircraft','Life Support','Moderate (12 people)','3 Minor (3 people)')])
e(G,253,None,'Tanker/Command Ship: own fuel','stat',D8,'The Tanker/Command Ship\'s own Fuel Resource is 10 Major (100 days/combat rounds), separate from the bulk fuel it carries as Cargo.',[('Tanker/Command Ship','Fuel','not printed','10 Major (100 days)')])
e(G,261,None,'Fleet Auxiliary: own fuel','stat',D8,'The Fleet Auxiliary\'s own Fuel Resource is 11 Major (110 days/combat rounds), separate from the bulk fuel it carries as Cargo.',[('Fleet Auxiliary','Fuel','not printed','11 Major (110 days)')])
e(G,260,None,'Retribution-class Frigate: drive','stat',D8,'The Retribution-class Frigate\'s Reaction Drive is Moderate, not Major, like its sister ship the Redemption. Its Total Power Slots read 6 Major (6 used), 3 Moderate (0 used).',[('Retribution-class Frigate','Drive','Major Reaction','Moderate Reaction'),('Retribution-class Frigate','Total Power Slots','9 Major (6 used)','6 Major (6 used), 3 Moderate (0 used)')])
e(G,253,None,'System Defense Craft: alternate forms','clarification',D8,'In the System Defense Craft\'s alternate forms, "missile array" means its 4 Launchers and "particle cannon" means its heavy railgun (the name from an earlier draft). The Strike Craft removes the 4 Launchers; the Torpedo Boat removes the heavy railgun.',[('System Defense Craft (Pocket Cruiser)','Alternate forms: missile array','missile array','4 Launchers'),('System Defense Craft (Pocket Cruiser)','Alternate forms: particle cannon','particle cannon','heavy railgun')])
e(G,235,None,'Coil Stack Battery/Charger','stat',D8,'The Coil Stack Battery/Charger is Small, not Tiny (a Moderate Power Supply needs a Small item), and holds 2 Moderate Charge, not 1. CR 0, CC 0 (unchanged).',[('Coil Stack Battery/Recharger','Size','Tiny','Small'),('Coil Stack Battery/Recharger','Charge','1 Moderate','2 Moderate')])
e(G,237,None,'Advanced Neural Interface Control Link','stat',D8,'The Advanced NICL\'s Initiative Modifier is +2, not +3; its Major Neural Interface already gives +3 Initiative when operating linked equipment, and the Modifier is the general bonus. [Dance Along the Bleeding Edge, But You Might Get Cut] splits in two: the Tag [Dance Along The Bleeding Edge 2] and the Major limitation [...But You Might Get Cut 2] (hacking that breaches the user\'s defenses can inflict physical damage). CR 1, CC 4 (unchanged).',
  [('Advanced Neural Interface Control Link','Modifier','Initiative +3','Initiative +2'),('Advanced Neural Interface Control Link','Tag','none','[Dance Along The Bleeding Edge 2]'),('Advanced Neural Interface Control Link','Limitation','[Dance Along the Bleeding Edge, But You Might Get Cut] (Major)','[...But You Might Get Cut 2] (Major)')])
e(IC,210,None,'Attack: Hyperspace implementation','clarification',D8,'The Hyperspace implementation (the Shohan Dreadnought\'s hyper cannon, the only such attack in the game) includes Counter: Armor and Area: Small Sudden at no extra cost. Both are printed in the cannon\'s stat block so its effects can be read without looking up the implementation.',[(None,'Hyperspace free features','Counter: Armor','Counter: Armor, Area: Small Sudden')])
D9='2026-09-29'
e(G,268,None,'Shohan Personal Armor','stat',D9,"The Shohan Personal Armor's Weapons +2 Modifier covers two skills, Melee and Heavy Weapons (pairing with a Tse Blade), and is costed as a Moderate Modifier. Target On Your Back is a Major limitation, not Moderate: the armor can't be concealed, and anyone wearing it is visibly in the other side's armor. Cost Rating unchanged (5).",
  [('Shohan Personal Armor','Modifier','Weapons +2','Weapons (Melee, Heavy Weapons) +2'),('Shohan Personal Armor','Limitation: Target On Your Back','Moderate','Major')])
e(IC,217,218,'Modifier: skill breadth','rule',D9,'The grade of a Modifier is how many skills it covers: Minor for one skill (10 BP per rank), Moderate for two (20 BP per rank), and Major for three or more, or a whole class of skills such as "Weapons" or "Technical Skills" (30 BP per rank). This replaces costing multi-skill Modifiers per skill. The +4 limit per skill still applies; how a class Modifier stacks with others is left to the table.',
  [(None,'Multi-skill Modifier cost','per skill','by breadth: Minor 1 skill (10/rank), Moderate 2 (20/rank), Major 3+ or a class (30/rank)')])
e(G,237,None,'Basic Neural Interface Control Link','stat',D9,"The Basic Neural Interface Control Link's Technical-class Skills +1 is a Major Modifier, since it covers a class of skills. Its Usage Restriction (skill modifiers only apply to linked gear) is Moderate, not Minor. Its Cost Rating is 1 (was 0).",
  [('Basic Neural Interface Control Link (NICL)','Modifier grade: Technical-class Skills','Minor','Major'),('Basic Neural Interface Control Link (NICL)','Limitation grade: Usage Restriction','Minor','Moderate'),('Basic Neural Interface Control Link (NICL)','CR','0','1')])
e(G,237,None,'Advanced Neural Interface Control Link','stat',D9,"The Advanced Neural Interface Control Link's Technical-class Skills +1 is a Major Modifier, since it covers a class of skills. Its Usage Restriction (skill modifiers only apply to linked gear) is Moderate, not Minor. Its Cost Rating is 2 (was 1).",
  [('Advanced Neural Interface Control Link','Modifier grade: Technical-class Skills','Minor','Major'),('Advanced Neural Interface Control Link','Limitation grade: Usage Restriction','Minor','Moderate'),('Advanced Neural Interface Control Link','CR','1','2')])
e(IC,211,None,'Attack: self-powered Plasma','rule',D9,'Plasma has a self-powered implementation for hand weapons. Instead of drawing 2 Power Slots per mount, it needs special ammunition (an Ammunition Resource). That requirement is built into the implementation as a Moderate limitation: it takes one of the two Moderate limitation slots but refunds no Build Points. Plasma weapons built into or slaved to a host still draw 2 Power Slots per mount, with or without ammunition. Kinetic (rail) weapons split the same way (p210): Kinetic draws a Power Slot plus Ammunition, Kinetic (self-powered) uses Ammunition only.',
  [(None,'Plasma implementations','Plasma','Plasma (2 Power Slots per mount); Plasma (self-powered) (special ammunition, built-in Moderate limitation)'),(None,'Kinetic implementations','Kinetic','Kinetic (Power Slot + Ammunition); Kinetic (self-powered) (Ammunition only)')])
e(G,232,None,'Plasma Carbine: self-powered','stat',D9,"The Plasma Carbine's attack is self-powered Plasma. Its special ammunition requirement is built into that implementation, replacing the separate Prerequisite (special ammunition) limitation, and its Bleed is 3 (Minor): 2 free from Plasma plus 1 bought. Cost Rating unchanged (2).",
  [('Plasma Carbine','Attack implementation','Plasma','Plasma (self-powered)'),('Plasma Carbine','Limitation','Moderate: Prerequisite (special ammunition)','none (built into Plasma (self-powered))'),('Plasma Carbine','Bleed','Minor 4 (2 free + 2 bought)','Minor 3 (2 free + 1 bought)')])
D10='2026-09-30'
e(IC,213,None,'Drive: Fuel exemptions','rule',D10,'A Drive needs no Fuel Resource when it can run from its item\'s own Power Supply and that supply burns no Fuel: a Coil (battery), Environmental, or Hyperspace Tap supply. A creature\'s legs, wings, or fins are a Biological Drive, which needs no Fuel either. Light Sail and Jump drives are unchanged.',
  [(None,'Drive Fuel','always needed (except Light Sail, Jump)','not needed when a Coil, Environmental, or Hyperspace Tap Power Supply runs it, or for a Biological Drive')])
e(IC,210,None,'Attack: One-Time Use feed','rule',D10,'An Attack on a One-Time Use item, such as a grenade, needs no feed (no Power Slot and no Ammunition): the item is its own charge.',
  [(None,'One-Time Use Attack feed','Power Slot or Ammunition','none')])
e(IC,216,None,'Power: host-powered items','clarification',D10,'An item with no Power Supply or Drive of its own, such as a weapon module or a G3P, draws the Power Slots it uses from the host it is mounted on or plugged into. Its stat block lists them as its power requirement. A Slave limitation still means it needs a Link of the right type to work, not just a power connection.',
  [(None,'Items without their own power','Not enough Power Slots','draw their slots from the host')])
E.sort(key=lambda x:(_order[x['section']],x['p1']))
