from costs import *
I=[]
def item(name,cat,page,size,cr,cc,rows,errata=(),flags=(),notes=(),extra=None,power=None,compute=True):
    I.append(dict(name=name,cat=cat,page=page,size=size,cr=cr,cc=cc,rows=rows,errata=list(errata),flags=list(flags),notes=list(notes),extra=extra or {},power=power,compute=compute))
UR='Usage Restriction'
# ---------- Armor
item("Standard Light Armor","Armor",226,"Small",0,0,[armor('Firefight',2),body('Small',10)],
 errata=["(new, 2026-09-27) p226: CR 0, not 2 (a typo; its printed CC is already 0)."],
 flags=["Printed CR shown here is the errata value (CR 0). The book printed CR 2."])
item("Psionic Light Armor","Armor",226,"Small",0,0,[armor('Firefight',2),body('Small',10),ps('Minor','Coil'),res('Minor','Charge',1),link('Minor','Psi')],
 errata=["p226: Charge lasts 10 days / combat turns (was 1 day). One rank of Charge = 10 days, so this is 1 rank.","(new, 2026-09-27) p226: CR 0, CC 0 (was CR 1, CC 1). Stats unchanged."],
 flags=["Printed CR/CC shown here are the errata values. The book printed CR 1, CC 1."],
 power="3 Minor slots from Coil; 1 used (Psi Link). OK.", notes=["Strain Threshold 5 (Minor Power Supply rank 1)."])
item("Camouflage Suit","Armor",226,"Small",1,1,[armor('Firefight',4),body('Small',10),mod('Stealth',3),lim('Moderate','Partial Armor'),lim('Minor',UR+' (specific environment)')],
 errata=["(new, 2026-09-26) p226: Armor Rating 4 (was 3)."])
item("Stealth Suit","Armor",226,"Small",2,3,[armor('Firefight',3),body('Small',15),radio('Minor'),computer('Minor',1),mod('Athletics',1),mod('Stealth',3),tag("Now You See Me, Now You Don't",3),lim('Moderate','Partial Armor')],
 errata=["(new, 2026-09-27) p226: Size is Small, not Medium (per the build notes); it can be worn under street clothing."])
item("Riot/LEO Armor","Armor",227,"Small",2,3,[armor('Firefight',4),body('Small',20),radio('Minor'),computer('Minor',1),ls('Minor'),mod('Detection',1),lim('Minor',UR+' (life support only provides rebreather)')],
 errata=["(new, 2026-09-27) p227: Size is Small, not Medium (per the build notes). Armor Rating 4 (Firefight), not 3."])
item("Riot/LEO Armor, Psi Variant","Armor",227,"Small",2,3,[armor('Firefight',3),body('Small',20),ps('Moderate','Coil'),res('Moderate','Charge',1),link('Minor','Psi'),radio('Minor'),computer('Minor',1),ls('Minor'),mod('Detection',1),tag('Mental Block'),lim('Minor',UR+' (life support only provides rebreather)')],
 errata=["(new, 2026-09-27) p227: Size is Small, not Medium (per the build notes). Restores Minor Life Support (the rebreather its limitation refers to) and adds Tag [Mental Block]. Strain Threshold is 10, not 5.","p227: Charge lasts 10 days / combat turns (1 rank)."],
 flags=[],
 notes=["Strain Threshold 10 (Moderate Power Supply, rank 1)."],power="3 Moderate slots; 1 used.")
item("Standard Powered Armor","Armor",227,"Medium",3,6,[armor('Battlefield',4),body('Medium',25),ps('Moderate','Coil'),res('Moderate','Charge',1),link('Minor','Weapon'),link('Moderate','Psi'),radio('Minor'),computer('Minor',1),ls('Minor'),mod('Athletics',1),mod('Detection',1),mod('Firearms/Heavy Weapons',1,2)],
 errata=["p227: Armor is Battlefield, not Firefight."],power="3 Moderate slots; 2 used.")
item("Kavacha-class A-350 Marine Engagement Suit","Armor",228,"Medium",4,10,[armor('Battlefield',4),body('Medium',35),ff('Minor',3),ps('Moderate','Coil'),res('Moderate','Charge',1),link('Minor','Weapon',2),link('Moderate','Psi'),mod('Firearms/Heavy Weapons',2,2),radio('Minor'),computer('Minor',2),ls('Minor'),mod('Athletics',2),mod('Detection',2),tag('Shohan Killer'),tag('High Security',3),tag('Coordinated Fire'),lim('Major','Restricted Technology (Property of the Terran Sphere Marines)')],
 errata=["p228: Armor is Battlefield, not Firefight."],power="3 Moderate slots; 2 used (Force Field 1, Psi Link 1).",
 notes=["Terran Force Field (reverse-engineered): Minor is allowed."])
item("Kavacha-class A-350SR Marine Reconnaissance Suit","Armor",228,"Medium",4,10,[armor('Battlefield',3),body('Medium',30),ff('Minor',3),ps('Moderate','Coil'),res('Moderate','Charge',1),link('Minor','Weapon'),mod('Firearms/Heavy Weapons',1,2),link('Moderate','Psi'),radio('Minor'),computer('Minor',2),mod('Athletics',2),mod('Detection',2),mod('Stealth',2),tag("Now You See Me, Now You Don't",3),tag('High Security',3),tag('Shohan Killer'),lim('Major','Restricted Technology (Property of the Terran Sphere Marines)')],
 errata=["(new, 2026-09-26) p228: Armor is Battlefield, not Firefight (the Kavacha errata covers both suits)."],
 flags=[],
 power="3 Moderate slots; 2 used.")
item("Flight Pack","Armor",229,"Small",0,0,[drive('Minor','Reaction'),res('Minor','Fuel',3),mod('Pilot',2),tag('Turn Your Head to Steer',1,True),tag('A Leap of Faith',3),lim('Moderate','Slave (powered armor Weapon Link)'),lim('Moderate',UR+' (Short range movement at Space scale, Far range at Battlefield scale)')],
 errata=["(new, 2026-09-27) p229: Adds Modifier: Pilot +2. [Turn Your Head to Steer] is a Free Tag; [A Leap of Faith] is rank 3. Its Usage Restriction is a Moderate limitation. CR 0, CC 0 (was CR 1, CC 1)."],
 notes=["[Turn Your Head to Steer] grants a free skill switch from Piloting to Athletics.","Range reference (PJ): Firefight Far range = Battlefield Short; Battlefield Far = Space Short.","Its Minor Reaction Drive is a jet pack: it works on a planet and in microgravity."],
 flags=["Printed CR/CC shown here are the errata values. The book printed CR 1, CC 1."])
item("Bolt-on Thruster Pack","Armor",229,"Small",1,1,[drive('Moderate','Reaction'),maneuver('Moderate',2),res('Moderate','Fuel',3),mod('Pilot',2),ls('Minor'),lim('Moderate','Slave (powered armor Weapon Link)'),tag('Leap of Faith')],
 errata=["(new, 2026-09-27) p229: Adds Modifier: Pilot +2 and Life Support: Minor (extends suit operations in space). Fuel is 3 Moderate, not Minor (Minor fuel cannot feed its Moderate drive)."])
# ---------- Melee
item("Knife","Weapons: Melee",229,"Small",-2,0,[attack('Firefight',2,['Melee']),lim('Minor',UR+' (Firefight targets only; useless against Battlefield or hull armor)')],
 errata=["(new, 2026-09-27) p229: Adds Limitation: Usage Restriction (Firefight targets only; useless against Battlefield or hull armor), Minor."])
item("Concealable Knife","Weapons: Melee",229,"Small",0,0,[attack('Firefight',2,['Melee']),mod('Concealable',2),tag('Disappearing Act',2)])
# ---------- Firearms
FR=lim('Minor',UR+' (ineffective at Far Range)')
item("Standard Gauss Pistol","Weapons: Firearms",230,"Small",-1,0,[attack('Firefight',2,['Kinetic']),res('Minor','Ammunition',2),FR])
item("Quality Gauss Pistol","Weapons: Firearms",230,"Small",0,0,[attack('Firefight',3,['Kinetic']),res('Minor','Ammunition',3),mod('Firearms',1),FR],
 errata=["(new, 2026-09-26) p230: Attack increases to 3x (was 2x); the build notes used 3x."])
item("Heavy Gauss Pistol","Weapons: Firearms",230,"Small",0,0,[attack('Firefight',3,['Kinetic'],label='Attack (mode 1: single target)'),attack('Firefight',2,['Kinetic'],label='Attack (mode 2: burst)'),area(),lim('Minor','Hungry (10 shots/round, burst mode)'),res('Minor','Ammunition',5),mod('Firearms',2),FR],
 errata=["(new, 2026-09-26) p230: Single-target mode increases to 3x (was 2x). Burst mode stays 2x."],
 notes=["\"Attacks (1/attack)\": one weapon with selectable modes. Each mode is costed as its own Attack (see Conventions)."])
item("Concealable Pistol","Weapons: Firearms",230,"Small",1,1,[attack('Firefight',3,['Kinetic']),res('Minor','Ammunition',4),counter('Detection (−2 to opponents’ Discern/Detection checks to spot it)'),mod('Firearms',2),tag('Silent, But Deadly',2),FR],
 errata=["(new, 2026-09-26) p230: Attack increases to 3x (was 2x), adds Modifier: Firearms +2 (per the build notes), and Ammunition increases to 4 ranks / 40 shots (was 3 / 30). 79 BP, CR 1."],
 flags=[])
item("Wellpoint Armory Stormguard 9MP","Weapons: Firearms",231,"Small",2,3,[attack('Firefight',3,['Kinetic'],label='Attack (mode 1)'),counter('Armor (mode 1)'),attack('Firefight',3,['Kinetic'],label='Attack (mode 2: scatter)'),area(),lim('Minor','Hungry (10 shots/round, scatter)'),attack('Firefight',3,['Kinetic'],label='Attack (mode 3: burst)'),area(),lim('Minor','Hungry (10 shots/round, burst)'),res('Minor','Ammunition',6),mod('Firearms',2),lim('Moderate','Prerequisite (special ammunition)'),FR],
 errata=["p231: Ammunition now costs CR 1 (was \"3x\"). Update the Prerequisite text."],
 notes=["Uses all 3 Minor limitation slots."])
NPC=lim('Minor','No Personal Concealment')
item("Standard Gauss Rifle","Weapons: Firearms",231,"Small",-1,0,[attack('Firefight',2,['Kinetic']),res('Minor','Ammunition',2),lim('Minor',UR+' (cannot be concealed on a person)')])
item("Quality Gauss Rifle","Weapons: Firearms",231,"Small",0,0,[attack('Firefight',3,['Kinetic']),res('Minor','Ammunition',2),mod('Firearms',1),NPC],
 notes=["\"No Personal Concealment\" is the same limitation the Standard rifle writes out as a Usage Restriction. Normalize the wording."])
item("Security Gauss Rifle","Weapons: Firearms",231,"Small",1,1,[attack('Firefight',4,['Kinetic'],label='Attack (mode 1: single target)'),attack('Firefight',3,['Kinetic'],label='Attack (mode 2: burst)'),area(),lim('Minor','Hungry (10 shots/round, burst)'),res('Minor','Ammunition',5),mod('Firearms',1),NPC],
 errata=["(new, 2026-09-26) p231: Single-target attack increases to 4x (was 3x). Burst mode stays 3x."])
item("Plasma Carbine","Weapons: Firearms",232,"Small",2,3,[attack('Firefight',5,['Plasma']),counter('Shields',True),bleed_plasma('Minor',2,4),counter('Armor'),res('Minor','Ammunition',2),tag("The Building's on Fire, and It's My Fault"),lim('Moderate','Prerequisite (special ammunition)')],
 errata=["(new, 2026-09-28) p232: Delete \"Upkeep: 1\". Upkeep was a recurring maintenance cost that was phased out of the rules; this listing is a leftover.","p232: Weapon Multiplier 4x (was 3x). Ammunition costs CR 1 (was 5x). Loses Area; gains Counter: Armor.","(new, 2026-09-27) p232: Attack 5x (was 4x). Bleed 4 (Minor): 2 free from Plasma plus 2 bought."],
 flags=["Plasma normally draws 2 Power Slots, but this carbine is fed by ammunition only. The rule allows either feed, so that's legal; just noting it."])
item("Sniper Rifle","Weapons: Firearms",232,"Small",3,6,[attack('Firefight',5,[]),counter('Armor'),ps('Minor','Coil'),res('Minor','Charge',1),mod('Detection',2),mod('Firearms',2),tag('Reach Out And Touch Someone'),lim('Minor',UR+' (no personal concealment)')],
 errata=["(new, 2026-09-26) p232: Attack 5x (was 4x)."],
 power="3 Minor slots; 1 used.")
# ---------- Grenade / heavy
item("Explosive Grenade","Weapons: Grenades",233,"Small",1,0,[attack('Firefight',6,[]),area(),counter('Armor'),lim('Major','One-Time Use'),lim('Minor','Hungry (1 shot per grenade)')],
 errata=["(new, 2026-09-26) p233: Attack 6x (was 5x)."],
 flags=["No implementation is given (\"Ranged 5x\"). Costed as Energy; as Kinetic it would be 6 BP cheaper. The CR is the same either way.",
        "CC 0 at CR 1 breaks the usual CR→CC pattern (CR 1 → CC 1). Possibly deliberate for consumables; sidearm ammo does the same."])
item("Tactical Railgun","Weapons: Heavy",233,"Small",2,3,[attack('Battlefield',4,['Kinetic']),area(),res('Moderate','Ammunition',4),lim('Moderate','Hungry (10 shots/round)'),mod('Heavy Weapons',2)],
 errata=["(new, 2026-09-26) p233: Size is Small (was Medium). Its Hungry limitation is Moderate (was treated as Minor). Attack stays 4x."],
 flags=["The Suit-Mounted Tactical Weapon template (p234) shrinks its weapons to Small. The railgun is now Small already, so for it the template only adds the power requirement and the Slave limitation."],
 power="Draws 1 Moderate slot from its host (no Power Supply of its own).",
 notes=["Uses both ammunition and power. See Conventions: gauss/rail weapons in this chapter do this."])
item("Tactical Missile Rack","Weapons: Heavy",233,"Medium",1,1,[launchers('Battlefield',12),res('Moderate','Magazine',3),mod('Gunnery',2),lim('Minor',UR+' (cannot reload during combat)'),lim('Moderate','Slave (mounted on a host unit that powers it)')],
 errata=["(new, 2026-09-27) p233: Adds Limitation: Slave (Moderate); the rack is a module mounted on and powered by a host unit."],
 power="Draws 3 Moderate slots from its host (12 launchers ÷ 4 = 3). OK.")
item("Light Plasma Cannon","Weapons: Heavy",234,"Medium",2,3,[attack('Battlefield',5,['Plasma']),counter('Shields',True),bleed_plasma('Moderate',2,4),area(),res('Moderate','Ammunition',4),tag("The Building's on Fire, and It's My Fault"),lim('Moderate','Prerequisite (special ammunition)')],
 errata=["p234: Ammunition costs CR 1 (was 5x). Update the Prerequisite text.","(new, 2026-09-27) p234: Attack 5x (was 4x). Bleed 4 (Moderate): 2 free from Plasma plus 2 bought."],
 power="Draws 2 Moderate slots from its host (Plasma = 2). OK.")
item("Suit-Mounted Tactical Weapon","Weapons: Heavy",234,"Small",None,None,[other('Template','Apply to Tactical Railgun, Tactical Missile Rack, or Light Plasma Cannon: size becomes Small, add +1 Moderate slot to the power requirement, add Limitation: Slave (unit with a Weapon Link)')],compute=False,
 notes=["A modification template, not an item. Implement it as a variant/derived item. No CR is printed."])
# ---------- Computers
item("Personal Computer","Computers",234,"Small",0,0,[computer('Minor',3),tasks([('Intrusion Detection',18)]),link('Minor','Data'),tag('Pick Up and Go')],power="Draws 1 Minor slot from its host/battery.")
item("Carry Comp","Computers",235,"Tiny",1,1,[radio('Minor'),computer('Minor',4),tasks([('Intrusion Detection',18)]),link('Minor','Data'),lim('Moderate','Prerequisite (requires a neural interface)')],errata=["(new, 2026-09-27) p235: Computer is rank 4 (TN 20), not rank 3."],power="Draws 1 Minor slot.")
# ---------- Power
item("Personal Psi Link","Power Supplies",235,"Small",1,1,[link('Major','Psi'),ps('Moderate','Coil'),res('Moderate','Charge',2)],
 errata=["p235: Power Supply is Moderate (was Major); Strain Threshold 10 (was 25). The Charge resource drops to Moderate to match.","(new, 2026-09-25) p216: Moderate Power Supplies are allowed on Small items, so this is now legal.","(new, 2026-09-27) p235: 2 Moderate Charge (was 1; 20 days or 20 combat rounds). CR 1, CC 1 (was CR 2, CC 3); the printed CR matched the original Major power supply."],
 flags=["Printed CR/CC shown here are the errata values. The book printed CR 2, CC 3."],
 power="3 Moderate slots; 1 used.")
item("Coil Stack Battery/Recharger","Power Supplies",235,"Small",0,0,[ps('Moderate','Coil'),res('Moderate','Charge',2)],
 errata=["(new, 2026-09-28) p235: Size is Small, not Tiny (a Moderate Power Supply needs a Small item), and it holds 2 Moderate Charge, not 1."],power="3 Moderate slots; 0 used.")
# ---------- Manufacturing
item("Personal G3P","Manufacturing",236,"Small",1,1,[manuf('Moderate'),mod('Design Software',1),tag("Hobbyist Builder's Best Friend",3)],errata=["(new, 2026-09-27) p236: [Hobbyist Builder's Best Friend] is rank 3 (was 1)."],power="Draws 1 Moderate slot from its host.")
item("Craftsman G3P","Manufacturing",236,"Medium",2,3,[manuf('Moderate'),manuf('Major'),mod('Design Software',1),tag('Professional Grade')],power="Draws 1 Moderate + 1 Major slot from its host.")
item("Commercial G3P","Manufacturing",236,"Large",3,6,[manuf('Major',3),mod('Design Software',2),tag('Industrial Load'),tag('No Assembly Required')],power="Draws 3 Major slots from its host.")
# ---------- Implants
item("Basic Neural Interface Control Link (NICL)","Biotech: Implants",237,"Tiny",0,2,[link('Minor','Data'),ni('Moderate'),mod('Technical-class Skills',1),mod('Initiative',1),tag('Protective Limiters'),lim('Minor',UR+' (Skill modifiers only apply to linked gear)')],
 extra={'XP':'4'},errata=["(new, 2026-09-27) p237: Modifier: Initiative +1 (was +2), per the build notes."],notes=["Initiative: +2 from the Moderate Neural Interface when operating linked equipment; +1 in general from the Modifier."],flags=["\"Technical-class Skills +1\" covers a class of skills. Costed as one Modifier."])
item("Advanced Neural Interface Control Link","Biotech: Implants",237,"Tiny",1,4,[link('Major','Data'),ni('Major'),mod('Technical-class Skills',1),mod('Initiative',2),tag('Dance Along The Bleeding Edge',2),lim('Major','[...But You Might Get Cut 2]: hacking that breaches the user’s defenses can inflict physical damage'),lim('Minor',UR+' (Skill modifiers only apply to linked gear)')],
 extra={'XP':'6'},errata=["(new, 2026-09-28) p237: Initiative Modifier is +2 (was +3). The Major Neural Interface gives +3 Initiative when operating linked equipment; the Modifier is the general bonus. [Dance Along the Bleeding Edge, But You Might Get Cut] splits in two: the Tag [Dance Along The Bleeding Edge 2] and the Major limitation [...But You Might Get Cut 2].","(new, 2026-09-25) p237: [Dance Along the Bleeding Edge, But You Might Get Cut] is a Major Limitation, not a Tag: hacking that breaches the user’s defenses can inflict physical damage."],
 notes=["Initiative: +3 from the Major Neural Interface when operating linked equipment; +2 in general from the Modifier."])
item("Reflex Enhancements","Biotech: Implants",237,"Tiny",1,4,[mod('Initiative',3),tag('Need For Speed')],extra={'XP':'6'},
 errata=["(new, 2026-09-27) p237: Adds Tag: [Need For Speed]."])
item("Cybernetic Arm","Biotech: Implants",238,"Small",0,2,[ps('Minor','Coil'),res('Minor','Charge',3),mod('Appropriate physical tasks',2)],extra={'XP':'4'},power="3 Minor slots; 1 used.")
item("Psi Amp","Biotech: Drugs",238,"Tiny",1,1,[other('Counter','Strain, 1 rank (+5 Psionic Strain, initial hit)',20),regen('Major',5,'Strain'),res('Minor','Duration',1),tag('My Mind Is Clear'),lim('Minor','[Euphoria] (side effect)'),lim('Major','One-Time Use')],
 errata=["(new, 2026-09-28) p238: Rebuilt. The initial hit is Counter: Strain, 1 rank (+5 Psionic Strain), followed by Regeneration: Strain 5 (Major, every round) for its Duration (1 Minor rank: 10 combat rounds). [Euphoria] is a Minor limitation. Supersedes the +10 Strain erratum.","p238: Psionic Strain +10 (was +25)."],
 notes=["Counter: Strain is 20 BP per rank of 5 Strain. Duration is bought as a Resource."])
item("Psi Damp","Biotech: Drugs",238,"Tiny",1,1,[other('Counter','Strain, 5 ranks (−25 Psionic Strain)',100),res('Moderate','Duration',1),lim('Moderate','[It Itches In My Brain 3] (side effect)'),lim('Major','One-Time Use')],
 errata=["(new, 2026-09-28) p238: Costed as Counter: Strain, 5 ranks (−25 Psionic Strain), with a Duration of 1 Moderate Resource rank (1 day). [It Itches In My Brain] becomes [It Itches In My Brain 3], a Moderate limitation."])
item("“Fluffy”","Creatures",239,"Medium",3,6,[attack('Firefight',3,['Melee'],label='Attack (Claws and Teeth)'),armor('Firefight',3),body('Medium',30),drive('Minor','Land (legs)'),maneuver('Minor',1),computer('Minor',4,'Brain'),tasks([('Stealth',17),('Combat',17),('Athletics',18),('Tracking',18),('Initiative',5)],True),lim('Moderate','Malfunction [Has A Mind of His Own]'),tag('Nice Kitty/Good Doggie',2),tag('Does He Do Any Tricks?'),tag('Loyal Companion',2),tag('Quick on His Feet',3)],
 errata=["(new, 2026-09-28) p239: Adds Drive: Minor Land (legs), which carries its Maneuver 1.","(new, 2026-09-26) p239: Armor Rating 3 (was 2)."],
 flags=["\"Initiative 5\" as a Task is odd (TN 5). Probably meant as an Initiative value, not a Task."],
 notes=["Attack can optionally deal Subdual damage."])
item("Monster in the Dark","Creatures",239,"Medium",None,None,[attack('Firefight',4,['Melee'],label='Attack (Lethal Claws)'),counter('Armor'),drive('Minor','Land (legs)'),maneuver('Minor',1),computer('Minor',4,'Brain'),tasks([('Stealth',18),('Combat',19),('Athletics',18),('Tracking',16),('Initiative',5)],True),lim('Moderate','Malfunction [Inverse Ninja Rule 3]'),tag("Don't Turn Around",2),tag('Clever Girl'),tag('Quick on Its Feet',3)],
 errata=["(new, 2026-09-28) p239: Adds Drive: Minor Land (legs), which carries its Maneuver 1."],
 flags=["Same Initiative-Task issue as Fluffy. No Armor or Body listed (default Body 10)."],notes=["GM creature; not for sale (CR —)."])
# ---------- Vehicles
SLV=lim('Moderate','Slave (external navigational infrastructure, such as GPS)')
item("Colonial Personal Transport (Hoverbike)","Vehicles: Personal",240,"Medium",1,1,[armor('Firefight',2),body('Medium',10),lim('Moderate','Partial Armor (aimed shots bypass it)'),drive('Minor','Ground'),drive('Minor','Air'),maneuver('Minor',2),res('Minor','Fuel',2),radio('Minor'),computer('Minor',1),cargo('Minor'),tag('Life is Too Short for Traffic'),tag("Drive or Pilot, It's All the Same")],
 errata=["(new, 2026-09-28) p240: Armor Rating 2 (Firefight), not 1. \"Cover: Moderate (Partial)\" becomes Limitation: Partial Armor (Moderate); an aimed shot bypasses the armor."],
 power="6 Minor slots (two Drives); 0 used. OK.",notes=["[Drive or Pilot, It's All the Same]: free Skill switch between Drive and Pilot."])
item("Family Transport","Vehicles: Personal",240,"Medium",0,0,[body('Medium',15),drive('Minor','Ground'),res('Minor','Fuel',2),radio('Minor'),computer('Minor',2),tasks([('Drive',15)]),cargo('Minor'),SLV],
 errata=["(new, 2026-09-27) p240: Fuel is 2 Minor (20 days/combat rounds; was 5). Task: Drive 15 (was 16)."])
item("Quality Family Transport","Vehicles: Personal",241,"Medium",1,1,[body('Medium',20),drive('Minor','Ground'),maneuver('Minor',1),res('Minor','Fuel',3),radio('Minor'),computer('Minor',3),tasks([('Drive',18)]),cargo('Minor'),tag('A Touch of Class',2),tag('Security'),SLV])
item("Speedster","Vehicles: Personal",241,"Medium",2,3,[body('Medium',30),drive('Minor','Ground'),maneuver('Minor',3),res('Minor','Fuel',3),cargo('Minor'),radio('Minor'),computer('Minor',3),tasks([('Drive',17)]),mod('Drive',2),tag('Security'),tag('Turns on a Dime'),tag('...And Turns A Few Heads',3,True),SLV],
 errata=["(new, 2026-09-27) p241: Adds Modifier: Drive +2 and the Free Tag [...And Turns A Few Heads 3]."])
item("Light Air Transport","Vehicles: Personal",242,"Large",2,3,[body('Large',50),drive('Minor','Air'),maneuver('Minor',2),res('Minor','Fuel',5),radio('Minor'),computer('Minor',4),tasks([('Autopilot',20),('Intrusion Detection',17)]),cargo('Moderate'),tag('Security'),SLV],
 errata=["(new, 2026-09-27) p242: Adds Task: Intrusion Detection 17 (per the build notes)."],
 notes=["A flying van: Large. The Light Performance Aircraft is a 2–3 seat craft, a bigger Hoverbike: Medium."])
item("Light Performance Aircraft","Vehicles: Personal",242,"Medium",3,6,[armor('Firefight',2),body('Medium',40),drive('Minor','Ground'),drive('Minor','Air'),res('Minor','Fuel',4),maneuver('Minor',4),radio('Minor'),computer('Minor',3),tasks([('Autopilot',18)]),cargo('Moderate'),ls('Minor',3),mod('Detection',1),tag('Security',2),tag("Barnstormer's Dream"),SLV],
 errata=["(new, 2026-09-28) p242: Life Support is 3 Minor (3 people), not 1 Moderate (12); it is a 2–3 seat craft.","(new, 2026-09-26) p242: Armor Rating 2 (was 1)."],power="6 Minor slots; 0 used.")
item("Cargo Transport","Vehicles: Commercial",243,"Large",2,3,[body('Large',50),drive('Minor','Ground'),res('Minor','Fuel',5),radio('Minor'),computer('Minor',3),tasks([('Drive',18)]),cargo('Moderate'),SLV,tag('Security',2),other('Tags','[Free Tags 3] or 15 BP (player-defined)',15)],
 errata=["(new, 2026-09-27) p243: [Security 2] (was [Security])."],
 notes=["\"[Free Tags 3] or 15 BP\": a placeholder the owner fills with Tags worth 15 BP, or spends as 15 BP on other attributes."])
item("Armored Cargo Transport","Vehicles: Commercial",243,"Large",3,6,[armor('Battlefield',4),body('Large',90),drive('Minor','Ground'),maneuver('Minor',1),res('Minor','Fuel',5),radio('Minor'),computer('Minor',4),tasks([('Drive',17),('Intrusion Detection',20)]),cargo('Moderate'),ls('Moderate'),mod('Detection',1),tag('Security',2),tag('Signed, Sealed, Delivered'),SLV],
 errata=["(new, 2026-09-28) p243: Body Track 90 (was 80). Computer is Minor rank 4 (20 target), not rank 3, to run its Intrusion Detection 20 Task."])
item("Air Transport","Vehicles: Commercial",244,"Large",3,6,[armor('Battlefield',2),body('Large',90),drive('Minor','Air'),maneuver('Minor',2),res('Minor','Fuel',5),cargo('Major',3),ls('Moderate'),computer('Minor',3),tasks([('Pilot',16),('Intrusion Detection',17)]),radio('Minor'),SLV,tag('Security',2)],errata=["(new, 2026-09-28) p244: Body Track 90 (was 80).","(new, 2026-09-27) p244: Armor Rating 2 (Battlefield; was 1). Maneuver 2 (was 1). Cargo is 3 Major (was 3 Moderate). Adds Life Support: Moderate (12 passengers). Computer is Minor rank 3 (was 2) and adds Task: Intrusion Detection 17."])
item("Assault Platform","Vehicles: Military",244,"Large",4,10,[attack('Battlefield',5,['Kinetic'],2,'Attack (main cannon)'),res('Moderate','Ammunition',4),am('Battlefield'),armor('Battlefield',4),body('Large',90),drive('Moderate','Ground'),maneuver('Moderate',2),ps('Moderate','Fusion'),res('Moderate','Fuel',3),ls('Moderate'),link('Moderate','Weapon',2),mod('Gunnery',2)],
 errata=["(new, 2026-09-28) p244: Body Track 90 (was 80)."],power="6 Moderate slots; 3 used (2 rail cannons + Anti-Missile). OK.")
item("Attack Hovercraft","Vehicles: Military",245,"Large",4,10,[armor('Battlefield',3),body('Large',90),attack('Battlefield',5,['Kinetic'],label='Attack (heavy railgun, single target)'),attack('Battlefield',4,['Kinetic'],label='Attack (burst mode)'),area(),lim('Minor','Hungry (10 shots/round)'),res('Moderate','Ammunition',3),drive('Minor','Air'),maneuver('Minor',3),ps('Moderate','Fusion',2),res('Moderate','Fuel',3),link('Moderate','Weapon',3),computer('Minor',2),radio('Minor'),mod('Detection',1),mod('Gunnery',1),tag('High Security',3),tag('Float Like a Butterfly'),tag('Sting Like a Bee',2),lim('Moderate','Crew Requirement (2)')],
 errata=["(new, 2026-09-28) p245: Body Track 90 (was 80).","(new, 2026-09-28) p245: Power Supply is Moderate Fusion rank 2 (was 1), so its 3 Weapon Links have power. Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).","(new, 2026-09-26) p245: Heavy railgun single-target attack increases to 5x (was 4x). Burst mode stays 4x."],
 flags=["Crew Requirement lists 2, but for a Large item the rule is 5. The number is flavor; the limitation is the same."],
 power="3 Minor (Air Drive; 0 used) + 6 Moderate (Fusion ×2; 2 used, 4 spare for its 3 Weapon Links). OK.")
item("Armored Personnel Carrier","Vehicles: Military",245,"Large",4,10,[attack('Battlefield',5,['Kinetic'],label='Attack (heavy gauss gun, single target)'),attack('Battlefield',4,['Kinetic'],label='Attack (burst mode)'),area(),lim('Minor','Hungry (10 shots/round)'),res('Moderate','Ammunition',4),armor('Battlefield',4),body('Large',90),drive('Minor','Ground'),ps('Moderate','Fusion',2),res('Moderate','Fuel',2),hangar('Major'),link('Minor','Weapon',2),mod('Detection',1),mod('Gunnery',1),tag('High Security',3),tag('Send in the Marines'),lim('Moderate','Crew Requirement (2)')],
 errata=["(new, 2026-09-28) p245: Body Track 90 (was 80).","(new, 2026-09-28) p245: Power Supply is Moderate Fusion rank 2 (was 1), so its 2 Weapon Links have power. Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).","(new, 2026-09-26) p245: Armor Rating 4 (was 3); single-target attack 5x (was 4x; burst stays 4x); Hangar is Major (was Minor), which holds the Medium marines."],
 power="3 Minor (Ground Drive; 0 used) + 6 Moderate (Fusion ×2; 2 used, 4 spare for its 2 Weapon Links). OK.")
# ---------- Probes & drones
item("Autonomous Kill Vehicle (“Auntie”)","Space: Probes and Drones",246,"Medium",4,10,[body('Medium',25),attack('Space',5,[],label='Attack (light particle beam)'),lim('Moderate','No Far Range (the beam cannot fire at Far Range)'),drive('Moderate','Reaction'),res('Moderate','Fuel',1),maneuver('Moderate',3),ps('Major','Coil'),res('Major','Charge',1),computer('Minor',3),tasks([('Detection',15),('Gunnery',18),('Piloting',17)]),radio('Moderate'),tag('Coordinated Fire'),tag('Security'),lim('Major','One-Time Use')],
 errata=["(new, 2026-09-26) p246: Attack 5x (was 4x). Adds a Major Coil Power Supply (rank 1) with 1 rank of Major Charge (10 combat rounds) to power the Space-scale beam (new p216 rule: Coil can be Major on a Medium item). Maneuver 3 (was 5; the cap is 4). Its Far Range restriction is a Moderate limitation, No Far Range (was a Minor Usage Restriction)."],
 power="3 Moderate (Reaction Drive), 3 Major (Coil); 1 Major used (beam).")
item("Recon Drone","Space: Probes and Drones",246,"Medium",2,3,[body('Medium',10),drive('Moderate','Reaction'),res('Moderate','Fuel',1),maneuver('Moderate',4),computer('Minor',3),tasks([('Piloting',18)]),radio('Moderate'),ansible(),res('Major','Tangle',1),mod('Detection',2),tag('Security',2),tag('I Spy with my Little Eye…'),lim('Major','One-Time Use')],
 errata=["(new, 2026-09-28) p246: Maneuver 4 (was 5; the cap is 4). Computer is Minor rank 3 (18 target), not rank 2, to run its Piloting 18 Task."])
item("SAR Probe","Space: Probes and Drones",247,"Medium",2,3,[body('Medium',20),drive('Moderate','Reaction'),res('Moderate','Fuel',3),ls('Moderate'),radio('Moderate'),computer('Minor',4),tasks([('Survivor Extraction',19)]),mod('Detection',1),mod('Medicine (first response only)',2),tag('Security',2),tag('Medical Supplies'),tag('Grappling Arms'),lim('Moderate','Slave (external control only)')])
item("Stealth FTL Recon Drone","Space: Probes and Drones",247,"Medium",6,21,[armor('Space',1,True),drive('Moderate','Reaction'),drive('Major','Gravitic'),res('Major','Fuel',2),maneuver('Major',2),computer('Minor',4),tasks([('Piloting',17),('Detection',19),('Intrusion Detection',15)]),ansible(),res('Major','Tangle',1),tag('Security',2),tag('I Spy with my Little Eye\u2026'),lim('Moderate','One Track Mind (follows its programmed route)'),lim('Major','One-Time Use (burned out after each run; an extended Engineering roll returns it to service)')],
 errata=["(new, 2026-09-25) p247: Stat block replaced by PJ's rebuilt design (spreadsheet \"FTL Recon Probe\"): CR 6, CC 21. Changes from the printed block: the original build notes left out the Shrouded Hull; Body is the default 10 (was 15); Fuel is 2 Major ranks shared by both Drives (was 5 Moderate + 1 Major); Maneuver is 2 at Major grade (was 4 at Moderate); Tangle 1 rank (was 2); Tags [Security 2] (was [High Security 3]); adds Limitations One Track Mind (Moderate) and One-Time Use (Major).",
        "(new, 2026-09-25) p217: A Major Fuel tank can feed the Moderate Reaction Drive (fuel feeds its own grade or lower)."],
 flags=["Printed CR/CC shown here are the errata values (CR 6, CC 21). The book printed CR 5, CC 15."],
 notes=["The spreadsheet listed Sensors – EM (Minor, 5 BP); dropped per PJ. The spreadsheet's Reaction Drive cost of 15 is corrected to 25 (Moderate Drive), giving 364 BP; CR is 6 either way."],
 power="3 Moderate (Reaction Drive), 3 Major (Gravitic Drive); 0 used.")
# ---------- Civilian starships
item("Telekinetic Shuttle","Space: Civilian Starships",248,"Large",3,6,[armor('Space',1),body('Large',50),ps('Major','Coil'),res('Major','Charge',2),link('Major','Psi'),radio('Moderate'),computer('Minor',2),cargo('Major'),ls('Moderate',2),mod('Pilot',1),tag('Security'),tag('Lifting Body',2),tag('Easy on the Hangar Bay'),lim('Minor',UR+' (Telekinetic operators only)')],
 errata=["(new, 2026-09-28) p248: Its Coil Power Supply runs on 2 Major Charge, not 2 Major Fuel.","p238: Telekinetic Shuttle has a Major Psi Link (added)."],
 flags=["No Drive: the Psionic operator moves it by Telekinesis. Intentional, but the validator will flag it as a vehicle without a Drive."],
 power="3 Major slots; 0 used.")
item("Courier","Space: Civilian Starships",248,"Large",5,15,[armor('Space',2),body('Large',110),drive('Minor','Air'),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',4),res('Major','Fuel',8),radio('Moderate'),ansible(),res('Major','Tangle',4),computer('Minor',3),cargo('Minor'),ls('Moderate',2),tag('We Get There Fast'),tag('Security',2),other('Tags','[Free Tags 3] or 15 BP',15),lim('Moderate','Crew Requirement (5)')],
 power="3 Minor, 3 Moderate, 3 Major; 0 used. OK.")
item("Shuttle/Yacht","Space: Civilian Starships",249,"Large",4,10,[body('Large',70),drive('Minor','Air'),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',2),res('Major','Fuel',6),radio('Moderate'),ansible(),res('Major','Tangle',2),computer('Minor',5),tasks([('Pilot',17)]),cargo('Moderate'),ls('Moderate'),tag('Security',2),tag('The Grand Tour',3,True)],
 errata=["(new, 2026-09-27) p249: Adds Task: Pilot 17 and the Free Tag [The Grand Tour 3]. Tangle is 2 ranks (20 days), not 1."])
item("Locust Mobile Industrial Platform","Space: Civilian Starships",250,"Huge",7,28,[armor('Space',2),body('Huge',250),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',1),res('Major','Fuel',9),radio('Moderate'),ansible(),res('Major','Tangle',2),computer('Moderate',4),tasks([('Engineering (Spacecraft)',20),('Engineering (Asteroid Mining)',20)]),manuf('Major'),hangar('Major'),cargo('Minor'),cargo('Moderate'),cargo('Major'),eco('Moderate'),grav('Major'),tag('The Family Shop',3),tag('Buy It, Use It, Break It, Fix It'),lim('Moderate','Crew Requirement (20)')],
 errata=["(new, 2026-09-28) p250: Total Power Slots read 6 Major (3 used); the grade was missing.","(new, 2026-09-27) p250: Armor Rating 2 (Space; was 1), Body Track 250 (was 200), and Maneuver 1 (not listed)."],
 power="6 Major (two Major Drives; 3 used).")
item("Factory Freighter","Space: Civilian Starships",251,"Huge",9,45,[armor('Space',4),body('Huge',300),drive('Moderate','Reaction'),drive('Major','Gravitic'),res('Major','Fuel',10),radio('Moderate'),ansible(),res('Major','Tangle',8),computer('Major',3),manuf('Major',3),cargo('Major',3),hangar('Major',2),ls('Major',5),tag('Security',2),tag('Small Town in Space',2),tag('Profit and Prize',3),lim('Moderate','Crew Requirement (20 navigation, 40 manufacturing)')],
 errata=["(new, 2026-09-27) p251: Reaction Drive is Moderate, not Major. Hangars 2 Major (was 3). Life Support 5 Major (500 people, was 6). CR 9, CC 45 (was CR 8, CC 36). Computer is Major rank 3 (18 target); remove \"5 tasks\" (a Major computer runs unlimited tasks)."],
 flags=["Printed CR/CC shown here are the errata values (CR 9, CC 45). The book printed CR 8, CC 36."],
 power="3 Major (Gravitic Drive) + 3 Moderate (Reaction Drive); 3 Major used (3 Manufactures). OK.")
item("Light Lugger","Space: Civilian Starships",251,"Huge",7,28,[armor('Space',3),body('Huge',350),drive('Moderate','Light Sail'),ps('Moderate','Coil'),res('Moderate','Charge',6),lim('Minor','Usage Restriction (charged only through laser contact)'),radio('Moderate'),ansible(),res('Major','Tangle',6),computer('Major',4),hangar('Major',2),cargo('Major',6),ls('Major',5),tag('Towing Rig',3),tag('Security',2),tag('AAALLL Ah-BOARD!'),lim('Moderate','Crew Requirement (10 skeleton, 20 full)')],
 power="6 Moderate slots (Light Sail 3 + Coil 3); 0 used. OK.")
# ---------- Military starships
AMS=am('Space')
item("Security Escort/Corsair","Space: Military Starships",252,"Large",5,15,[attack('Space',4,[],label='Attack (main battery)'),AMS,armor('Space',3),body('Large',110),drive('Moderate','Reaction'),maneuver('Moderate',3),drive('Major','Gravitic'),ps('Major','Fusion'),res('Major','Fuel',8),link('Minor','Weapon',2),radio('Moderate'),computer('Moderate',3),ls('Moderate'),mod('Gunnery',1),tag('Security',2),tag('Float Like a Butterfly, Sting Like a Bee',2),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["(new, 2026-09-28) p252: Total Power Slots read 6 Major (2 used), 3 Moderate (0 used), not 9 Major (4 used). Weapons fitted to its Weapon Links draw further slots."],
 power="6 Major (Gravitic Drive + Fusion; 2 used: main battery, Anti-Missile) + 3 Moderate (Reaction Drive; 0 used). OK.",
 flags=["Maneuver is bought at Moderate; the rule says Major (the largest Drive). At Major it's +30 BP; CR unchanged."])
item("Standard Assault Shuttle","Space: Military Starships",252,"Large",5,15,[attack('Space',4,[],label='Attack (laser battery)'),launchers('Space',4),res('Major','Magazine',2),armor('Space',3),body('Large',90),drive('Minor','Air'),drive('Moderate','Reaction'),radio('Moderate'),drive('Major','Gravitic'),maneuver('Major',2),res('Major','Fuel',2),hangar('Major'),ls('Moderate',2),mod('Gunnery',1),tag('High Security',3),tag('Rapid Fire',2),tag('Send in the Marines'),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 flags=["No Computer listed; it has no Tasks, so none is required."],power="Not listed. The Drives give 3 of each grade; 2 Major used (laser + launchers).",
 errata=["(new, 2026-09-28) p252: Adds Communications: Moderate (Radio).","(new, 2026-09-28) p252: 4 Launchers (Space), not 2 (launchers come in sets of 4)."])
item("Tanker/Command Ship","Space: Military Starships",253,"Large",6,21,[AMS,armor('Space',4),body('Large',110),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',3),res('Major','Fuel',10),other('Bulk fuel stores','Carried as Cargo (below); see errata',0),radio('Moderate'),ansible(),res('Major','Tangle',4),computer('Moderate',4),cargo('Major',2),ls('Moderate'),mod('Detection',2),mod('Tactics',1),tag('Security',2),tag('Command and Control'),tag('Mid-Flight Refuel'),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["(new, 2026-09-28) p253: The ship's own Fuel is 10 Major (100 days), separate from the bulk fuel it carries as Cargo.","(new, 2026-09-26) p253: Armor Rating 4 (was 3).","(new, 2026-09-25) p253: The printed \"100 Major Fuel\" is bulk fuel held as Cargo, not the ship's own Fuel Resource. Pumping it from the storage tanks into a ship's systems takes an Engineering check."])
item("System Defense Craft (Pocket Cruiser)","Space: Military Starships",253,"Large",6,21,[attack('Space',5,['Kinetic'],label='Attack (heavy railgun)'),res('Major','Ammunition',2),AMS,launchers('Space',4),res('Major','Magazine',4),armor('Space',4),body('Large',110),drive('Major','Reaction'),maneuver('Major',4),res('Major','Fuel',3),radio('Moderate'),computer('Moderate',3),ls('Moderate'),mod('Detection',1),mod('Gunnery',1),tag('High Security',3),tag('Rapid Fire',2),tag('Sentinel'),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["(new, 2026-09-28) p253: In the alternate forms, \"missile array\" means the 4 Launchers and \"particle cannon\" means the heavy railgun (an earlier draft's name)."],
 notes=["Alternate form STRIKE CRAFT: +1 Armor Rating; add Energy Ranged (Space, linked particle cannon); +1 to the heavy railgun's multiplier; remove the 4 Launchers.","Alternate form TORPEDO BOAT: add 4 Launchers and +1 Magazine; remove the heavy railgun."])
item("Dragon-class Fleet Interceptor/Escort","Space: Military Starships",254,"Large",6,21,[launchers('Space',8),res('Major','Magazine',6),armor('Space',4),body('Large',90),ff('Moderate',4),drive('Moderate','Reaction'),drive('Minor','Air'),ps('Major','Fusion (auxiliary)'),maneuver('Moderate',4),res('Major','Fuel',2),radio('Moderate'),computer('Moderate',3),ls('Minor',2),mod('Detection',1),mod('Gunnery',1),tag('Shohan Killer'),tag('High Security',3),tag('Hit and Run Tactics'),tag('Take One for the Team'),lim('Moderate','Crew Requirement (2)')],
 errata=["(new, 2026-09-28) p254: Fuel is 2 Major (20 days), not 2 Moderate, so it can run the Major Fusion reactor as well as the drives.","(new, 2026-09-28) p254: The Air Drive is Minor, not Moderate (a typo; the build notes have a Moderate in-system Reaction Drive and a Minor Air Drive). It carries 8 Launchers, not 6.","(new, 2026-09-25) p254: Adds the auxiliary Major Fusion Power Supply (rank 1) described in the design notes but missing from the stat block. Power Slots become 6 Moderate + 3 Major."],
 notes=["[Take One for the Team] lets the Dragon redirect an attack onto itself."])
item("Bridgehead Assault Shuttle","Space: Military Starships",255,"Large",6,21,[attack('Space',5,['Plasma'],label='Attack (rapid plasma cannon)'),counter('Shields',True),bleed('Major',2,True),AMS,armor('Space',4),body('Large',90),ff('Moderate',3),drive('Minor','Air'),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',3),res('Major','Fuel',2),radio('Moderate'),computer('Moderate',3),hangar('Major'),ls('Moderate',2),mod('Detection',1),mod('Gunnery',1),tag('High Security',3),tag('Rapid Fire',2),tag('Send in the Marines'),lim('Major','Restricted Technology (property of the Terran Sphere)'),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["(new, 2026-09-28) p255: Bleed is Major 2 (the free Plasma Bleed: half of 5x, rounded down), not Major 3. Total Power Slots read 3 Moderate (1 used), 3 Major (3 used).","(new, 2026-09-26) p255: Armor Rating 4 (was 3); plasma cannon 5x (was 4x)."],
 power="3 Moderate (1 used: Force Field), 3 Major (3 used: Plasma 2, Anti-Missile 1). OK.")
item("Phantom Deep Recon and Insertion Vehicle (DRIV)","Space: Military Starships",255,"Large",8,36,[launchers('Space',4),res('Major','Magazine',4),lim('Minor',UR+' (no combat reload)'),armor('Space',3,True),body('Large',110),lim('Minor',UR+' (hull shroud does not work during atmospheric re-entry)'),drive('Major','Gravitic (modified in-system)'),lim('Minor','Hungry (1 Fuel/round for in-system maneuvers)'),drive('Moderate','Reaction'),drive('Moderate','Air'),drive('Minor','Sea/Submersible'),maneuver('Moderate',4),res('Major','Fuel',7),radio('Moderate'),laser('Moderate'),ansible(),res('Major','Tangle',5),computer('Moderate',3),manuf('Major'),cargo('Major'),ls('Moderate'),mod('Detection',2),mod('Gunnery',1),tag('Marines on Ice'),tag('The High Dive'),tag("Now You See Me, Now You Don't",2),tag('High Security',3),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["p255: Moderate Laser Link (added)."],
 notes=["Uses all 3 Minor limitation slots."])
item("Standard Cruiser","Space: Military Starships",256,"Huge",8,36,[attack('Space',5,['Kinetic'],2,'Attack (heavy railgun turrets)'),res('Major','Ammunition',8),AMS,launchers('Space',4),res('Major','Magazine',4),armor('Space',4),body('Huge',250),drive('Major','Gravitic'),drive('Moderate','Reaction'),maneuver('Major',3),ps('Major','Fusion'),res('Major','Fuel',10),radio('Moderate'),ansible(),computer('Major',3),res('Major','Tangle',3),cargo('Moderate'),hangar('Moderate'),ls('Major'),mod('Detection',2),mod('Gunnery',2),mod('Tactics',1),tag('High Security',3),tag('Coordinated Fire',2),tag('On Patrol'),lim('Moderate','Crew Requirement (20 skeleton, 75 full)')],
 errata=["(new, 2026-09-28) p256: Adds Computer: Major 3 (18 target, unlimited tasks), matching the Redemption and Retribution.","(new, 2026-09-28) p256: Adds Power Supply: Major Fusion, rank 1, to power its integrated railgun turrets. Total Power Slots read 6 Major (4 used), 3 Moderate (0 used), not 3 Major (2 used)."],
 power="6 Major (Gravitic Drive + Fusion; 4 used: 2 railgun turrets, Anti-Missile, 4 Launchers = 1) + 3 Moderate (Reaction Drive; 0 used). OK.")
item("Defiance-class Cruiser","Space: Military Starships",257,"Huge",7,28,[attack('Space',8,['Plasma'],label='Attack (spinal heavy plasma cannon)'),counter('Shields',True),bleed('Major',4,True),AMS,launchers('Space',4),res('Major','Magazine',4),armor('Space',5),body('Huge',200),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',4),res('Major','Fuel',3),radio('Moderate'),ansible(),res('Major','Tangle',2),computer('Major',3),ls('Moderate'),mod('Detection',1),mod('Gunnery',1),tag('High Security'),tag('Go to Rapid Fire!'),tag('Shohan Killer'),lim('Moderate','Malfunction [That Gun’s Got Kick 2]')],
 power="6 Major; 4 used (Plasma 2, Anti-Missile 1, Launchers 1). OK.")
item("Conventional Frigate","Space: Military Starships",258,"Huge",10,55,[attack('Space',6,[],2,'Attack (laser batteries alpha and beta)'),counter('Armor'),AMS,launchers('Space',8),res('Major','Magazine',6),armor('Space',5),body('Huge',350),drive('Major','Reaction'),drive('Major','Gravitic'),res('Major','Fuel',7),radio('Moderate'),ansible(),res('Major','Tangle',5),computer('Major',4),tasks([('Intrusion Detection',20)]),cargo('Major'),hangar('Major',2),ls('Major',3),mod('Detection',2),mod('Engineering (Starship)',1),mod('Gunnery',4),mod('Tactics',1),tag('High Security',3),tag('Go to Rapid Fire!',2),tag('The One-Two Punch',2),lim('Moderate','Crew Requirement (100 skeleton, 200 full)')],
 errata=["(new, 2026-09-28) p258: 8 Launchers (Space), not 6 (launchers come in sets of 4).","p258 (\"Standard Frigate\"): skeleton crew 100 (was 10), full complement 200 (was 20). Applied here on the assumption that it means the Conventional Frigate; there's no ship called Standard Frigate."],
 power="6 Major; 5 used (2 lasers, Anti-Missile, 6 Launchers = 2). OK.")
item("Intrepid-class Frigate","Space: Military Starships",258,"Huge",9,45,[attack('Space',7,['Kinetic'],2,'Attack (railgun turrets)'),res('Major','Ammunition',8),AMS,launchers('Space',4),res('Major','Magazine',4),armor('Space',5),body('Huge',400),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',2),res('Major','Fuel',5),radio('Moderate'),laser('Moderate'),ansible(),res('Major','Tangle',2),computer('Major',3),hangar('Moderate'),ls('Major'),mod('Detection',2),mod('Gunnery',2),tag('Hold the Line',3),tag('Security Alert',2),lim('Moderate','Crew Requirement (30 skeleton, 85 full with marines)')],
 notes=["The railguns take no Power Slots here (2 used = Anti-Missile + Launchers), unlike the ground-scale rail weapons. See Conventions."])
item("Resolute-class Frigate","Space: Military Starships",259,"Huge",10,55,[attack('Space',7,[],label='Attack (laser turret)'),AMS,launchers('Space',12),res('Major','Magazine',12),armor('Space',5),body('Huge',300),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',1),res('Major','Fuel',6),radio('Moderate'),laser('Moderate'),ansible(),res('Major','Tangle',6),computer('Major',4),hangar('Major'),ls('Major',3),mod('Gunnery',2),tag("At Arm's Length",3),tag('Security Alert',2),lim('Moderate','Crew Requirement (50 skeleton, 95 full)')],
 errata=["(new, 2026-09-26) p259: Armor Rating 5 (was 4); laser turret 7x (was 6x)."],
 power="6 Major; 5 used (laser, Anti-Missile, 12 Launchers = 3). OK.")
item("Redemption-class Frigate","Space: Military Starships",259,"Huge",10,55,[attack('Space',8,['Plasma'],2,'Attack (heavy plasma cannon)'),counter('Shields',True),bleed('Major',4,True),am('Space',2),launchers('Space',4),res('Major','Magazine',6),armor('Space',6),body('Huge',350),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',3),ps('Major','Fusion',2),res('Major','Fuel',7),radio('Moderate'),laser('Moderate'),ansible(),res('Major','Tangle',5),computer('Major',3),cargo('Major'),hangar('Major'),ls('Major'),mod('Detection',2),mod('Gunnery',2),tag('Security: High Alert',3),tag('All Ahead Full',3),tag('Pride of the Fleet',3),tag('The One-Two Punch',2),tag('Shohan Killer'),lim('Moderate','Crew Requirement (10 skeleton, 20 full)'),lim('Major','Restricted Technology (Property of the Terran Sphere Navy)')],
 errata=["(new, 2026-09-28) p259: 4 Launchers (Space), not 6; the ship is built around its plasma cannons. Total Power Slots: 9 Major (7 used), 3 Moderate (0 used).","(new, 2026-09-28) p259: Total Power Slots read 9 Major (8 used), 3 Moderate (0 used), not 9 Major (7 used)."],
 flags=["Differs from the Workbench design exercise (pp. 219–221): fuel here is Major (15/rank) where the exercise used Moderate (10/rank); the limitations are Crew + Restricted Technology here, 2 Moderate in the exercise. Both land on CR 10."],
 power="9 Major (Fusion ×2 + Gravitic Drive; 7 used: 2 Plasma ×2, 2 Anti-Missile, 4 Launchers = 1) + 3 Moderate (Reaction Drive; 0 used). OK.")
item("Retribution-class Frigate","Space: Military Starships",260,"Huge",10,55,[attack('Space',7,['Plasma'],label='Attack (heavy plasma cannon)'),counter('Shields',True),bleed('Major',3,True),AMS,launchers('Space',12),res('Major','Magazine',12),armor('Space',6),body('Huge',350),drive('Moderate','Reaction'),drive('Major','Gravitic'),maneuver('Major',3),ps('Major','Fusion'),res('Major','Fuel',7),radio('Moderate'),laser('Moderate'),ansible(),res('Major','Tangle',5),computer('Major',3),cargo('Moderate'),hangar('Major'),ls('Major'),mod('Detection',3),mod('Engineering (Starship)',1),mod('Gunnery',2),mod('Tactics',1),tag('Security: High Alert',3),tag('Flush the Tubes!',2),tag('Shohan Hunter'),lim('Moderate','Crew Requirement (20 skeleton, 100 full)')],
 errata=["(new, 2026-09-28) p260: Reaction Drive is Moderate, not Major, like its sister ship the Redemption. Total Power Slots read 6 Major (6 used), 3 Moderate (0 used).","(new, 2026-09-28) p260: \"Anti-Missile (Space) 2x\" reads Anti-Missile (Space) 1x (one mount). Total Power Slots read 9 Major (6 used), not 7 used."],
 power="6 Major (Fusion + Gravitic Drive; 6 used: Plasma 2, Anti-Missile 1, 12 Launchers = 3) + 3 Moderate (Reaction Drive; 0 used). OK.")
item("Marine LASCO (Launch, Support, and Command) Vessel","Space: Military Starships",261,"Huge",10,55,[AMS,launchers('Space',8),res('Major','Magazine',8),lim('Minor',UR+' (limited firing arc)'),armor('Space',6),body('Huge',350),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',2),res('Major','Fuel',10),radio('Moderate'),ansible(),res('Major','Tangle',5),computer('Major',4),cargo('Major',2),hangar('Major',4),ls('Major',5),mod('Detection',2),mod('Engineering (Starship)',1),mod('Gunnery',2),mod('Medicine',1),mod('Tactics',1),tag('High Security',3),tag('The Hammer of God',3),tag('Go to Rapid Fire',3),tag('Coordinated Fire',2),tag('Eye in the Sky'),lim('Moderate','Crew Requirement (20 skeleton, 40 full)'),lim('Moderate','Prerequisite (Property of the Terran Sphere)')],
 errata=["(new, 2026-09-27) p261: Fuel is 10 Major (100 days), not 13. Adds Limitation: Prerequisite [Property of the Terran Sphere] (Moderate). The 4 Major Hangars hold 3 Large craft each (4 crammed), so 12–16 Bridgehead Assault Shuttles."],
 flags=["The bombardment weaponry in the flavor text is the missile launchers; there is no separate bombardment Attack (confirmed against the build notes)."])
item("Fleet Auxiliary","Space: Military Starships",261,"Huge",9,45,[armor('Space',5),body('Huge',300),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',2),res('Major','Fuel',11),other('Bulk fuel stores','Carried as Cargo (below); see errata',0),link('Major','Refueling',3),radio('Moderate'),ansible(),res('Major','Tangle',5),computer('Major',3),manuf('Major'),cargo('Major',4),hangar('Major',3),ls('Major',3),mod('Detection',1),mod('Engineering (Starship)',3),tag('Rally and Resupply'),tag('High Security',3),tag('Mothership'),lim('Moderate','Crew Requirement (20 skeleton, 40 full)')],
 errata=["(new, 2026-09-28) p261: The ship's own Fuel is 11 Major (110 days), separate from the bulk fuel it carries as Cargo.","(new, 2026-09-25) p261: The printed \"300 Major Fuel\" is bulk fuel held as Cargo (enough to refuel three frigates), not the ship's own Fuel Resource. Pumping it from the storage tanks into a ship's systems takes an Engineering check."],
 power="6 Major (two Major drives); 4 used (3 Refueling Links, Manufacture 1). OK.")
item("Arniston (Unique Armed Merchantman)","Space: Military Starships",262,"Huge",9,45,[AMS,launchers('Space',8),res('Major','Magazine',8),armor('Space',6,True),body('Huge',300),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',1),res('Major','Fuel',6),lim('Minor',UR+' (no maneuver when shrouded)'),radio('Moderate'),ansible(),res('Major','Tangle',2),computer('Major',3),manuf('Major'),link('Major','Weapon'),cargo('Major'),hangar('Major'),ls('Major'),mod('Detection',2),mod('Gunnery',1),tag("She's Gone This Far…"),tag('Appearances Can Be Deceiving',2),tag('Go To Rapid Fire!',2),tag('High Security',3),lim('Moderate','Crew Requirement (20 skeleton, 40 full)'),lim('Moderate','Prerequisite ([Only One Woman Can Maintain the Old Girl])')],
 errata=["(new, 2026-09-28) p262: Fuel reads 6 Major Fuel (60 days/combat rounds), not 6 days.","p262: Power Slots 6 Major, 4 used (was missing); a weapon fitted to the Weapon Link draws a further slot.","(new, 2026-09-27) p262: Manufacture is Major (was Moderate). Adds a Major Weapon Link so the crew can fit a custom weapon besides the missiles. Detection +2 (was +1)."],
 power="6 Major; 4 used (Anti-Missile 1, 8 Launchers = 2, Manufacture 1), 5 with a weapon on the Link. OK.")
# ---------- Havenite
item("Havenite Lilith Carrier","Space: Free Haven",263,"Huge",10,55,[attack('Space',7,[],2,'Attack (heavy particle cannon)'),launchers('Space',4),res('Major','Magazine',4),AMS,armor('Space',5,True),body('Huge',300),drive('Major','Reaction'),drive('Major','Gravitic'),maneuver('Major',4),res('Major','Fuel',4),lim('Major','Unique Fuel (Antimatter)'),radio('Moderate'),ansible(),res('Major','Tangle',5),computer('Moderate',3),manuf('Major'),cargo('Major',2),hangar('Major',3),ls('Major',2),mod('Detection',4),mod('Engineering',3),mod('Gunnery',3),mod('Medicine',2),tag("Now You See Me, Now You Don't",2),tag('Go to Rapid Fire',2),tag('High Security',3),lim('Moderate','Crew Requirement (20 skeleton, 40 full)'),lim('Moderate','Key Personnel (Navigator)')],
 errata=["(new, 2026-09-27) p263: Heavy particle cannon is 7x (was 6x). Armor Rating 5 (was 3). Cargo 2 Major (was \"1 Huge\"; Cargo has no Huge grade). Adds Manufacture: Major. Unique Fuel (Antimatter) is a Major limitation. Power Slots 6 Major (from its two Major drives), 5 used."],
 notes=["Key Personnel (Navigator) is a Moderate limitation."],
 power="6 Major (two Major drives); 5 used (2 cannon mounts, 4 Launchers = 1, Anti-Missile 1, Manufacture 1). OK.")
item("Havenite Marauder","Space: Free Haven",263,"Large",6,21,[AMS,launchers('Space',8),res('Major','Magazine',6),armor('Space',4,True),body('Large',130),drive('Moderate','Reaction'),maneuver('Moderate',4),ps('Major','Antimatter'),res('Major','Fuel',3),lim('Major','Unique Fuel (Antimatter)'),radio('Moderate'),ansible(),res('Major','Tangle',2),computer('Moderate',3),ls('Moderate'),mod('Detection',2),mod('Gunnery',1),tag('Ambush!'),tag('Go to Rapid Fire',3),tag('Coordinated Fire',2),tag("Don't Get Too Comfortable"),lim('Moderate','Crew Requirement (2 skeleton, 5 full)')],
 errata=["(new, 2026-09-28) p263: 8 Launchers (Space), not 6 (launchers come in sets of 4; fits its heavy missile loadout).","(new, 2026-09-28) p263: Magazine reads 6 Major Magazine (60 shots), not 640 shots.","(new, 2026-09-27) p263: Rebuilt from the build notes. Armor Rating 4 (Shrouded Hull), not 5. Reaction Drive is Moderate, not Major; the Major Gravitic Drive is removed (the Marauder has no interstellar drive). Maneuver 4 now runs on the Moderate drive. Adds Power Supply: Major Antimatter, rank 1 (3 Major slots for the Anti-Missile and launchers). Unique Fuel (Antimatter) is a Major limitation. Intrusion Detection task removed."],
 flags=["With no interstellar drive, the Marauder relies on a carrier (the Lilith's Major Hangars) to travel between systems. The Ansible keeps it in touch with the carrier."],
 power="3 Major (Antimatter Power Supply) + 3 Moderate (Reaction Drive); 3 Major used (Anti-Missile 1, 8 Launchers = 2). OK.")
item("Havenite Lamprey","Space: Free Haven",264,"Large",5,15,[attack('Space',6,['Melee'],label='Attack (Energy Melee breacher)'),AMS,armor('Space',4),body('Large',70),drive('Major','Gravitic (modified in-system grav drive)'),lim('Minor',UR+' (Gravitic drive works in-system only; not FTL-capable)'),maneuver('Major',4),res('Major','Fuel',4),lim('Minor','Hungry (1 fuel/round in-system travel)'),radio('Moderate'),ansible(),res('Major','Tangle',1),computer('Moderate',3),hangar('Moderate',2),ls('Moderate',3),tag("Now You See Me, Now You Don't",2),tag('High Security',3),tag('Once More into the Breach'),tag('Stuck on You'),lim('Moderate','Crew Requirement (1 skeleton, 2 full)'),lim('Major','One-Time Use (boarding craft; must be reserviced after action)')],
 errata=["(new, 2026-09-28) p264: Fuel reads 4 Major Fuel (40 days/combat rounds), not 4 days.","(new, 2026-09-27) p264: The drive is a Major Gravitic drive modified for in-system use (like the Phantom's), not a Reactionless drive, with Limitation: Usage Restriction (in-system only; not FTL-capable), Minor. Adds Limitation: One-Time Use (Major); the boarding craft must be reserviced after action."],
 notes=["[Once More into the Breach]: after a successful breacher attack, the crew can move from the troop deck to the target ship. [Stuck on You]: on a successful Hard Maneuver check, the ship latches on."])
# ---------- Starship accessories
item("Heavy Railgun","Space: Starship Accessories",264,"Medium",3,6,[attack('Space',7,['Kinetic']),res('Major','Ammunition',4),body('Medium',50),lim('Minor','No Combat Reload'),lim('Moderate','Slave (Weapon Link)')],
 errata=["(new, 2026-09-28) p264: Adds Power Requirement: 1 Major slot (drawn from the host through its Weapon Link), like the Heavy Laser Cannon.","p264: Attack 7x (was 6x); Body 50 (was 10)."],
 power="Draws 1 Major slot from its host.")
item("Heavy Laser Cannon","Space: Starship Accessories",264,"Medium",4,10,[attack('Space',8,[]),body('Medium',50),lim('Moderate','Slave (Weapon Link)')],
 errata=["p264: Attack 8x (was 7x); Body 50 (was 10)."],power="Draws 1 Major slot from its host.")
item("Quad Missile Pack","Space: Starship Accessories",265,"Medium",2,3,[launchers('Space',4),res('Major','Magazine',8),lim('Minor','No Combat Reload'),lim('Moderate','Slave (Weapon Link)')],
 errata=["(new, 2026-09-28) p265: Magazine reads 8 Major Magazines (80 shots), not 2."],power="Draws 1 Major slot from its host (4 Launchers).")
# ---------- Programs (software: size from required rank)
def prog(name,rank,cr,cc,rows,flags=(),page=266,size=None,errata=(),notes=()):
    item(name,"Programs",page,size or ('Tiny' if rank==1 else 'Small'),cr,cc,rows,flags=flags,errata=errata,notes=notes,extra={'Required Computer Grade':{'Tiny':'Minor','Small':'Minor','Medium':'Minor','Large':'Moderate','Huge':'Moderate','Colossal':'Major'}[size or ('Tiny' if rank==1 else 'Small')]})
prog("Social Aggregator",2,2,3,[mod('Social Analysis (Persuade, Discern, Socialize)',3,3),tag('Always in the Know',2)],
 notes=["Multi-skill Modifiers are costed per skill: +3 across three skills = 90 BP."])
prog("Basic Security Software",1,0,0,[tasks([('Intrusion Detection',15)]),tag('Under Lock and Key',2)],size='Small',errata=["(new, 2026-09-27) p266: A Small item (per the build notes); requires a Minor computer."])
prog("Security Software",2,1,1,[tasks([('Intrusion Detection',20)]),tag('Under a Watchful Eye'),tag('This Is A Private Conversation',2,free=True),tag('I See You',2,free=True)],errata=["(new, 2026-09-27) p266: Adds the Free Tags [This Is A Private Conversation 2] and [I See You 2]."])
prog("Traceback",2,1,1,[tasks([('Trace',18)])],page=266,size='Tiny',errata=["(new, 2026-09-27) p266: A Tiny add-on module for a larger security suite."])
prog("Honey Pot",2,2,3,[tasks([('Compromise',18)]),tag('The Wages of Sin',2)],size='Tiny',errata=["(new, 2026-09-27) p266: A Tiny add-on module for a larger security suite. [The Wages of Sin] is rank 2."])
prog("Military-Grade Security",4,4,10,[tasks([('Intrusion Detection',20),('Trace',20)]),tag('I See You',3,free=True),tag('Like Fort Knox',3,free=True),tag('This Is A Private Conversation',2,free=True)],page=267,size='Small',errata=["(new, 2026-09-27) p267: Compromise task removed. [I See You 3] and [Like Fort Knox 3] are Free Tags (Like Fort Knox was rank 1), and it adds the Free Tag [This Is A Private Conversation 2]. Its TN 20 Tasks run at TN 20 only on a rank 4 or better computer."])
prog("Cover Identity",1,2,3,[tasks([('Spoof ID',15)]),mod('Credentials',1),tag("Not the Dude You're Looking For")],page=267,size='Tiny',errata=["(new, 2026-09-25) p267 (clarification): A Tiny item. The identity is stored on a chip (ident card, passport) and runs on whatever computer reads it to spoof that reader."])
prog("Good Cover Identity",2,4,10,[tasks([('Spoof ID',20)]),mod('Credentials',2),tag('Do You Know Who I Am?')],page=267,size='Tiny',
 errata=["(new, 2026-09-25) p267 (clarification): A Tiny item. The identity is stored on a chip (ident card, passport) and runs on whatever computer reads it to spoof that reader."],
 flags=["Tiny chip, Minor computer. Its Spoof ID 20 runs at 20 only on a rank 4 or better reader; lower-rank readers cap it at their max TN."])
# ---------- Shohan
item("Tse Blade","Shohan: Battlefield",268,"Small",4,10,[attack('Battlefield',5,['Tse','Melee'],label='Attack (Tse blade)'),counter('Armor',True),lim('Minor',UR+' (no area attacks against Firefight targets)'),attack('Firefight',5,['Flare'],label='Attack (flare gun)'),area(),counter('Armor'),lim('Minor',UR+' (cannot be fired more than once per round)'),ps('Moderate','Hyperspace Tap'),tag('Cut Through Anything',3),tag('Flexible Geometry Blade',1,True),tag('Where Did You Get Your Hands on One?'),lim('Moderate','Malfunction [Interested Parties], [Emergent Altered]')],
 errata=["p268: Attack multipliers 5x (was 4x).","(new, 2026-09-25) p216: Moderate Power Supplies are allowed on Small items, so the Hyperspace Tap is now legal.","(new, 2026-09-27) p268: [Flexible Geometry Blade] is a Free Tag. [Where Did You Get Your Hands on One?] is a standard Tag (it applies when a character outside the Shohan and Altered carries one). CR 4, CC 10 (was CR 5, CC 15)."],
 flags=["The no-area restriction is meaningful: a Battlefield-scale attack used against Firefight-scale targets counts as an area attack by default (scaling rule). The limitation removes that, so the blade hits one Firefight target.",
        "Printed CR/CC shown here are the errata values (the book printed CR 5, CC 15). They apply to Altered characters only (see chapter note)."],
 power="3 Moderate; 2 used (both attacks). OK.")
item("Shohan Personal Armor","Shohan: Battlefield",268,"Medium",5,15,[armor('Battlefield',4),body('Medium',45),regen('Moderate',4,'Biological'),ff('Minor',3),regen('Major',4,'Force Field'),ps('Moderate','Hyperspace Tap'),link('Moderate','Weapon',2),radio('Moderate'),computer('Minor',3),ls('Minor'),mod('Athletics',1),mod('Detection',2),mod('Weapons (Melee, Heavy Weapons)',2,2),lim('Minor',UR+' (Weapons +2 applies only to weapons on its Weapon Links)'),tag('The Armor Just Ate the Table'),lim('Moderate','Malfunction [Emergent Altered]'),lim('Major','Target On Your Back (visibly wearing enemy armor; not concealable)')],
 errata=["(new, 2026-09-29) p268: Weapons +2 covers two skills, Melee and Heavy Weapons (a Tse Blade combo), costed as a Moderate Modifier. Target On Your Back is a Major limitation, not Moderate: anyone wearing it is visibly in the other side's armor.","(new, 2026-09-28) p268: Body Track 45 (was 40).","(new, 2026-09-28) p268: Its 2 Weapon Links are Moderate. Its Weapons +2 Modifier works only with weapons on those Links (Usage Restriction, Minor). Computer is Minor rank 3 (was Moderate). Athletics +1 (was +2).","p268: Armor is Battlefield, not Firefight.","(new, 2026-09-27) p268: Regeneration grades are Biological 4 at Moderate (4 Body per scene) and Force Field 4 at Major (per round). [Emergent Altered] is a Moderate limitation (Malfunction), and the armor has a second Moderate limitation, Target On Your Back."],
 power="3 Moderate (Hyperspace Tap); 3 used (Force Field 1, a weapon on each Weapon Link 1 + 1). OK.")
item("War Drone (Cerberus)","Shohan: Battlefield",269,"Medium",None,None,[attack('Battlefield',5,['Flare'],2,'Attack (heavy flare gun)'),area(),counter('Armor'),attack('Battlefield',4,['Tse','Melee'],label='Attack (Tse claws)'),counter('Armor',True),lim('Minor',UR+' (no area attacks against Firefight targets)'),armor('Battlefield',5),body('Medium',80),regen('Moderate',5,'Biological'),ff('Minor',6),regen('Major',4,'Force Field'),ps('Moderate','Hyperspace Tap',2),computer('Moderate',4,'Brain'),tasks([('Athletics',17),('Combat',20),('Stealth',18),('Tactics',18)],True),tag('Seek And Destroy',3),tag('Faster than He Looks',2),tag('Unrelenting Pursuit')],
 errata=["(new, 2026-09-28) p269: Computer is a Moderate Brain rank 4 (20 target), not rank 3, to run its Combat 20 Task.","p269: Body 80, Armor 5 (was lower)."],
 flags=["Regeneration grade not given. Force Field Regeneration is Major (Shohan rule); Biological/Mechanical costed as Moderate."],
 notes=["No CR: not available for purchase."])
item("Shohan Deployment Pod","Shohan: Battlefield",269,"Large",None,None,[attack('Battlefield',4,['Flare'],3,'Attack (heavy flare gun)'),area(),counter('Armor'),armor('Space',4),body('Large',150),regen('Moderate',3,'Mechanical'),ff('Moderate',5),regen('Major',4,'Force Field'),drive('Moderate','Reactionless'),lim('Major','One-Time Use (drive)'),ps('Moderate','Hyperspace Tap',2),hypercomm(),hangar('Major'),tag("They're Here"),tag('Rapid Fire',3)],
 notes=["The Hangar is a Hyperspace Teleport Platform: it can bring down many Medium items from distant storage."])
item("Shohan Destroyer","Shohan: Spacecraft",270,"Huge",None,None,[attack('Space',7,['Flare'],4,'Attack (heavy flare cannon array)'),counter('Armor'),counter('Missiles'),armor('Space',6),body('Huge',250),regen('Moderate',1,'Mechanical'),ff('Major',3),regen('Major',6,'Force Field'),drive('Moderate','Reactionless'),drive('Major','Jump'),maneuver('Major',4),ps('Major','Hyperspace Tap',2),radio('Moderate'),hypercomm(),computer('Major',4),tasks([('Electronic Warfare',20),('Gunnery',20),('Piloting',20),('Tactics',18)]),tag('Go to Rapid Fire',3),tag('A Hawk Amongst Sparrows',3)],
 notes=["[Disoriented] comes with the Jump Drive; it isn't a bought Malfunction."],power="3 Moderate, 9 Major (Jump Drive's tap 3 + 2 taps 6). 7 Major used.")
item("Shohan Dreadnought","Shohan: Spacecraft",270,"Colossal",None,None,[attack('Space',13,['Hyperspace'],label='Attack (hyper cannon)'),other('Area','Small Sudden (free, Hyperspace)',0),counter('Armor',True),lim('Minor',UR+' (cannot be fired more than once per round)'),attack('Space',4,['Flare'],5,'Attack (heavy flare cannon array)'),counter('Armor'),counter('Missiles'),armor('Space',11),body('Colossal',500),ff('Major',5),regen('Major',10,'Force Field'),drive('Moderate','Reactionless'),drive('Major','Jump'),ps('Major','Hyperspace Tap',4),radio('Moderate'),hypercomm(),computer('Major',4),tasks([('Computer Subversion',20),('Gunnery',20),('Piloting',20),('Tactics',20)]),tag('Turret Fire',3),tag('An Ancient Doom',3),tag("You're Never Safe")],
 notes=["The hyper cannon's Counter: Armor and Area: Small Sudden come free with the Hyperspace implementation; they're printed so a GM or player can see what the cannon does without looking it up."])
# ---------- Resistance
item("Resistance Lumber Mech","Resistance Technology",271,"Medium",4,10,[armor('Battlefield',4),body('Medium',70),attack('Battlefield',5,['Melee'],label='Attack (modified chainsaw)'),counter('Armor'),drive('Minor','Ground'),maneuver('Minor',2),ps('Moderate','Coil'),res('Moderate','Charge',2),link('Minor','Weapon',2),mod('Detection',1),tag('Security',2),tag('Climbs Like A Monkey'),tag('Death From Above'),tag('Kinetic Feedback Control Rig',1,True),lim('Moderate','Partial Armor'),lim('Minor',UR+' (bulky form increases ground movement difficulty)')],
 errata=["(new, 2026-09-28) p271: Total Power Slots read 3 Minor (0 used), 3 Moderate (1 used), not 2 Minor.","(new, 2026-09-27) p271: Body Track 70 (was 80). The Coil Power Supply's \"2 Moderate Fuel\" should read 2 Moderate Charge. [Kinetic Feedback Control Rig] is a Free Tag (free Skill switch from Drive to Athletics)."],
 power="3 Minor (Ground Drive; 0 used) + 3 Moderate (Coil; 1 used). OK.",
 notes=["[Kinetic Feedback Control Rig]: switch from Drive to Athletics."])
item("Resistance Variable Laser Array","Resistance Technology",271,"Small",1,1,[attack('Battlefield',4,[]),counter('Shields'),counter('Armor'),ps('Moderate','Coil'),res('Moderate','Charge',1),mod('Heavy Weapons',1),lim('Moderate','Prerequisite (Hard Detection check to lock on; visual contact; Force Field targets may break the lock with a sustained Meditate check)')],
 errata=["(new, 2026-09-25) p216: Moderate Power Supplies are allowed on Small items, so this is now legal."],
 notes=["Alternate form SUIT-MOUNTED VLA: drop the Power Supply and Charge, draw 1 Moderate slot from the host, add Limitation: Slave (unit with a Weapon Link)."],power="3 Moderate; 1 used.")
