-- The database structure, generated by `php dev/dump-db.php`. Don't edit by hand:
-- change the database with a migration (db/migrations), then regenerate this file.
--
-- New database: run this, then db/seed.sql. An existing database only needs the
-- migrations it hasn't had yet. CREATE TABLE (no DROP) so it can't wipe a live database.

-- Tables are in name order, not dependency order.
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `attribute` (
  `AttributeID` int NOT NULL AUTO_INCREMENT,
  `AttributeName` varchar(255) DEFAULT NULL,
  `SpecializationsFlag` tinyint DEFAULT NULL,
  PRIMARY KEY (`AttributeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `attributescale` (
  `AttributeScaleID` int NOT NULL AUTO_INCREMENT,
  `AttributeID` int NOT NULL,
  `ScaleType` set('MINOR','MODERATE','MAJOR') NOT NULL,
  `AttributeCost` int NOT NULL,
  `AttributeFormula` varchar(255) DEFAULT NULL,
  `PowerSlots` int DEFAULT NULL,
  PRIMARY KEY (`AttributeScaleID`),
  KEY `AttributeID` (`AttributeID`),
  CONSTRAINT `attributescale_ibfk_1` FOREIGN KEY (`AttributeID`) REFERENCES `attribute` (`AttributeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `attributespecialization` (
  `AttributeSpecializationID` int NOT NULL AUTO_INCREMENT,
  `AttributeScaleID` int NOT NULL,
  `SpecializationName` varchar(255) NOT NULL,
  `AttributeCost` int DEFAULT NULL,
  `AttributeFormula` int DEFAULT NULL,
  `PowerSlots` int DEFAULT NULL,
  PRIMARY KEY (`AttributeSpecializationID`),
  KEY `AttributeScaleID` (`AttributeScaleID`),
  CONSTRAINT `attributespecialization_ibfk_1` FOREIGN KEY (`AttributeScaleID`) REFERENCES `attributescale` (`AttributeScaleID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `item` (
  `ItemID` varchar(50) NOT NULL,
  `ItemName` varchar(200) DEFAULT NULL,
  `ItemSize` int DEFAULT NULL,
  `ItemTypeID` int DEFAULT NULL,
  `CostRating` int DEFAULT NULL,
  `IsPublic` tinyint DEFAULT '0',
  PRIMARY KEY (`ItemID`),
  KEY `item_itemtype_fk` (`ItemTypeID`),
  CONSTRAINT `item_itemtype_fk` FOREIGN KEY (`ItemTypeID`) REFERENCES `itemtype` (`ItemTypeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemattribute` (
  `ItemAttributeID` int NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `ParentAttributeID` int DEFAULT NULL,
  `AttributeID` int DEFAULT NULL,
  `AttributeScaleID` int DEFAULT NULL,
  `Rank` int DEFAULT NULL,
  `Implementation` varchar(50) DEFAULT NULL,
  `BuildPoints` int DEFAULT NULL,
  `PowerSlots` int DEFAULT NULL,
  `System` varchar(200) DEFAULT NULL,
  `SortOrder` int DEFAULT NULL,
  PRIMARY KEY (`ItemAttributeID`,`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemlimit` (
  `LimitID` int NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `LimitDesc` varchar(200) DEFAULT NULL,
  `LimitScale` int DEFAULT NULL,
  `BuildPoints` int DEFAULT NULL,
  `itemlimitcol` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LimitID`,`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemmodifier` (
  `ModifierID` int NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `ModifierName` varchar(100) DEFAULT NULL,
  `SkillID` int DEFAULT NULL,
  PRIMARY KEY (`ModifierID`,`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemsize` (
  `ItemSizeID` int NOT NULL AUTO_INCREMENT,
  `SizeName` varchar(255) NOT NULL,
  `BasePoints` int DEFAULT NULL,
  `IncrementPoints` int DEFAULT NULL,
  `BaseCR` int DEFAULT NULL,
  `BaseBody` int DEFAULT NULL,
  PRIMARY KEY (`ItemSizeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemtag` (
  `TagID` int NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `TagDesc` varchar(200) DEFAULT NULL,
  `TagRank` int DEFAULT NULL,
  `TagFree` bit(1) DEFAULT NULL,
  `BuildPoints` int DEFAULT NULL,
  PRIMARY KEY (`TagID`,`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemtask` (
  `TaskID` int NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `TaskName` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`TaskID`,`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `itemtype` (
  `ItemTypeID` int NOT NULL AUTO_INCREMENT,
  `ItemTypeName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ItemTypeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `limitationtype` (
  `LimitationTypeID` int NOT NULL AUTO_INCREMENT,
  `LimitationName` set('MINOR','MODERATE','MAJOR') NOT NULL,
  `LimitationCost` int NOT NULL,
  PRIMARY KEY (`LimitationTypeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `skills` (
  `skillID` int NOT NULL AUTO_INCREMENT,
  `skillName` varchar(100) NOT NULL,
  PRIMARY KEY (`skillID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
