-- Redemption errata: structured data for MySQL 8
-- Generated 2026-09-27 from `Redemption Errata.txt` (project doc). Keep the two in sync:
-- the text file is the human-readable version; this script is the loadable version.
--
-- Tables
--   errata         One row per errata entry (one line of the text file).
--     ErrataID       Position in book order. Renumbered when entries are added, so always
--                    reload the whole script; don't reference these IDs from other tables.
--     Section        Combat | Item Creation | Gear | Psionics
--     PageStart      Book page (PageEnd is set only for ranges, e.g. 226-271).
--     Subject        Rule or item the entry is about (human label).
--     ErrataType     rule | stat | clarification | replacement | typo
--                    (replacement = the whole stat block is replaced; see ErrataText)
--     ErrataText     The full errata wording, as published.
--     AddedOn        NULL for the original errata; the date for entries added since.
--   errata_change  Zero or more machine-readable changes per entry.
--     ItemName       Exact item name in docs/equipment_catalog.md, or NULL for rule changes.
--     FieldName, OldValue, NewValue   What changed. Values are display text, not numbers.
--
-- Reloadable: drops and recreates both tables. Table names are lowercase (MySQL on Linux
-- is case-sensitive), matching the rest of the schema.

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `errata_change`;
DROP TABLE IF EXISTS `errata`;

CREATE TABLE `errata` (
  `ErrataID`   INT          NOT NULL,
  `Section`    VARCHAR(32)  NOT NULL,
  `PageStart`  SMALLINT     NOT NULL,
  `PageEnd`    SMALLINT     NULL,
  `Subject`    VARCHAR(128) NOT NULL,
  `ErrataType` VARCHAR(16)  NOT NULL,
  `ErrataText` TEXT         NOT NULL,
  `AddedOn`    DATE         NULL,
  PRIMARY KEY (`ErrataID`),
  KEY `ix_errata_page` (`PageStart`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `errata_change` (
  `ErrataChangeID` INT          NOT NULL,
  `ErrataID`       INT          NOT NULL,
  `ItemName`       VARCHAR(128) NULL,
  `FieldName`      VARCHAR(96)  NOT NULL,
  `OldValue`       VARCHAR(255) NULL,
  `NewValue`       VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ErrataChangeID`),
  KEY `ix_errata_change_item` (`ItemName`),
  CONSTRAINT `fk_errata_change_errata` FOREIGN KEY (`ErrataID`) REFERENCES `errata` (`ErrataID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `errata` (`ErrataID`, `Section`, `PageStart`, `PageEnd`, `Subject`, `ErrataType`, `ErrataText`, `AddedOn`) VALUES
(1, 'Combat', 183, NULL, 'Plasma Attacks', 'rule', 'Plasma Weapon Attacks should be +2 Multiplier versus shields, not "Double Damage" as described here. This brings it in line with the description for Counter: Shields on P212.', NULL),
(2, 'Combat', 183, NULL, 'Terran psionic Force Fields', 'rule', 'Terran Sphere psionics using force fields circumvent the restriction on Psionic effects by having a gap in their force field''s protection. This means that their force fields may be bypassed by aimed or area attacks that happen while they are using their powers. Normally this vulnerability only lasts for the Psionics turn, leaving them vulnerable to sustained attacks, but ongoing effects require the gap to remain open and exploitable.', NULL),
(3, 'Combat', 185, NULL, 'Armor reduction duration', 'rule', 'Armor Reduction from Coordinated Fire or from attacks with Counter: Armor persists until the end of the round, allowing subsequent players to take advantage of the target''s weakened state.', NULL),
(4, 'Combat', 191, NULL, 'Battle Strain: missile salvos', 'rule', 'Battle strain can be spent on a 1 to 1 basis to increase the number of missiles in a salvo. This can not be used in conjunction with the Coordinated fire effect.', NULL),
(5, 'Combat', 191, NULL, 'Battle Strain: Tags and extra actions', 'rule', 'Using Battle Strain to Activate Tags or Perform Extra Actions with a unit does not fall under the single Battle Strain expenditure per round rule. Additional extra actions after the first cost increasing multiples of 3 Battle Strain (6, 9, etc...) as per the extra actions for AP rule.', NULL),
(6, 'Combat', 191, NULL, 'Attached characters: skill switch', 'rule', 'A character attached to a unit may use Tags and their personal AP to skill switch from the unit''s target number on to their corresponding skill.', NULL),
(7, 'Combat', 194, NULL, 'Missile attacks vs margin of defense', 'rule', 'Missile attacks reduce their targets'' total margin of defense by the number of attacking missiles in the salvo not -1 per salvo launched at the target. This reduction is not restricted to their bonus margin of defense from anti missile fire.', NULL),
(8, 'Item Creation', 209, 212, 'Software: required computer', 'rule', 'Software no longer requires a computer rank by size. Instead, program size sets the computer grade it needs. Tiny, Small, and Medium programs need a Minor computer, carry 1 or 2 Tasks, and serve a single user. Large and Huge programs need a Moderate computer, carry multiple Tasks, and serve dozens of users at once. Colossal programs need a Major computer and serve hundreds of users at once. Computer rank no longer limits program size; it only caps Task target numbers. A Task runs at its own TN or the computer rank''s maximum TN, whichever is lower. Replace every "Required Computer Rank" in program stat blocks with the matching Required Computer Grade.', '2026-09-27'),
(9, 'Item Creation', 210, NULL, 'Attack: turrets', 'rule', 'Omission of Turret rules from Attack attribute - Spending the base cost for an attack multiple times allows additional gunners to make attacks with the weapon, or the same gunner assuming he spends the action points. The Ships of the Line design exercise starting on page 219 provides an example of these rules in action.', NULL),
(10, 'Item Creation', 210, NULL, 'Attack: Melee', 'rule', 'Melee attacks can never gain the Area attribute.', NULL),
(11, 'Item Creation', 210, NULL, 'Attack: rail weapon power', 'rule', 'Rail (Kinetic Ranged) weapons integrated into an item (ship and vehicle weapons, and units slaved to a host such as suit-mounted or Weapon Link weapons) draw a Power Slot like any other Attack, in addition to their Ammunition. Standalone rail weapons (hand weapons such as gauss pistols and rifles) need no Power Supply: the power is built into the casing of each round, and this is already included in their Ammunition.', '2026-09-28'),
(12, 'Item Creation', 210, NULL, 'Attack: Hyperspace implementation', 'clarification', 'The Hyperspace implementation (the Shohan Dreadnought''s hyper cannon, the only such attack in the game) includes Counter: Armor and Area: Small Sudden at no extra cost. Both are printed in the cannon''s stat block so its effects can be read without looking up the implementation.', '2026-09-28'),
(13, 'Item Creation', 211, NULL, 'Attack: Plasma Bleed', 'rule', 'A Plasma Attack''s free Bleed (half its Weapon Multiplier, at the grade matching the Attack''s scale) can be increased. Additional Bleed damage costs the difference between the full Bleed cost and the free Bleed.', '2026-09-27'),
(14, 'Item Creation', 211, NULL, 'Attack: self-powered Plasma', 'rule', 'Plasma has a self-powered implementation for hand weapons. Instead of drawing 2 Power Slots per mount, it needs special ammunition (an Ammunition Resource). That requirement is built into the implementation as a Moderate limitation: it takes one of the two Moderate limitation slots but refunds no Build Points. Plasma weapons built into or slaved to a host still draw 2 Power Slots per mount, with or without ammunition. Kinetic (rail) weapons split the same way (p210): Kinetic draws a Power Slot plus Ammunition, Kinetic (self-powered) uses Ammunition only.', '2026-09-29'),
(15, 'Item Creation', 212, NULL, 'Counter: Armor', 'rule', 'Counter Armor no longer can bypass non-partial armor on an aimed attack. Instead on an unaimed attack it will reduce armor by 1. Aimed attacks will grant an additional 1 armor reduction for the attack, bringing the aimed attack to -2 armor. However, the armor reduction contributed to other attacks remains at -1 armor.', NULL),
(16, 'Item Creation', 212, 215, 'Drugs: Strain and Duration', 'rule', 'Counter: Strain raises or lowers Psionic Strain by 5 per Counter (20 BP each). Regeneration: Strain restores Psionic Strain like other Regeneration implementations. A drug''s Duration is bought as a Resource (1 Minor rank ≈ 10 combat rounds or 1 hour; 1 Moderate rank ≈ 1 day).', '2026-09-28'),
(17, 'Item Creation', 213, NULL, 'Drive: Reactionless', 'rule', 'Reactionless drives should not expel Reaction Mass.', NULL),
(18, 'Item Creation', 214, NULL, 'Hangar: capacity', 'rule', 'Hangar: "multiple items" means 3 items, or 4 if crammed in. For example, a Major Hangar on a Huge ship holds 3 Large craft (4 crammed), and a Moderate Hangar holds 3 items two sizes smaller (4 crammed).', '2026-09-27'),
(19, 'Item Creation', 214, NULL, 'Launcher: sets of 4', 'rule', 'Launchers are bought in sets of 4 (one set draws 1 Power Slot and costs 4 × the per-launcher price: 20 / 40 / 60 BP). Ships printing launcher counts that are not multiples of 4 are corrected by errata (Standard Assault Shuttle, Dragon, Conventional Frigate, Redemption, Havenite Marauder). A Magazine does not have to match the launcher count.', '2026-09-28'),
(20, 'Item Creation', 215, NULL, 'Link: Refueling', 'rule', 'Add a Link type, Refueling: a docking connection that transfers fuel to a linked craft of up to the Link''s maximum size. Each Refueling Link draws 1 Power Slot of its grade while in use. (The Fleet Auxiliary''s three Major Refueling Links account for 3 of its 4 used Power Slots.)', '2026-09-28'),
(21, 'Item Creation', 216, NULL, 'Power Supply: minimum item size', 'rule', 'A Moderate Power Supply may be installed on a Small item (the table lists Medium). Major Power Supplies still require a Large item, except that the compact Hyperspace Tap and Coil implementations can squeeze a Major Power Supply into a Medium item.', '2026-09-25'),
(22, 'Item Creation', 217, NULL, 'Resource: Fuel grade', 'rule', 'A Fuel Resource can feed Drives and Power Supplies of its own grade or lower. A larger fuel tank can feed a smaller drive (for example, Major Fuel can feed a Moderate Reaction Drive), but never the reverse.', '2026-09-25'),
(23, 'Item Creation', 217, NULL, 'Regeneration: Force Field', 'rule', 'Shohan Force Field Regeneration is always Major grade (regenerates every round).', '2026-09-27'),
(24, 'Item Creation', 217, 218, 'Limitations: examples', 'clarification', 'Key Personnel (the item needs a specific crew member, such as a Navigator) is a Moderate limitation. A Modifier covering several skills is costed per skill (10 BP × rank × number of skills). A Minor Reaction Drive is a jet pack that works on a planet or in microgravity.', '2026-09-28'),
(25, 'Item Creation', 217, 218, 'Modifier: skill breadth', 'rule', 'The grade of a Modifier is how many skills it covers: Minor for one skill (10 BP per rank), Moderate for two (20 BP per rank), and Major for three or more, or a whole class of skills such as "Weapons" or "Technical Skills" (30 BP per rank). This replaces costing multi-skill Modifiers per skill. The +4 limit per skill still applies; how a class Modifier stacks with others is left to the table.', '2026-09-29'),
(26, 'Gear', 225, NULL, 'Quick Reference table', 'typo', 'Update the Quick Reference table to match the errata: Standard Light Armor CR 0, CC 0; Psionic Light Armor CR 0, CC 0; Flight Pack CR 0, CC 0; Personal Psi Link CR 1, CC 1; Stealth FTL Recon Drone CR 6, CC 21; Factory Freighter CR 9, CC 45; Tse Blade CR 4, CC 10. Replace the Programs "Min" column (minimum computer rank) with the required computer grade: Minor for all eight programs.', '2026-09-28'),
(27, 'Gear', 226, 271, 'Firearms skill name', 'clarification', 'Equipment Modifiers listed for "Sidearms" should read "Firearms". Sidearms is an earlier name for the personal weapon skill.', '2026-09-26'),
(28, 'Gear', 226, 271, 'Multiplier printing error', 'clarification', 'Several stat blocks printed an Armor or Attack Multiplier rank as the final value, leaving out the base rank, so the printed Armor Rating or Weapon Multiplier is one step too low. The affected items are corrected individually below.', '2026-09-26'),
(29, 'Gear', 226, NULL, 'Psionic Light Armor', 'stat', 'Psionic Light Armor''s fuel should read 10 Days/Combat turns instead of "1 Day".', NULL),
(30, 'Gear', 226, NULL, 'Camouflage Suit', 'stat', 'The Camouflage Suit''s Armor Rating is 4 (Firefight), not 3.', '2026-09-26'),
(31, 'Gear', 226, NULL, 'Standard Light Armor', 'stat', 'Standard Light Armor''s Cost Rating is 0, not 2 (its CC is already 0).', '2026-09-27'),
(32, 'Gear', 226, NULL, 'Psionic Light Armor', 'stat', 'Psionic Light Armor''s Cost Rating is 0 and its Character Creation cost is 0 (was CR 1, CC 1). Its stats are unchanged.', '2026-09-27'),
(33, 'Gear', 226, NULL, 'Stealth Suit', 'stat', 'The Stealth Suit is a Small item, not Medium; it can be worn under street clothing.', '2026-09-27'),
(34, 'Gear', 227, NULL, 'Riot/LEO Armor, Psi Variant', 'stat', 'Riot/LEO Armor, Psi Variant, fuel should also be 10 Days/Combat turns.', NULL),
(35, 'Gear', 227, NULL, 'Standard Powered Armor', 'stat', 'Standard Powered Armor possesses Battlefield, not Firefight level armor.', NULL),
(36, 'Gear', 227, NULL, 'Riot/LEO Armor', 'stat', 'Riot/LEO Armor is a Small item, not Medium, and its Armor Rating is 4 (Firefight), not 3.', '2026-09-27'),
(37, 'Gear', 227, NULL, 'Riot/LEO Armor, Psi Variant', 'stat', 'Riot/LEO Armor, Psi Variant is a Small item, not Medium. It has Life Support: Minor (the rebreather its limitation refers to), gains the Tag [Mental Block], and its Strain Threshold is 10, not 5.', '2026-09-27'),
(38, 'Gear', 228, NULL, 'Kavacha Powered Armor', 'stat', 'Kavacha Powered Armor possesses Battlefield, not Firefight level armor. This applies to both the A-350 Marine Engagement Suit and the A-350SR Marine Reconnaissance Suit.', NULL),
(39, 'Gear', 229, NULL, 'Knife', 'stat', 'The Knife gains Limitation: Usage Restriction (Firefight targets only; useless against Battlefield or hull armor), Minor.', '2026-09-27'),
(40, 'Gear', 229, NULL, 'Flight Pack', 'stat', 'The Flight Pack gains Modifier: Pilot +2. [Turn Your Head to Steer] is a Free Tag and [A Leap of Faith] is rank 3. Its Usage Restriction is a Moderate limitation. Its Cost Rating is 0 and its Character Creation cost is 0 (was CR 1, CC 1).', '2026-09-27'),
(41, 'Gear', 229, NULL, 'Bolt-on Thruster Pack', 'stat', 'The Bolt-on Thruster Pack gains Modifier: Pilot +2 and Life Support: Minor (extending suit operations in space). Its fuel is 3 Moderate Fuel, not Minor.', '2026-09-27'),
(42, 'Gear', 230, NULL, 'Quality Gauss Pistol', 'stat', 'The Quality Gauss Pistol''s attack increases to 3x from 2x.', '2026-09-26'),
(43, 'Gear', 230, NULL, 'Heavy Gauss Pistol', 'stat', 'The Heavy Gauss Pistol''s single-target attack increases to 3x from 2x. The burst fire mode remains 2x.', '2026-09-26'),
(44, 'Gear', 230, NULL, 'Concealable Pistol', 'stat', 'The Concealable Pistol''s attack increases to 3x from 2x, it gains Modifier: Firearms +2, and its ammunition increases to 4 Minor Ammunition (40 shots) from 3 (30 shots).', '2026-09-26'),
(45, 'Gear', 231, NULL, 'Wellpoint Armory Stormguard 9MP', 'stat', 'Wellpoint Armory Stormguard 9MP ammo now costs CR 1 instead of "3x".', NULL),
(46, 'Gear', 231, NULL, 'Security Gauss Rifle', 'stat', 'The Security Gauss Rifle''s single-target attack increases to 4x from 3x. The burst fire mode remains 3x.', '2026-09-26'),
(47, 'Gear', 232, NULL, 'Plasma Carbine', 'stat', 'The Plasma Carbine has the following changes: Weapon multiplier increases to 4x from 3x, Ammo cost is CR 1, not 5x, and it loses the Area attack attribute, to be replaced with Counter: Armor.', NULL),
(48, 'Gear', 232, NULL, 'Sniper Rifle', 'stat', 'The Sniper Rifle''s attack increases to 5x from 4x.', '2026-09-26'),
(49, 'Gear', 232, NULL, 'Plasma Carbine', 'stat', 'The Plasma Carbine''s attack increases to 5x from 4x. Its Bleed is 4 (Minor): 2 free from the Plasma implementation plus 2 bought.', '2026-09-27'),
(50, 'Gear', 232, NULL, 'Plasma Carbine: Upkeep', 'typo', 'Delete "Upkeep: 1" from the Plasma Carbine. Upkeep, a recurring maintenance cost, was phased out of the rules; this listing is a leftover.', '2026-09-28'),
(51, 'Gear', 232, NULL, 'Plasma Carbine: self-powered', 'stat', 'The Plasma Carbine''s attack is self-powered Plasma. Its special ammunition requirement is built into that implementation, replacing the separate Prerequisite (special ammunition) limitation, and its Bleed is 3 (Minor): 2 free from Plasma plus 1 bought. Cost Rating unchanged (2).', '2026-09-29'),
(52, 'Gear', 233, NULL, 'Explosive Grenade', 'stat', 'The Explosive Grenade''s attack increases to 6x from 5x.', '2026-09-26'),
(53, 'Gear', 233, NULL, 'Tactical Railgun', 'stat', 'The Tactical Railgun is a Small item, not Medium. Its Hungry limitation is a Moderate limitation. Its attack remains 4x.', '2026-09-26'),
(54, 'Gear', 233, NULL, 'Tactical Missile Rack', 'stat', 'The Tactical Missile Rack gains Limitation: Slave (Moderate). It is a module mounted on and powered by a host unit.', '2026-09-27'),
(55, 'Gear', 234, NULL, 'Light Plasma Cannon', 'stat', 'Light Plasma cannon ammo now costs CR 1.', NULL),
(56, 'Gear', 234, NULL, 'Light Plasma Cannon', 'stat', 'The Light Plasma Cannon''s attack increases to 5x from 4x. Its Bleed is 4 (Moderate): 2 free from the Plasma implementation plus 2 bought.', '2026-09-27'),
(57, 'Gear', 235, NULL, 'Personal Psi Link', 'stat', 'Personal Psi Link should read Moderate instead of Major Power Supply. Strain should be 10 not 25 - This is the most important change on the list, as starting Psionics were more powerful than intended as a result.', NULL),
(58, 'Gear', 235, NULL, 'Carry Comp', 'stat', 'The Carry Comp''s computer is rank 4 (20 target, 5 tasks), not rank 3.', '2026-09-27'),
(59, 'Gear', 235, NULL, 'Personal Psi Link', 'stat', 'The Personal Psi Link carries 2 Moderate Charge (20 days or 20 combat rounds), not 1. Its Cost Rating is 1 and its Character Creation cost is 1 (was CR 2, CC 3); the printed price matched its original Major Power Supply.', '2026-09-27'),
(60, 'Gear', 235, NULL, 'Coil Stack Battery/Charger', 'stat', 'The Coil Stack Battery/Charger is Small, not Tiny (a Moderate Power Supply needs a Small item), and holds 2 Moderate Charge, not 1. CR 0, CC 0 (unchanged).', '2026-09-28'),
(61, 'Gear', 236, NULL, 'Personal G3P', 'stat', 'The Personal G3P''s [Hobbyist Builder''s Best Friend] Tag is rank 3.', '2026-09-27'),
(62, 'Gear', 237, NULL, 'Advanced Neural Interface Control Link', 'stat', 'The Advanced Neural Interface Control Link''s [Dance Along the Bleeding Edge, But You Might Get Cut] is a Major Limitation, not a Tag: hacking that breaches the user''s defenses can inflict physical damage.', '2026-09-25'),
(63, 'Gear', 237, NULL, 'Basic Neural Interface Control Link', 'stat', 'The Basic Neural Interface Control Link''s Initiative Modifier is +1, not +2.', '2026-09-27'),
(64, 'Gear', 237, NULL, 'Reflex Enhancements', 'stat', 'Reflex Enhancements gain the Tag [Need For Speed].', '2026-09-27'),
(65, 'Gear', 237, NULL, 'Advanced Neural Interface Control Link', 'stat', 'The Advanced NICL''s Initiative Modifier is +2, not +3; its Major Neural Interface already gives +3 Initiative when operating linked equipment, and the Modifier is the general bonus. [Dance Along the Bleeding Edge, But You Might Get Cut] splits in two: the Tag [Dance Along The Bleeding Edge 2] and the Major limitation [...But You Might Get Cut 2] (hacking that breaches the user''s defenses can inflict physical damage). CR 1, CC 4 (unchanged).', '2026-09-28'),
(66, 'Gear', 237, NULL, 'Basic Neural Interface Control Link', 'stat', 'The Basic Neural Interface Control Link''s Technical-class Skills +1 is a Major Modifier, since it covers a class of skills. Its Usage Restriction (skill modifiers only apply to linked gear) is Moderate, not Minor. Its Cost Rating is 1 (was 0).', '2026-09-29'),
(67, 'Gear', 237, NULL, 'Advanced Neural Interface Control Link', 'stat', 'The Advanced Neural Interface Control Link''s Technical-class Skills +1 is a Major Modifier, since it covers a class of skills. Its Usage Restriction (skill modifiers only apply to linked gear) is Moderate, not Minor. Its Cost Rating is 2 (was 1).', '2026-09-29'),
(68, 'Gear', 238, NULL, 'Psi Amp', 'stat', 'The Psionic Strain on Psi Amps reduced from +25 to +10.', NULL),
(69, 'Gear', 238, NULL, 'Telekinetic Shuttle', 'stat', 'The Telekinetic Shuttle now has a Major Psi Link.', NULL),
(70, 'Gear', 238, NULL, 'Psi Amp', 'stat', 'The Psi Amp is rebuilt. Its initial hit is +5 Psionic Strain (Counter: Strain, 1 rank), followed by Regeneration: Strain 5 (Major, every round) for its Duration of 10 combat rounds (1 Minor Resource rank). [Euphoria] is a Minor limitation. This supersedes the earlier +10 Strain erratum. CR 1, CC 1 (unchanged).', '2026-09-28'),
(71, 'Gear', 238, NULL, 'Psi Damp', 'stat', 'The Psi Damp is costed as Counter: Strain, 5 ranks (−25 Psionic Strain), with a Duration of 1 day (1 Moderate Resource rank). [It Itches In My Brain] becomes [It Itches In My Brain 3], a Moderate limitation. CR 1, CC 1 (unchanged).', '2026-09-28'),
(72, 'Gear', 239, NULL, '"Fluffy"', 'stat', '"Fluffy" has Armor Rating 3 (Firefight), not 2.', '2026-09-26'),
(73, 'Gear', 239, NULL, 'Creatures: Drive', 'stat', '"Fluffy" and the Monster in the Dark gain Drive: Minor Land (legs), which carries their Maneuver 1.', '2026-09-28'),
(74, 'Gear', 240, NULL, 'Family Transport', 'stat', 'The Family Transport''s fuel is 2 Minor Fuel (20 days/combat rounds), not 5, and its Drive Task is 15, not 16.', '2026-09-27'),
(75, 'Gear', 240, NULL, 'Colonial Personal Transport (Hoverbike)', 'stat', 'The Colonial Personal Transport (Hoverbike) has Armor Rating 2 (Firefight), not 1. Replace "Cover: Moderate (Partial)" with Limitation: Partial Armor (Moderate); an aimed shot bypasses its armor.', '2026-09-28'),
(76, 'Gear', 241, NULL, 'Speedster', 'stat', 'The Speedster gains Modifier: Drive +2 and the Free Tag [...And Turns A Few Heads 3].', '2026-09-27'),
(77, 'Gear', 242, NULL, 'Light Performance Aircraft', 'stat', 'The Light Performance Aircraft has Armor Rating 2 (Firefight), not 1.', '2026-09-26'),
(78, 'Gear', 242, NULL, 'Light Air Transport', 'stat', 'The Light Air Transport gains Task: Intrusion Detection 17.', '2026-09-27'),
(79, 'Gear', 242, NULL, 'Light Performance Aircraft: life support', 'stat', 'The Light Performance Aircraft has Life Support: 3 Minor (3 people), not 1 Moderate (12 people); it is a 2–3 seat craft.', '2026-09-28'),
(80, 'Gear', 243, NULL, 'Cargo Transport', 'stat', 'The Cargo Transport''s Tag is [Security 2], not [Security].', '2026-09-27'),
(81, 'Gear', 243, NULL, 'Armored Cargo Transport: Body Track', 'stat', 'The Armored Cargo Transport''s Body Track is 90, not 80 (80 isn''t a whole Large increment; 90 costs the same).', '2026-09-28'),
(82, 'Gear', 243, NULL, 'Armored Cargo Transport: computer', 'stat', 'The Armored Cargo Transport''s computer is Minor rank 4 (20 target, 5 tasks), not rank 3, so it can run its Intrusion Detection 20 Task.', '2026-09-28'),
(83, 'Gear', 244, NULL, 'Air Transport', 'stat', 'The Air Transport has Armor Rating 2 (Battlefield), not 1, and Maneuver 2, not 1. Its cargo is 3 Major, not 3 Moderate, and it gains Life Support: Moderate (12 passengers). Its computer is rank 3 (18 target, 5 tasks), not rank 2, and it gains Task: Intrusion Detection 17.', '2026-09-27'),
(84, 'Gear', 244, NULL, 'Air Transport: Body Track', 'stat', 'The Air Transport''s Body Track is 90, not 80 (80 isn''t a whole Large increment; 90 costs the same).', '2026-09-28'),
(85, 'Gear', 244, NULL, 'Assault Platform: Body Track', 'stat', 'The Assault Platform''s Body Track is 90, not 80 (80 isn''t a whole Large increment; 90 costs the same).', '2026-09-28'),
(86, 'Gear', 245, NULL, 'Attack Hovercraft', 'stat', 'The Attack Hovercraft''s heavy railgun single-target attack increases to 5x from 4x. The burst fire mode remains 4x.', '2026-09-26'),
(87, 'Gear', 245, NULL, 'Armored Personnel Carrier', 'stat', 'The Armored Personnel Carrier has Armor Rating 4 (Battlefield), not 3. Its heavy gauss gun''s single-target attack increases to 5x from 4x; the burst fire mode remains 4x. Its troop bay is a Major Hangar, not Minor.', '2026-09-26'),
(88, 'Gear', 245, NULL, 'Armored Personnel Carrier: power', 'stat', 'The Armored Personnel Carrier''s Power Supply is Moderate Fusion rank 2, not rank 1, so its 2 Weapon Links have power for linked weapons. Its Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).', '2026-09-28'),
(89, 'Gear', 245, NULL, 'Attack Hovercraft: power', 'stat', 'The Attack Hovercraft''s Power Supply is Moderate Fusion rank 2, not rank 1, so its 3 Weapon Links have power for linked weapons. Its Total Power Slots read 3 Minor (0 used), 6 Moderate (2 used).', '2026-09-28'),
(90, 'Gear', 245, NULL, 'Attack Hovercraft: Body Track', 'stat', 'The Attack Hovercraft''s Body Track is 90, not 80 (80 isn''t a whole Large increment; 90 costs the same).', '2026-09-28'),
(91, 'Gear', 245, NULL, 'Armored Personnel Carrier: Body Track', 'stat', 'The Armored Personnel Carrier''s Body Track is 90, not 80 (80 isn''t a whole Large increment; 90 costs the same).', '2026-09-28'),
(92, 'Gear', 246, NULL, 'Autonomous Kill Vehicle', 'stat', 'The Autonomous Kill Vehicle''s light particle beam increases to 5x from 4x. It gains a Major Coil Power Supply (rank 1) with 1 Major Charge (10 combat rounds) to power the beam. Its Maneuver drops to 3 from 5. Its "ineffective at Far Range" restriction becomes a Moderate Limitation: No Far Range. Total Power Slots: 3 Moderate (0 used), 3 Major (1 used).', '2026-09-26'),
(93, 'Gear', 246, NULL, 'Recon Drone', 'stat', 'The Recon Drone''s Maneuver is 4, not 5 (the maximum is 4). Its computer is Minor rank 3 (18 target, 5 tasks), not rank 2, so it can run its Piloting 18 Task.', '2026-09-28'),
(94, 'Gear', 247, NULL, 'Stealth FTL Recon Drone', 'replacement', 'The Stealth FTL Recon Drone''s stat block is replaced. The original build left out the cost of its Shrouded Hull. Corrected stats: Size Medium, CR 6, CC 21. Armor Rating 1 (Space, Shrouded); Body Track 10. Drives: Moderate Reaction, Major Gravitic, Maneuver 2; Resource: 2 Major Fuel (shared by both Drives). Communications: Major (Ansible; Resource: 1 Major Tangle). Computer: Minor 4 (20 target, 5 tasks); Tasks: Piloting 17, Detection 19, Intrusion Detection 15. Tags: [Security 2], [I Spy with my Little Eye...]. Limitations: One Track Mind (Moderate; follows its programmed route), One-Time Use (Major; each drone is burned out by its run and requires an extended Engineering roll to be brought back into service). Total Power Slots: 3 Moderate (0 used), 3 Major (0 used).', '2026-09-25'),
(95, 'Gear', 248, NULL, 'Telekinetic Shuttle: Charge', 'typo', 'The Telekinetic Shuttle''s Coil Power Supply runs on 2 Major Charge, not 2 Major Fuel.', '2026-09-28'),
(96, 'Gear', 249, NULL, 'Shuttle/Yacht', 'stat', 'The Shuttle/Yacht gains Task: Pilot 17 and the Free Tag [The Grand Tour 3]. Its Tangle is 2 ranks (20 days), not 1.', '2026-09-27'),
(97, 'Gear', 250, NULL, 'Locust Mobile Industrial Platform', 'stat', 'The Locust Mobile Industrial Platform has Armor Rating 2 (Space), not 1, and a Body Track of 250, not 200. It has Maneuver 1.', '2026-09-27'),
(98, 'Gear', 250, NULL, 'Locust: power slots', 'typo', 'The Locust Mobile Industrial Platform''s Total Power Slots read 6 Major (3 used); the grade was missing.', '2026-09-28'),
(99, 'Gear', 251, NULL, 'Factory Freighter', 'stat', 'The Factory Freighter''s Reaction Drive is Moderate, not Major. It has 2 Major Hangars, not 3, and 5 Major Life Support (500 people), not 6. Its computer is Major rank 3 (18 target); delete "5 tasks", since a Major computer runs unlimited tasks. Its CR is 9 and CC 45, not CR 8 and CC 36. Total Power Slots: 3 Major and 3 Moderate, 3 Major used.', '2026-09-27'),
(100, 'Gear', 252, NULL, 'Security Escort/Corsair: power slots', 'typo', 'The Security Escort/Corsair''s Total Power Slots read 6 Major (2 used), 3 Moderate (0 used), not 9 Major (4 used). Weapons fitted to its Weapon Links draw further slots.', '2026-09-28'),
(101, 'Gear', 252, NULL, 'Standard Assault Shuttle: launchers', 'stat', 'The Standard Assault Shuttle carries 4 Launchers (Space), not 2.', '2026-09-28'),
(102, 'Gear', 252, NULL, 'Standard Assault Shuttle: radio', 'stat', 'The Standard Assault Shuttle gains Communications: Moderate (Radio).', '2026-09-28'),
(103, 'Gear', 253, NULL, 'Tanker/Command Ship', 'stat', 'The Tanker/Command Ship''s 100 ranks of Major Fuel are bulk fuel stores carried as Cargo, not the ship''s own Fuel Resource. Pumping fuel from the storage tanks into a ship''s systems requires an Engineering check.', '2026-09-25'),
(104, 'Gear', 253, NULL, 'Tanker/Command Ship', 'stat', 'The Tanker/Command Ship has Armor Rating 4 (Space), not 3.', '2026-09-26'),
(105, 'Gear', 253, NULL, 'Tanker/Command Ship: own fuel', 'stat', 'The Tanker/Command Ship''s own Fuel Resource is 10 Major (100 days/combat rounds), separate from the bulk fuel it carries as Cargo.', '2026-09-28'),
(106, 'Gear', 253, NULL, 'System Defense Craft: alternate forms', 'clarification', 'In the System Defense Craft''s alternate forms, "missile array" means its 4 Launchers and "particle cannon" means its heavy railgun (the name from an earlier draft). The Strike Craft removes the 4 Launchers; the Torpedo Boat removes the heavy railgun.', '2026-09-28'),
(107, 'Gear', 254, NULL, 'Dragon-class Fleet Interceptor/Escort', 'stat', 'The Dragon-class Fleet Interceptor/Escort is missing the auxiliary Major Fusion Power Supply described in its design notes. Its Power Slots become 6 Moderate and 3 Major.', '2026-09-25'),
(108, 'Gear', 254, NULL, 'Dragon-class Fleet Interceptor/Escort', 'stat', 'The Dragon-class Fleet Interceptor/Escort''s Air Drive is Minor, not Moderate; its drives are a Moderate in-system Reaction Drive and a Minor Air Drive. It carries 8 Launchers (Space), not 6.', '2026-09-28'),
(109, 'Gear', 254, NULL, 'Dragon-class Fleet Interceptor/Escort: fuel', 'stat', 'The Dragon-class Fleet Interceptor/Escort carries 2 Major Fuel (20 days/combat rounds), not 2 Moderate, so it can run its Major Fusion reactor as well as its drives.', '2026-09-28'),
(110, 'Gear', 255, NULL, 'Bridgehead Assault Shuttle', 'stat', 'The Bridgehead Assault Shuttle has Armor Rating 4 (Space), not 3, and its rapid plasma cannon increases to 5x from 4x.', '2026-09-26'),
(111, 'Gear', 255, NULL, 'Phantom DRIV', 'stat', 'The Phantom DRIV possesses a Moderate Laser Link.', NULL),
(112, 'Gear', 255, NULL, 'Bridgehead Assault Shuttle: Bleed', 'stat', 'The Bridgehead Assault Shuttle''s rapid plasma cannon has Bleed: Major 2 (its free Plasma Bleed, half of 5x rounded down), not Major 3. Its Total Power Slots read 3 Moderate (1 used), 3 Major (3 used).', '2026-09-28'),
(113, 'Gear', 256, NULL, 'Standard Cruiser: power', 'stat', 'The Standard Cruiser gains Power Supply: Major Fusion, rank 1, to power its integrated railgun turrets. Its Total Power Slots read 6 Major (4 used), 3 Moderate (0 used), not 3 Major (2 used).', '2026-09-28'),
(114, 'Gear', 256, NULL, 'Standard Cruiser: computer', 'stat', 'The Standard Cruiser gains Computer: Major 3 (18 target, unlimited tasks), matching the Redemption and Retribution.', '2026-09-28'),
(115, 'Gear', 258, NULL, 'Standard (Conventional) Frigate', 'stat', 'Skeleton Crew of Standard Frigate up to 100, from 10, Full Complement to 200, from 20.', NULL),
(116, 'Gear', 258, NULL, 'Conventional Frigate: launchers', 'stat', 'The Conventional Frigate carries 8 Launchers (Space), not 6.', '2026-09-28'),
(117, 'Gear', 259, NULL, 'Resolute-class Frigate', 'stat', 'The Resolute-class Frigate has Armor Rating 5 (Space), not 4, and its laser turret increases to 7x from 6x.', '2026-09-26'),
(118, 'Gear', 259, NULL, 'Redemption-class Frigate: launchers and power', 'stat', 'The Redemption-class Frigate carries 4 Launchers (Space), not 6; the ship is built around its plasma cannons. Its Total Power Slots read 9 Major (7 used), 3 Moderate (0 used), not 9 Major (7 used) with no Moderate listed.', '2026-09-28'),
(119, 'Gear', 260, NULL, 'Retribution-class Frigate: Anti-Missile', 'typo', 'The Retribution-class Frigate''s "Anti-Missile (Space) 2x" reads "Anti-Missile (Space) 1x"; it has one Anti-Missile mount. Its Total Power Slots read 9 Major (6 used), not 7 used.', '2026-09-28'),
(120, 'Gear', 260, NULL, 'Retribution-class Frigate: drive', 'stat', 'The Retribution-class Frigate''s Reaction Drive is Moderate, not Major, like its sister ship the Redemption. Its Total Power Slots read 6 Major (6 used), 3 Moderate (0 used).', '2026-09-28'),
(121, 'Gear', 261, NULL, 'Fleet Auxiliary', 'stat', 'The Fleet Auxiliary''s 300 ranks of Major Fuel are bulk fuel stores carried as Cargo, not the ship''s own Fuel Resource. Pumping fuel from the storage tanks into a ship''s systems requires an Engineering check.', '2026-09-25'),
(122, 'Gear', 261, NULL, 'Marine LASCO Vessel', 'stat', 'The Marine LASCO Vessel carries 10 Major Fuel (100 days), not 13. It gains the Limitation Prerequisite: [Property of the Terran Sphere] (Moderate). Each of its 4 Major Hangars holds 3 Large craft (4 if crammed), so it launches 12 to 16 Bridgehead Assault Shuttles.', '2026-09-27'),
(123, 'Gear', 261, NULL, 'Fleet Auxiliary: own fuel', 'stat', 'The Fleet Auxiliary''s own Fuel Resource is 11 Major (110 days/combat rounds), separate from the bulk fuel it carries as Cargo.', '2026-09-28'),
(124, 'Gear', 262, NULL, 'Arniston', 'stat', 'The Arniston is missing its Power Slots listing: 6 Major, 3 Used.', NULL),
(125, 'Gear', 262, NULL, 'Arniston', 'stat', 'The Arniston''s Manufacture is Major, not Moderate, and it gains a Major Weapon Link so the crew can fit a custom weapon besides the missiles. Its Detection is +2, not +1. It uses 4 of its 6 Major Power Slots, not 3; a weapon fitted to the Link draws another.', '2026-09-27'),
(126, 'Gear', 262, NULL, 'Arniston: fuel endurance', 'typo', 'The Arniston''s fuel reads "6 Major Fuel (60 days/combat rounds)", not 6 days.', '2026-09-28'),
(127, 'Gear', 263, NULL, 'Lilith Carrier', 'stat', 'The Havenite Lilith Carrier''s heavy particle cannons are 7x, not 6x. Its Armor Rating is 5 (Space, Shrouded Hull), not 3. Its cargo is 2 Major, not 1 Huge (Cargo has no Huge grade). It gains Manufacture: Major, and its Unique Fuel (Antimatter) limitation is Major. Total Power Slots: 6 Major, 5 used.', '2026-09-27'),
(128, 'Gear', 263, NULL, 'Havenite Marauder', 'stat', 'The Havenite Marauder has Armor Rating 4 (Space, Shrouded Hull), not 5. Its Reaction Drive is Moderate, not Major, and it has no Gravitic Drive; it relies on a carrier to travel between systems. It gains Power Supply: Major Antimatter, rank 1, which powers its Anti-Missile and launchers. Its Unique Fuel (Antimatter) limitation is Major. Remove its Intrusion Detection task. Total Power Slots: 3 Major and 3 Moderate, 3 Major used.', '2026-09-27'),
(129, 'Gear', 263, NULL, 'Havenite Marauder: magazine', 'typo', 'The Havenite Marauder''s magazine reads "6 Major Magazine (60 shots)", not 640 shots.', '2026-09-28'),
(130, 'Gear', 263, NULL, 'Havenite Marauder: launchers', 'stat', 'The Havenite Marauder carries 8 Launchers (Space), not 6, to fit its heavy missile loadout.', '2026-09-28'),
(131, 'Gear', 264, NULL, 'Heavy Railgun', 'stat', 'Heavy Railgun - Attack increases from 6 to 7, body to 50.', NULL),
(132, 'Gear', 264, NULL, 'Heavy Laser Cannon', 'stat', 'Heavy Laser Cannon - Attack increases from 7 to 8, body to 50.', NULL),
(133, 'Gear', 264, NULL, 'Havenite Lamprey', 'stat', 'The Havenite Lamprey''s drive is a Major Gravitic Drive modified for in-system use (like the Phantom''s), not a Reactionless drive. It gains the Limitations Usage Restriction: in-system only, not FTL-capable (Minor), and One-Time Use (Major); the boarding craft must be reserviced after each action.', '2026-09-27'),
(134, 'Gear', 264, NULL, 'Havenite Lamprey: fuel endurance', 'typo', 'The Havenite Lamprey''s fuel reads "4 Major Fuel (40 days/combat rounds)", not 4 days.', '2026-09-28'),
(135, 'Gear', 264, NULL, 'Heavy Railgun: power', 'stat', 'The Heavy Railgun gains Power Requirement: 1 Major slot, drawn from its host through the Weapon Link (like the Heavy Laser Cannon).', '2026-09-28'),
(136, 'Gear', 265, NULL, 'Quad Missile Pack: magazine', 'typo', 'The Quad Missile Pack''s magazine reads "8 Major Magazines (80 shots)", not 2 Major Magazines.', '2026-09-28'),
(137, 'Gear', 266, NULL, 'Security programs: sizes', 'clarification', 'Basic Security Software and Security Software are Small items. Traceback and Honey Pot are Tiny add-on modules for a larger security suite.', '2026-09-27'),
(138, 'Gear', 266, NULL, 'Security Software', 'stat', 'Security Software gains the Free Tags [This Is A Private Conversation 2] and [I See You 2].', '2026-09-27'),
(139, 'Gear', 266, NULL, 'Honey Pot', 'stat', 'Honey Pot''s [The Wages of Sin] Tag is rank 2.', '2026-09-27'),
(140, 'Gear', 267, NULL, 'Cover Identity programs', 'clarification', 'Cover Identity and Good Cover Identity are Tiny items. The identity is stored on a chip (such as an ident card or passport) and runs on whatever computer reads the chip, spoofing that reader. The reader needs a Minor computer or better; its Tasks run at the lower of their own TN and the reader''s max TN.', '2026-09-25'),
(141, 'Gear', 267, NULL, 'Military-Grade Security', 'stat', 'Military-Grade Security loses its Compromise Task. [I See You 3] and [Like Fort Knox 3] are Free Tags ([Like Fort Knox] was rank 1), and it gains the Free Tag [This Is A Private Conversation 2].', '2026-09-27'),
(142, 'Gear', 268, NULL, 'Tse Blade', 'stat', 'Tse Blade attack multipliers increase to 5x.', NULL),
(143, 'Gear', 268, NULL, 'Shohan Personal Armor', 'stat', 'Shohan Personal Armor possesses Battlefield, not Firefight level armor.', NULL),
(144, 'Gear', 268, NULL, 'Tse Blade', 'stat', 'The Tse Blade''s [Flexible Geometry Blade] is a Free Tag. [Where Did You Get Your Hands on One?] is a standard Tag (it applies when a character who is neither Shohan nor Altered carries one). Its Cost Rating is 4 and its Character Creation cost is 10 (was CR 5, CC 15).', '2026-09-27'),
(145, 'Gear', 268, NULL, 'Shohan Personal Armor', 'stat', 'Shohan Personal Armor''s Regeneration grades are Biological 4 at Moderate (4 Body per scene) and Force Field 4 at Major (every round). [Emergent Altered] is a Moderate limitation (Malfunction), and the armor has a second Moderate limitation, Target On Your Back.', '2026-09-27'),
(146, 'Gear', 268, NULL, 'Shohan Personal Armor', 'stat', 'The Shohan Personal Armor''s 2 Weapon Links are Moderate. Its Weapons +2 Modifier works only with weapons fitted to those Links (Limitation: Usage Restriction, Minor). Its Computer is Minor rank 3 (18 target), not Moderate, its Athletics Modifier is +1, not +2, and its Body Track is 45, not 40. Total Power Slots: 3 Moderate, 3 used (Force Field and one weapon on each Link).', '2026-09-28'),
(147, 'Gear', 268, NULL, 'Shohan Personal Armor', 'stat', 'The Shohan Personal Armor''s Weapons +2 Modifier covers two skills, Melee and Heavy Weapons (pairing with a Tse Blade), and is costed as a Moderate Modifier. Target On Your Back is a Major limitation, not Moderate: the armor can''t be concealed, and anyone wearing it is visibly in the other side''s armor. Cost Rating unchanged (5).', '2026-09-29'),
(148, 'Gear', 269, NULL, 'War Drone (Cerberus)', 'stat', 'Shohan War Drone''s Body increases to 80, armor increases to 5.', NULL),
(149, 'Gear', 269, NULL, 'War Drone (Cerberus): computer', 'stat', 'The War Drone (Cerberus)''s Brain is Moderate rank 4 (20 target), not rank 3, so it can run its Combat 20 Task.', '2026-09-28'),
(150, 'Gear', 271, NULL, 'Resistance Lumber Mech', 'stat', 'The Resistance Lumber Mech''s Body Track is 70, not 80. Its Coil Power Supply uses 2 Moderate Charge, not Fuel. [Kinetic Feedback Control Rig] is a Free Tag (free Skill switch from Drive to Athletics).', '2026-09-27'),
(151, 'Gear', 271, NULL, 'Resistance Lumber Mech: power slots', 'typo', 'The Resistance Lumber Mech''s Total Power Slots read 3 Minor (0 used), 3 Moderate (1 used), not 2 Minor.', '2026-09-28'),
(152, 'Psionics', 278, NULL, 'Astral Projection', 'rule', 'Astral Projection costs 1 strain per round or scene that the character maintains the projection.', NULL),
(153, 'Psionics', 285, NULL, 'Necromancy: sacrificing attunements', 'rule', 'Necromantic attunements may be sacrificed to gain strain at 10 points for every rank of the attunement.', NULL),
(154, 'Psionics', 285, NULL, 'Necromancy: shunting damage', 'rule', 'Necromancers may shunt damage to their strain track at a 1 to 1 ratio, previously this was 3 strain for every point of damage.', NULL);

INSERT INTO `errata_change` (`ErrataChangeID`, `ErrataID`, `ItemName`, `FieldName`, `OldValue`, `NewValue`) VALUES
(1, 1, NULL, 'Effect against Force Fields', 'Double Damage', '+2 Weapon Multiplier'),
(2, 7, NULL, 'Margin of defense reduction', '-1 per salvo', '-1 per missile in the salvo'),
(3, 8, NULL, 'Software requirement', 'Required Computer Rank (by size)', 'Required Computer Grade (by size)'),
(4, 8, NULL, 'Task TN on a lower-rank computer', 'not allowed', 'runs at the computer rank''s max TN'),
(5, 11, NULL, 'Rail weapon power', 'unclear', 'integrated/slaved: Power Slot + Ammunition; standalone: self-powered rounds'),
(6, 12, NULL, 'Hyperspace free features', 'Counter: Armor', 'Counter: Armor, Area: Small Sudden'),
(7, 13, NULL, 'Plasma Bleed above the free amount', 'not addressed', 'Costs the difference between full Bleed cost and the free Bleed'),
(8, 14, NULL, 'Plasma implementations', 'Plasma', 'Plasma (2 Power Slots per mount); Plasma (self-powered) (special ammunition, built-in Moderate limitation)'),
(9, 14, NULL, 'Kinetic implementations', 'Kinetic', 'Kinetic (Power Slot + Ammunition); Kinetic (self-powered) (Ammunition only)'),
(10, 15, NULL, 'Armor reduction', '-2, or ignore armor on an aimed attack', '-1 unaimed; -2 aimed; -1 carries to other attacks'),
(11, 16, NULL, 'Counter implementations', 'Armor, Shields, Disabling, Strike', 'adds Strain (±5 Psionic Strain per Counter)'),
(12, 16, NULL, 'Regeneration implementations', 'Biological, Force Field, Mechanical', 'adds Strain'),
(13, 16, NULL, 'Drug Duration', 'undefined', 'Resource'),
(14, 17, NULL, 'Reaction mass', 'Expels reaction mass', 'Does not expel reaction mass'),
(15, 18, NULL, 'Hangar capacity', 'multiple items', '3 items (4 crammed)'),
(16, 19, NULL, 'Launcher purchase', 'per launcher', 'sets of 4'),
(17, 20, NULL, 'Link types', 'Data, Psi, Weapon', 'adds Refueling (draws 1 Power Slot)'),
(18, 21, NULL, 'Minimum size: Moderate', 'Medium', 'Small'),
(19, 21, NULL, 'Minimum size: Major (Hyperspace Tap or Coil)', 'Large', 'Medium'),
(20, 22, NULL, 'Fuel grade', 'Same grade as the Drive/Power Supply', 'Same grade or higher'),
(21, 23, NULL, 'Force Field Regeneration grade', 'not specified', 'Major'),
(22, 24, NULL, 'Key Personnel', 'unlisted', 'Moderate limitation'),
(23, 24, NULL, 'Multi-skill Modifier cost', 'unclear', 'per skill'),
(24, 24, NULL, 'Minor Reaction Drive', 'unlisted', 'jet pack (planet or microgravity)'),
(25, 25, NULL, 'Multi-skill Modifier cost', 'per skill', 'by breadth: Minor 1 skill (10/rank), Moderate 2 (20/rank), Major 3+ or a class (30/rank)'),
(26, 26, 'Standard Light Armor', 'Quick Reference CR/CC', '2 / 0', '0 / 0'),
(27, 26, 'Psionic Light Armor', 'Quick Reference CR/CC', '1 / 1', '0 / 0'),
(28, 26, 'Flight Pack', 'Quick Reference CR/CC', '1 / 1', '0 / 0'),
(29, 26, 'Personal Psi Link', 'Quick Reference CR/CC', '2 / 3', '1 / 1'),
(30, 26, 'Stealth FTL Recon Drone', 'Quick Reference CR/CC', '5 / 15', '6 / 21'),
(31, 26, 'Factory Freighter', 'Quick Reference CR/CC', '8 / 36', '9 / 45'),
(32, 26, 'Tse Blade', 'Quick Reference CR/CC', '5 / 15', '4 / 10'),
(33, 26, NULL, 'Quick Reference: Programs column', 'Min (computer rank)', 'Computer grade (Minor)'),
(34, 27, NULL, 'Modifier skill', 'Sidearms', 'Firearms'),
(35, 29, 'Psionic Light Armor', 'Charge duration', '1 day', '10 days / combat turns'),
(36, 30, 'Camouflage Suit', 'Armor Rating', '3 (Firefight)', '4 (Firefight)'),
(37, 31, 'Standard Light Armor', 'CR', '2', '0'),
(38, 32, 'Psionic Light Armor', 'CR', '1', '0'),
(39, 32, 'Psionic Light Armor', 'CC', '1', '0'),
(40, 33, 'Stealth Suit', 'Size', 'Medium', 'Small'),
(41, 34, 'Riot/LEO Armor, Psi Variant', 'Charge duration', '1 day', '10 days / combat turns'),
(42, 35, 'Standard Powered Armor', 'Armor scale', 'Firefight', 'Battlefield'),
(43, 36, 'Riot/LEO Armor', 'Size', 'Medium', 'Small'),
(44, 36, 'Riot/LEO Armor', 'Armor Rating', '3 (Firefight)', '4 (Firefight)'),
(45, 37, 'Riot/LEO Armor, Psi Variant', 'Size', 'Medium', 'Small'),
(46, 37, 'Riot/LEO Armor, Psi Variant', 'Life Support', 'none', 'Minor (1 person)'),
(47, 37, 'Riot/LEO Armor, Psi Variant', 'Tag', 'none', '[Mental Block]'),
(48, 37, 'Riot/LEO Armor, Psi Variant', 'Strain Threshold', '5', '10'),
(49, 38, 'Kavacha-class A-350 Marine Engagement Suit', 'Armor scale', 'Firefight', 'Battlefield'),
(50, 38, 'Kavacha-class A-350SR Marine Reconnaissance Suit', 'Armor scale', 'Firefight', 'Battlefield'),
(51, 39, 'Knife', 'Limitation', 'none', 'Usage Restriction (Firefight targets only), Minor'),
(52, 40, 'Flight Pack', 'Modifier', 'none', 'Pilot +2'),
(53, 40, 'Flight Pack', 'Tag type: [Turn Your Head to Steer]', 'Standard', 'Free'),
(54, 40, 'Flight Pack', 'Tag rank: [A Leap of Faith]', '1', '3'),
(55, 40, 'Flight Pack', 'Limitation grade: Usage Restriction', 'Minor', 'Moderate'),
(56, 40, 'Flight Pack', 'CR', '1', '0'),
(57, 40, 'Flight Pack', 'CC', '1', '0'),
(58, 41, 'Bolt-on Thruster Pack', 'Modifier', 'none', 'Pilot +2'),
(59, 41, 'Bolt-on Thruster Pack', 'Life Support', 'none', 'Minor (1 person)'),
(60, 41, 'Bolt-on Thruster Pack', 'Fuel', '3 Minor', '3 Moderate'),
(61, 42, 'Quality Gauss Pistol', 'Weapon Multiplier', '2x', '3x'),
(62, 43, 'Heavy Gauss Pistol', 'Weapon Multiplier (single target)', '2x', '3x'),
(63, 44, 'Concealable Pistol', 'Weapon Multiplier', '2x', '3x'),
(64, 44, 'Concealable Pistol', 'Modifier', 'none', 'Firearms +2'),
(65, 44, 'Concealable Pistol', 'Ammunition', '3 Minor (30 shots)', '4 Minor (40 shots)'),
(66, 45, 'Wellpoint Armory Stormguard 9MP', 'Ammunition cost', '3x', 'CR 1'),
(67, 46, 'Security Gauss Rifle', 'Weapon Multiplier (single target)', '3x', '4x'),
(68, 47, 'Plasma Carbine', 'Weapon Multiplier', '3x', '4x'),
(69, 47, 'Plasma Carbine', 'Ammunition cost', '5x', 'CR 1'),
(70, 47, 'Plasma Carbine', 'Area', 'Small Sudden', 'none'),
(71, 47, 'Plasma Carbine', 'Counter', 'none', 'Armor'),
(72, 48, 'Sniper Rifle', 'Weapon Multiplier', '4x', '5x'),
(73, 49, 'Plasma Carbine', 'Weapon Multiplier', '4x', '5x'),
(74, 49, 'Plasma Carbine', 'Bleed', 'Moderate 2', 'Minor 4 (2 free + 2 bought)'),
(75, 50, 'Plasma Carbine', 'Upkeep', '1', 'none'),
(76, 51, 'Plasma Carbine', 'Attack implementation', 'Plasma', 'Plasma (self-powered)'),
(77, 51, 'Plasma Carbine', 'Limitation', 'Moderate: Prerequisite (special ammunition)', 'none (built into Plasma (self-powered))'),
(78, 51, 'Plasma Carbine', 'Bleed', 'Minor 4 (2 free + 2 bought)', 'Minor 3 (2 free + 1 bought)'),
(79, 52, 'Explosive Grenade', 'Weapon Multiplier', '5x', '6x'),
(80, 53, 'Tactical Railgun', 'Size', 'Medium', 'Small'),
(81, 53, 'Tactical Railgun', 'Limitation grade: Hungry', 'Minor', 'Moderate'),
(82, 54, 'Tactical Missile Rack', 'Limitation', 'none', 'Slave (host unit), Moderate'),
(83, 55, 'Light Plasma Cannon', 'Ammunition cost', '5x', 'CR 1'),
(84, 56, 'Light Plasma Cannon', 'Weapon Multiplier', '4x', '5x'),
(85, 56, 'Light Plasma Cannon', 'Bleed', 'Major 2', 'Moderate 4 (2 free + 2 bought)'),
(86, 57, 'Personal Psi Link', 'Power Supply', 'Major Coil', 'Moderate Coil'),
(87, 57, 'Personal Psi Link', 'Strain Threshold', '25', '10'),
(88, 58, 'Carry Comp', 'Computer', 'Minor 3 (18 target)', 'Minor 4 (20 target)'),
(89, 59, 'Personal Psi Link', 'Charge', '1 Moderate', '2 Moderate'),
(90, 59, 'Personal Psi Link', 'CR', '2', '1'),
(91, 59, 'Personal Psi Link', 'CC', '3', '1'),
(92, 60, 'Coil Stack Battery/Recharger', 'Size', 'Tiny', 'Small'),
(93, 60, 'Coil Stack Battery/Recharger', 'Charge', '1 Moderate', '2 Moderate'),
(94, 61, 'Personal G3P', 'Tag rank: [Hobbyist Builder''s Best Friend]', '1', '3'),
(95, 62, 'Advanced Neural Interface Control Link', '[Dance Along the Bleeding Edge, But You Might Get Cut]', 'Tag', 'Major Limitation'),
(96, 63, 'Basic Neural Interface Control Link (NICL)', 'Modifier: Initiative', '+2', '+1'),
(97, 64, 'Reflex Enhancements', 'Tag', 'none', '[Need For Speed]'),
(98, 65, 'Advanced Neural Interface Control Link', 'Modifier', 'Initiative +3', 'Initiative +2'),
(99, 65, 'Advanced Neural Interface Control Link', 'Tag', 'none', '[Dance Along The Bleeding Edge 2]'),
(100, 65, 'Advanced Neural Interface Control Link', 'Limitation', '[Dance Along the Bleeding Edge, But You Might Get Cut] (Major)', '[...But You Might Get Cut 2] (Major)'),
(101, 66, 'Basic Neural Interface Control Link (NICL)', 'Modifier grade: Technical-class Skills', 'Minor', 'Major'),
(102, 66, 'Basic Neural Interface Control Link (NICL)', 'Limitation grade: Usage Restriction', 'Minor', 'Moderate'),
(103, 66, 'Basic Neural Interface Control Link (NICL)', 'CR', '0', '1'),
(104, 67, 'Advanced Neural Interface Control Link', 'Modifier grade: Technical-class Skills', 'Minor', 'Major'),
(105, 67, 'Advanced Neural Interface Control Link', 'Limitation grade: Usage Restriction', 'Minor', 'Moderate'),
(106, 67, 'Advanced Neural Interface Control Link', 'CR', '1', '2'),
(107, 68, 'Psi Amp', 'Psionic Strain', '+25', '+10'),
(108, 69, 'Telekinetic Shuttle', 'Link', 'none', 'Major Psi'),
(109, 70, 'Psi Amp', 'Psionic Strain', '+10', '+5 initial (Counter: Strain, 1 rank)'),
(110, 70, 'Psi Amp', 'Regeneration', 'none', 'Strain 5, Major (every round)'),
(111, 70, 'Psi Amp', 'Duration', '10 combat rounds or 1 hour', '1 Minor Resource rank (10 combat rounds)'),
(112, 70, 'Psi Amp', 'Limitation', '[Euphoria] (Drawback Tag)', '[Euphoria] (Minor)'),
(113, 71, 'Psi Damp', 'Psionic Strain', '−25', '−25 (Counter: Strain, 5 ranks)'),
(114, 71, 'Psi Damp', 'Duration', '1 day', '1 Moderate Resource rank (1 day)'),
(115, 71, 'Psi Damp', 'Limitation', '[It Itches in My Brain] (Drawback Tag)', '[It Itches In My Brain 3] (Moderate)'),
(116, 72, '“Fluffy”', 'Armor Rating', '2 (Firefight)', '3 (Firefight)'),
(117, 73, '“Fluffy”', 'Drive', 'none', 'Minor Land (legs)'),
(118, 73, 'Monster in the Dark', 'Drive', 'none', 'Minor Land (legs)'),
(119, 74, 'Family Transport', 'Fuel', '5 Minor', '2 Minor'),
(120, 74, 'Family Transport', 'Task: Drive', '16', '15'),
(121, 75, 'Colonial Personal Transport (Hoverbike)', 'Armor Rating', '1 (Firefight)', '2 (Firefight)'),
(122, 75, 'Colonial Personal Transport (Hoverbike)', 'Cover', 'Moderate (Partial)', 'none'),
(123, 75, 'Colonial Personal Transport (Hoverbike)', 'Limitation', 'none', 'Partial Armor (Moderate)'),
(124, 76, 'Speedster', 'Modifier', 'none', 'Drive +2'),
(125, 76, 'Speedster', 'Tag', 'none', '[...And Turns A Few Heads 3] (Free)'),
(126, 77, 'Light Performance Aircraft', 'Armor Rating', '1 (Firefight)', '2 (Firefight)'),
(127, 78, 'Light Air Transport', 'Tasks', 'Autopilot 20', 'Autopilot 20, Intrusion Detection 17'),
(128, 79, 'Light Performance Aircraft', 'Life Support', 'Moderate (12 people)', '3 Minor (3 people)'),
(129, 80, 'Cargo Transport', 'Tag rank: [Security]', '1', '2'),
(130, 81, 'Armored Cargo Transport', 'Body Track', '80', '90'),
(131, 82, 'Armored Cargo Transport', 'Computer', 'Minor 3 (18 target)', 'Minor 4 (20 target)'),
(132, 83, 'Air Transport', 'Armor Rating', '1 (Battlefield)', '2 (Battlefield)'),
(133, 83, 'Air Transport', 'Maneuver', '1', '2'),
(134, 83, 'Air Transport', 'Cargo', '3 Moderate', '3 Major'),
(135, 83, 'Air Transport', 'Life Support', 'none', 'Moderate (12 people)'),
(136, 83, 'Air Transport', 'Computer', 'Minor 2 (16 target)', 'Minor 3 (18 target)'),
(137, 83, 'Air Transport', 'Tasks', 'Pilot 16', 'Pilot 16, Intrusion Detection 17'),
(138, 84, 'Air Transport', 'Body Track', '80', '90'),
(139, 85, 'Assault Platform', 'Body Track', '80', '90'),
(140, 86, 'Attack Hovercraft', 'Weapon Multiplier (single target)', '4x', '5x'),
(141, 87, 'Armored Personnel Carrier', 'Armor Rating', '3 (Battlefield)', '4 (Battlefield)'),
(142, 87, 'Armored Personnel Carrier', 'Weapon Multiplier (single target)', '4x', '5x'),
(143, 87, 'Armored Personnel Carrier', 'Hangar', 'Minor', 'Major'),
(144, 88, 'Armored Personnel Carrier', 'Power Supply', 'Moderate Fusion 1', 'Moderate Fusion 2'),
(145, 88, 'Armored Personnel Carrier', 'Total Power Slots', '3 Minor (2 used), 3 Moderate (0 used)', '3 Minor (0 used), 6 Moderate (2 used)'),
(146, 89, 'Attack Hovercraft', 'Power Supply', 'Moderate Fusion 1', 'Moderate Fusion 2'),
(147, 89, 'Attack Hovercraft', 'Total Power Slots', '3 Minor (0 used), 3 Moderate (3 used)', '3 Minor (0 used), 6 Moderate (2 used)'),
(148, 90, 'Attack Hovercraft', 'Body Track', '80', '90'),
(149, 91, 'Armored Personnel Carrier', 'Body Track', '80', '90'),
(150, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Weapon Multiplier', '4x', '5x'),
(151, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Power Supply', 'none', 'Major Coil, rank 1'),
(152, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Charge', 'none', '1 Major (10 combat rounds)'),
(153, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Maneuver', '5', '3'),
(154, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Limitation', 'Usage Restriction (ineffective at Far Range), Minor', 'No Far Range, Moderate'),
(155, 92, 'Autonomous Kill Vehicle (“Auntie”)', 'Total Power Slots', '3 Moderate (1 used)', '3 Moderate (0 used), 3 Major (1 used)'),
(156, 93, 'Recon Drone', 'Maneuver', '5', '4'),
(157, 93, 'Recon Drone', 'Computer', 'Minor 2 (16 target)', 'Minor 3 (18 target)'),
(158, 94, 'Stealth FTL Recon Drone', 'CR', '5', '6'),
(159, 94, 'Stealth FTL Recon Drone', 'CC', '15', '21'),
(160, 94, 'Stealth FTL Recon Drone', 'Body Track', '15', '10'),
(161, 94, 'Stealth FTL Recon Drone', 'Fuel', '5 Moderate + 1 Major', '2 Major (shared)'),
(162, 94, 'Stealth FTL Recon Drone', 'Maneuver', '4', '2 (Major grade)'),
(163, 94, 'Stealth FTL Recon Drone', 'Tangle', '2 Major', '1 Major'),
(164, 94, 'Stealth FTL Recon Drone', 'Tags', '[High Security 3], [I Spy with my Little Eye...]', '[Security 2], [I Spy with my Little Eye...]'),
(165, 94, 'Stealth FTL Recon Drone', 'Limitations', 'none', 'One Track Mind (Moderate), One-Time Use (Major)'),
(166, 95, 'Telekinetic Shuttle', 'Resource', '2 Major Fuel', '2 Major Charge'),
(167, 96, 'Shuttle/Yacht', 'Tasks', 'none', 'Pilot 17'),
(168, 96, 'Shuttle/Yacht', 'Tag', 'none', '[The Grand Tour 3] (Free)'),
(169, 96, 'Shuttle/Yacht', 'Tangle', '1', '2 (20 days)'),
(170, 97, 'Locust Mobile Industrial Platform', 'Armor Rating', '1 (Space)', '2 (Space)'),
(171, 97, 'Locust Mobile Industrial Platform', 'Body Track', '200', '250'),
(172, 97, 'Locust Mobile Industrial Platform', 'Maneuver', 'none', '1'),
(173, 98, 'Locust Mobile Industrial Platform', 'Total Power Slots', '6 (3 used)', '6 Major (3 used)'),
(174, 99, 'Factory Freighter', 'Drive', 'Major Reaction', 'Moderate Reaction'),
(175, 99, 'Factory Freighter', 'Hangar', '3 Major', '2 Major'),
(176, 99, 'Factory Freighter', 'Life Support', '6 Major (600 people)', '5 Major (500 people)'),
(177, 99, 'Factory Freighter', 'Computer', 'Major 3 (18 target, 5 tasks)', 'Major 3 (18 target)'),
(178, 99, 'Factory Freighter', 'CR', '8', '9'),
(179, 99, 'Factory Freighter', 'CC', '36', '45'),
(180, 100, 'Security Escort/Corsair', 'Total Power Slots', '9 Major (4 used)', '6 Major (2 used), 3 Moderate (0 used)'),
(181, 101, 'Standard Assault Shuttle', 'Launchers', '2 (Space)', '4 (Space)'),
(182, 102, 'Standard Assault Shuttle', 'Communications', 'none', 'Moderate (Radio)'),
(183, 103, 'Tanker/Command Ship', 'Fuel', '100 Major Fuel (Resource)', 'Bulk fuel stores carried as Cargo'),
(184, 104, 'Tanker/Command Ship', 'Armor Rating', '3 (Space)', '4 (Space)'),
(185, 105, 'Tanker/Command Ship', 'Fuel', 'not printed', '10 Major (100 days)'),
(186, 106, 'System Defense Craft (Pocket Cruiser)', 'Alternate forms: missile array', 'missile array', '4 Launchers'),
(187, 106, 'System Defense Craft (Pocket Cruiser)', 'Alternate forms: particle cannon', 'particle cannon', 'heavy railgun'),
(188, 107, 'Dragon-class Fleet Interceptor/Escort', 'Power Supply', 'none', 'Major Fusion, rank 1 (auxiliary)'),
(189, 107, 'Dragon-class Fleet Interceptor/Escort', 'Total Power Slots', '6 Moderate (6 used)', '6 Moderate, 3 Major'),
(190, 108, 'Dragon-class Fleet Interceptor/Escort', 'Drive', 'Moderate Air', 'Minor Air'),
(191, 108, 'Dragon-class Fleet Interceptor/Escort', 'Launchers', '6 (Space)', '8 (Space)'),
(192, 109, 'Dragon-class Fleet Interceptor/Escort', 'Fuel', '2 Moderate', '2 Major'),
(193, 110, 'Bridgehead Assault Shuttle', 'Armor Rating', '3 (Space)', '4 (Space)'),
(194, 110, 'Bridgehead Assault Shuttle', 'Weapon Multiplier', '4x', '5x'),
(195, 111, 'Phantom Deep Recon and Insertion Vehicle (DRIV)', 'Communication', 'none', 'Moderate Laser Link'),
(196, 112, 'Bridgehead Assault Shuttle', 'Bleed', 'Major 3', 'Major 2'),
(197, 112, 'Bridgehead Assault Shuttle', 'Total Power Slots', '3 Moderate (3 used), 3 Major (3 used)', '3 Moderate (1 used), 3 Major (3 used)'),
(198, 113, 'Standard Cruiser', 'Power Supply', 'none', 'Major Fusion 1'),
(199, 113, 'Standard Cruiser', 'Total Power Slots', '3 Major (2 used), 3 Moderate (0 used)', '6 Major (4 used), 3 Moderate (0 used)'),
(200, 114, 'Standard Cruiser', 'Computer', 'none', 'Major 3 (18 target)'),
(201, 115, 'Conventional Frigate', 'Crew Requirement', '10 skeleton, 20 full', '100 skeleton, 200 full'),
(202, 116, 'Conventional Frigate', 'Launchers', '6 (Space)', '8 (Space)'),
(203, 117, 'Resolute-class Frigate', 'Armor Rating', '4 (Space)', '5 (Space)'),
(204, 117, 'Resolute-class Frigate', 'Weapon Multiplier', '6x', '7x'),
(205, 118, 'Redemption-class Frigate', 'Launchers', '6 (Space)', '4 (Space)'),
(206, 118, 'Redemption-class Frigate', 'Total Power Slots', '9 Major (7 used)', '9 Major (7 used), 3 Moderate (0 used)'),
(207, 119, 'Retribution-class Frigate', 'Anti-Missile', 'Anti-Missile (Space) 2x', 'Anti-Missile (Space) 1x'),
(208, 119, 'Retribution-class Frigate', 'Total Power Slots', '9 Major (7 used)', '9 Major (6 used)'),
(209, 120, 'Retribution-class Frigate', 'Drive', 'Major Reaction', 'Moderate Reaction'),
(210, 120, 'Retribution-class Frigate', 'Total Power Slots', '9 Major (6 used)', '6 Major (6 used), 3 Moderate (0 used)'),
(211, 121, 'Fleet Auxiliary', 'Fuel', '300 Major Fuel (Resource)', 'Bulk fuel stores carried as Cargo'),
(212, 122, 'Marine LASCO (Launch, Support, and Command) Vessel', 'Fuel', '13 Major', '10 Major (100 days)'),
(213, 122, 'Marine LASCO (Launch, Support, and Command) Vessel', 'Limitation', 'none', 'Prerequisite [Property of the Terran Sphere] (Moderate)'),
(214, 123, 'Fleet Auxiliary', 'Fuel', 'not printed', '11 Major (110 days)'),
(215, 124, 'Arniston (Unique Armed Merchantman)', 'Total Power Slots', 'missing', '6 Major (3 used)'),
(216, 125, 'Arniston (Unique Armed Merchantman)', 'Manufacture', 'Moderate', 'Major'),
(217, 125, 'Arniston (Unique Armed Merchantman)', 'Link', 'none', 'Major Weapon'),
(218, 125, 'Arniston (Unique Armed Merchantman)', 'Modifier', 'Detection +1', 'Detection +2'),
(219, 125, 'Arniston (Unique Armed Merchantman)', 'Total Power Slots', '6 Major (3 used)', '6 Major (4 used)'),
(220, 126, 'Arniston (Unique Armed Merchantman)', 'Fuel', '6 Major Fuel (6 days/combat rounds)', '6 Major Fuel (60 days/combat rounds)'),
(221, 127, 'Havenite Lilith Carrier', 'Attack', 'Heavy particle cannon 6x (2 mounts)', 'Heavy particle cannon 7x (2 mounts)'),
(222, 127, 'Havenite Lilith Carrier', 'Armor Rating', '3 (Space)', '5 (Space)'),
(223, 127, 'Havenite Lilith Carrier', 'Cargo', '1 Huge', '2 Major'),
(224, 127, 'Havenite Lilith Carrier', 'Manufacture', 'none', 'Major'),
(225, 127, 'Havenite Lilith Carrier', 'Limitation', 'Unique Fuel (Antimatter)', 'Unique Fuel (Antimatter) (Major)'),
(226, 127, 'Havenite Lilith Carrier', 'Total Power Slots', 'none', '6 Major (5 used)'),
(227, 128, 'Havenite Marauder', 'Armor Rating', '5 (Space)', '4 (Space)'),
(228, 128, 'Havenite Marauder', 'Drive', 'Major Reaction, Major Gravitic', 'Moderate Reaction'),
(229, 128, 'Havenite Marauder', 'Power Supply', 'none', 'Major Antimatter, rank 1'),
(230, 128, 'Havenite Marauder', 'Limitation', 'Unique Fuel (Antimatter)', 'Unique Fuel (Antimatter) (Major)'),
(231, 128, 'Havenite Marauder', 'Tasks', 'Intrusion Detection 20', 'none'),
(232, 128, 'Havenite Marauder', 'Total Power Slots', 'none', '3 Major, 3 Moderate (3 Major used)'),
(233, 129, 'Havenite Marauder', 'Magazine', 'Major Magazine (640 shots)', '6 Major Magazine (60 shots)'),
(234, 130, 'Havenite Marauder', 'Launchers', '6 (Space)', '8 (Space)'),
(235, 131, 'Heavy Railgun', 'Weapon Multiplier', '6x', '7x'),
(236, 131, 'Heavy Railgun', 'Body Track', '10', '50'),
(237, 132, 'Heavy Laser Cannon', 'Weapon Multiplier', '7x', '8x'),
(238, 132, 'Heavy Laser Cannon', 'Body Track', '10', '50'),
(239, 133, 'Havenite Lamprey', 'Drive', 'Reactionless', 'Major Gravitic (modified, in-system)'),
(240, 133, 'Havenite Lamprey', 'Limitation', 'none', 'Usage Restriction: in-system only (Minor)'),
(241, 133, 'Havenite Lamprey', 'Limitation', 'none', 'One-Time Use (Major)'),
(242, 134, 'Havenite Lamprey', 'Fuel', '4 Major Fuel (4 days/combat rounds)', '4 Major Fuel (40 days/combat rounds)'),
(243, 135, 'Heavy Railgun', 'Power Requirement', 'none', '1 Major slot'),
(244, 136, 'Quad Missile Pack', 'Magazine', '2 Major Magazines (80 shots)', '8 Major Magazines (80 shots)'),
(245, 137, 'Basic Security Software', 'Size', 'not printed', 'Small'),
(246, 137, 'Security Software', 'Size', 'not printed', 'Small'),
(247, 137, 'Traceback', 'Size', 'not printed', 'Tiny'),
(248, 137, 'Honey Pot', 'Size', 'not printed', 'Tiny'),
(249, 138, 'Security Software', 'Tag', 'none', '[This Is A Private Conversation 2] (Free)'),
(250, 138, 'Security Software', 'Tag', 'none', '[I See You 2] (Free)'),
(251, 139, 'Honey Pot', 'Tag rank: [The Wages of Sin]', '1', '2'),
(252, 140, 'Cover Identity', 'Size', 'not printed', 'Tiny'),
(253, 140, 'Good Cover Identity', 'Size', 'not printed', 'Tiny'),
(254, 141, 'Military-Grade Security', 'Tasks', 'Intrusion Detection 20, Trace 20, Compromise 20', 'Intrusion Detection 20, Trace 20'),
(255, 141, 'Military-Grade Security', 'Tag', '[I See You 3]', '[I See You 3] (Free)'),
(256, 141, 'Military-Grade Security', 'Tag', '[Like Fort Knox]', '[Like Fort Knox 3] (Free)'),
(257, 141, 'Military-Grade Security', 'Tag', 'none', '[This Is A Private Conversation 2] (Free)'),
(258, 142, 'Tse Blade', 'Weapon Multiplier (both attacks)', '4x', '5x'),
(259, 143, 'Shohan Personal Armor', 'Armor scale', 'Firefight', 'Battlefield'),
(260, 144, 'Tse Blade', 'Tag type: [Flexible Geometry Blade]', 'Standard', 'Free'),
(261, 144, 'Tse Blade', 'Tag', '[Where Did You Get Your Hands on One?] (conditional)', 'Standard Tag'),
(262, 144, 'Tse Blade', 'CR', '5', '4'),
(263, 144, 'Tse Blade', 'CC', '15', '10'),
(264, 145, 'Shohan Personal Armor', 'Regeneration: Biological', '4 (grade not printed)', '4, Moderate'),
(265, 145, 'Shohan Personal Armor', 'Regeneration: Force Field', '4 (grade not printed)', '4, Major'),
(266, 145, 'Shohan Personal Armor', 'Limitation', 'none', 'Malfunction [Emergent Altered], Moderate'),
(267, 145, 'Shohan Personal Armor', 'Limitation', 'none', 'Target On Your Back, Moderate'),
(268, 146, 'Shohan Personal Armor', 'Links', '2 Weapon', '2 Moderate Weapon'),
(269, 146, 'Shohan Personal Armor', 'Limitation', 'none', 'Usage Restriction: Weapons +2 only with Link weapons (Minor)'),
(270, 146, 'Shohan Personal Armor', 'Computer', 'Moderate 3', 'Minor 3'),
(271, 146, 'Shohan Personal Armor', 'Modifier', 'Athletics +2', 'Athletics +1'),
(272, 146, 'Shohan Personal Armor', 'Body Track', '40', '45'),
(273, 147, 'Shohan Personal Armor', 'Modifier', 'Weapons +2', 'Weapons (Melee, Heavy Weapons) +2'),
(274, 147, 'Shohan Personal Armor', 'Limitation: Target On Your Back', 'Moderate', 'Major'),
(275, 148, 'War Drone (Cerberus)', 'Body Track', '40', '80'),
(276, 148, 'War Drone (Cerberus)', 'Armor Rating', '4', '5'),
(277, 149, 'War Drone (Cerberus)', 'Computer', 'Moderate Brain 3 (18 target)', 'Moderate Brain 4 (20 target)'),
(278, 150, 'Resistance Lumber Mech', 'Body Track', '80', '70'),
(279, 150, 'Resistance Lumber Mech', 'Resource', '2 Moderate Fuel', '2 Moderate Charge'),
(280, 150, 'Resistance Lumber Mech', 'Tag type: [Kinetic Feedback Control Rig]', 'Standard', 'Free'),
(281, 151, 'Resistance Lumber Mech', 'Total Power Slots', '2 Minor (0 used), 3 Moderate (1 used)', '3 Minor (0 used), 3 Moderate (1 used)'),
(282, 152, NULL, 'Strain cost', NULL, '1 per round or scene maintained'),
(283, 154, NULL, 'Damage-to-strain ratio', '3 strain per 1 damage', '1 strain per 1 damage');
